db/db.go
Improved PutIfNotExists for memory store to make it safe for concurrent use. The new implementation uses PutIfNotExists method from the syncmap which performs atomic insert.
Details about the LoadOrStore method - https://godoc.org/golang.org/x/sync/syncmap#Map.LoadOrStore
(this PR is working copy of the broken PR #13)
=> Updated PutIfNotExists method for memory kv to make it safe for concurrent use

config/config.go, config/config_test.go, consensus/scheme/rolldpos/fsm.go, consensus/scheme/rolldpos/fsm_test.go, consensus/scheme/rolldpos/rolldpos.go, consensus/scheme/rolldpos/rolldpos_test.go
For every block height, the node will check the timespan since last block, and determine if it's whose slot.
In addition, I fixed the clock usage in the consensus module.
=> IOTEX-2 Support time based rotation on proposing a block

.codecov.yml
70% may not always make sense. For example, the original code coverage is low. We should use auto instead, which enforces the coverage doesn't go down after patch.
=> Adjust codecov patch coverage target to auto

consensus/scheme/rolldpos/rolldpos_test.go, logger/README.md
According to the log: https://circleci.com/gh/iotexproject/iotex-core/414, the test failed as simple as time limit too short. After 5 secs, it only committed block 1. I enlarge the wait period to 10 secs.
=> Fix network-partition-time-rotation sporadic test failure

server/itx/heartbeat.go
when committing metrics, all labels have to set value
=> fix panic cause by metrics label mismatch

consensus/scheme/rolldpos/rolldpos.go, consensus/scheme/rolldpos/rolldpos_test.go
Say "no" number of "no" is more than 1/3 of delegates.
We could remove self notification, and jump from Prepare to eFinishEpoch if Prepare's decision is "no", which I will do in a follow up PR
=> reset the boundary of 'no' decision

action/const.go, actpool/actpool.go, actpool/actpool_test.go, blockchain/block.go, blockchain/blockvalidator.go, blockchain/evm.go, consensus/scheme/rolldpos/fsm.go
If the received endorse is of different block, reject these endorses. This will prevent two blocks reach consensus at the same time.
=> Check endorse block hash

action/subchain/protocol.go, action/subchain/protocol_test.go, blockchain/block.go, blockchain/block_test.go, blockchain/blockchain.go, blockchain/blockchain_test.go, blockchain/evmstatedbadapter.go, blocksync/slidingwindow.go, consensus/scheme/rolldpos/rolldpos_test.go, explorer/explorer_test.go, misc/scripts/mockgen.sh, state/account.go, state/candidate.go, state/candidate_test.go, state/contract.go, state/contract_test.go, state/factory.go, state/factory_test.go, state/state.go, state/workingset.go, test/mock/mock_actpool/mock_actpool.go, test/mock/mock_blockchain/mock_blockchain.go, test/mock/mock_state/mock_state.go, test/mock/mock_state/mock_workingset.go
1. Define the state interface with common methods that state factory only needs to understand
2. Expose generic state manipulation methods from WorkingSet
3. Relocating original State struct to AccountState
=> IOTEX-109 Define state interface and make working set expose generic state manipulation methods

consensus/scheme/rolldpos/fsm.go, consensus/scheme/rolldpos/fsm_test.go, consensus/scheme/rolldpos/rolldpos.go, consensus/scheme/rolldpos/rolldpos_test.go, endorsement/endorsement.go, endorsement/endorsementset.go
Previously, we use maps to count the number of endorsements for block proposal and block commit. With endorsementSet, we replace these maps with an endorsement set
=> Use endorsement.Set to log all the endorsements

trie/trie.go, trie/trie_test.go
toRoot is not supposed to be a class level parameter. Replace it with local parameter which will be returned by function query. With this implementation, we can delete function clear, and change the lock of function Get to RLock
=> create pathToRoot type and delete clear

action/subchain/datamodel.go, action/subchain/datamodel_test.go, action/subchain/protocol.go, action/subchain/startsubchain.go, action/subchain/startsubchain_test.go, state/state.go, state/state_test.go
The reason of doing this is to get all sub chain in operation account at restart, and start the services for them.
=> IOTEX-121 Persist the sub-chain address together with the used Chain IDs

consensus/scheme/rolldpos/fsm.go, consensus/scheme/rolldpos/fsm_test.go, proto/blockchain.pb.go
In initPropose:
non-proposers jump directly to the AcceptPropose;
proposer proposes a block and then jump to the AcceptPropose step.
Which helps simplify the logic.
=> Unify the initPropose step for proposer and non-proposer

endorsement/endorsementset.go, endorsement/endorsementset_test.go
different consensus vote topics from the same user were counted twice
=> prevent double counting from same endorser

e2etest/multichain_test.go, server/itx/server.go
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0x43b320d]
goroutine 30 [running]:
github.com/iotexproject/iotex-core/vendor/github.com/boltdb/bolt.(*DB).beginRWTx(0x0, 0x0, 0x0, 0x0)
/Users/zjshen/Projects/go/src/github.com/iotexproject/iotex-core/vendor/github.com/boltdb/bolt/db.go:506 +0x3d
github.com/iotexproject/iotex-core/vendor/github.com/boltdb/bolt.(*DB).Begin(0x0, 0x47a7a01, 0xc4202d7be8, 0x402c469, 0xc42024a030)
/Users/zjshen/Projects/go/src/github.com/iotexproject/iotex-core/vendor/github.com/boltdb/bolt/db.go:461 +0x38
github.com/iotexproject/iotex-core/vendor/github.com/boltdb/bolt.(*DB).Update(0x0, 0xc4202d7c28, 0x0, 0x0)
/Users/zjshen/Projects/go/src/github.com/iotexproject/iotex-core …
```
=> Fix the 2-chain e2e test failure in console

blockchain/blockchain.go, blockchain/genesis.go, config/config.go, consensus/consensus.go, server/itx/subchain.go, state/candidate.go, state/workingset.go
1. Clean up the code of handling genesis block state mutation
2. Relax the assumption that candidates always exist
3. The code to check if we should use empty genesis block is not refined. There requires a future code refactor work to make genesis block creation more coherent
=> IOTEX-143 Make sub-chain start from an empty genesis block

action/protocols/account/protocol_test.go, action/transfer.go, action/transfer_test.go, blockchain/block_test.go, blockchain/blockchain.go, blockchain/blockchain_test.go, blockchain/blockdao.go, blockchain/blockdao_test.go, explorer/explorer.go
Previously all coinbase transfers have the same hash, so that indexing them via hash was broken. This PR will leverage block height to set nonce of coinbase transfer, so that the hash will be unique then.
Additionally, fix a coinbase flag bug in the explorer together
=> IOTEX-152 Add block height info into the coinbase transfer as the nonce

consensus/scheme/rolldpos/fsm.go
The commit endorsement is a dummy one, which cannot be skipped right now.
=> keep self endorsement

blocksync/blocksync.go, blocksync/buffer.go, server/itx/heartbeat.go
Assume the block to sync is h, confirmed block is c. If c+1 is in buffer and there is a block in (c+1, h) not in buffer, target height won't get set.
=> fix block sync bug

action/protocols/multichain/mainchain/createdeposit_test.go, action/protocols/multichain/mainchain/startsubchain_test.go, blockchain/blockchain.go, blockchain/blockchain_test.go, blockchain/blockcreationsubscriber.go, chainservice/chainservice.go, indexservice/indexer.go, indexservice/server.go, server/itx/server.go, server/itx/subchain.go, server/main.go, test/mock/mock_blockchain/mock_blockchain.go
1. Delete channel
2. Delete routine
3. Implement Indexer and Server as subscribers
=> change block creation subscription implementation

blocksync/blocksync.go, blocksync/blocksync_test.go
If a node has temporary outage, but is unfortunately be chosen as the proposer during this period, there's no chance for the whole network to recover, because no flying broadcasted block exist, and the node wouldn't able to proactively catchup the missing blocks.
This PR makes the node to tentatively request tip height + 1 block every 10 block sync interval, so that it could recover and catch up other delegates to continue consensus. This will not be very efficient if a node miss tons of blocks, but a working solution for short-term outage.
=> IOTEX-157 Make blocksync tentatively sync tip height + 1 block

consensus/scheme/rolldpos/fsm.go
the log entry is too large. it is unreadable and it break zerolog
=> remove log which logs the whole block

action/protocol/execution/evm/evmstatedbadapter.go, action/protocol/execution/evm/evmstatedbadapter_test.go
This reverts commit b473d2e7dd3de6ee65b163365f4a01437a92c65d.
=> Disable Snapshot() function before solving the memory thrash/leak (#384)

action/protocol/execution/evm/evm.go, action/protocol/execution/evm/evmstatedbadapter.go, action/protocol/execution/evm/evmstatedbadapter_test.go, action/protocol/execution/protocol.go
Test plan: unit test.
Potential problem: In some cases of contract creation, the nonce won't be increased, e.g., https://github.com/CoderZhi/go-ethereum/blob/master/core/vm/evm.go#L348-L353. The second error type shouldn't happen if we check the balance transfer in action pick. These two errors could only happen when the contract creation call is triggered by another contract execution. Thus, we leave this problem in future investigation.
=> implement set nonce for adapter

blockchain/blockchain.go, blockchain/blockchain_test.go, blockchain/blockdao.go, blocksync/buffer.go, consensus/consensus.go, consensus/scheme/rolldpos/rolldpos.go, db/batch.go, db/batch_test.go, db/db.go, db/db_badger.go, db/db_bolt.go, db/db_test.go
PutIfNotExists semantics is confusing, and shouldn't be decided by the database. Removing it from db api.  In addition, I update the use case accordingly. Some could use regular put api.
Test Plan: updated unit tests, make reboot & run
=> IOTEX-192 Removing PutIfNotExists API db

explorer/explorer.go, explorer/explorer_test.go, explorer/idl/explorer.idl, explorer/idl/explorer/explorer.go, state/factory/factory.go, state/factory/factory_test.go, state/factory/workingset.go, test/mock/mock_explorer/mock_explorer.go, test/mock/mock_factory/mock_factory.go
The API is added for us to debug state related issues.
Test plan: unit tests added for factory and explorer, and verified it a real cluster
=> IOTEX-197 Keep tracking root hash history and serve it via explorer API

action/protocol/execution/protocol_test.go, blockchain/block/builder.go, blockchain/block/builder_test.go, blockchain/block/runnable.go, blockchain/blockchain.go, blockchain/blockchain_test.go, blockchain/blockvalidator_test.go, blockchain/genesis_test.go, blocksync/blocksync_test.go, blocksync/buffer_test.go, consensus/consensus.go, consensus/scheme/rolldpos/fsm_test.go, consensus/scheme/rolldpos/rolldpos.go, consensus/scheme/rolldpos/rolldpos_test.go, e2etest/local_test.go, e2etest/util.go, explorer/explorer_test.go, test/mock/mock_blockchain/mock_blockchain.go
Split parameter iotxaddress to public key, private key, and raw address. This change is a preparation for the full migration to address v1. In next PR, raw address will be replaced by Bech32 encoded string address.
=> IOTEX-205 Modify MintNewBlock to remove the dependency on iotxaddress

pkg/prometheustimer/timer.go
This is a harmless error.
Tested with uint tests: The error won't be returned or printed
=> mute AlreadyRegisteredError

blockchain/blockchain_test.go, blockchain/blockvalidator_test.go, db/db_badger.go, db/db_bolt.go, explorer/explorer_test.go
Remove the dedup logic on starting db, and make sure db only will be started once
Remove setting db = nil logic to avoid panic of receiving db op request after calling stop
=> Ensure db is only started and stopped once in the tests

Gopkg.lock, Gopkg.toml, tools/util/injectorutil.go, vendor/github.com/cenkalti/backoff/.gitignore, vendor/github.com/cenkalti/backoff/.travis.yml, vendor/github.com/cenkalti/backoff/LICENSE, vendor/github.com/cenkalti/backoff/README.md, vendor/github.com/cenkalti/backoff/backoff.go, vendor/github.com/cenkalti/backoff/context.go, vendor/github.com/cenkalti/backoff/exponential.go, vendor/github.com/cenkalti/backoff/retry.go, vendor/github.com/cenkalti/backoff/ticker.go, vendor/github.com/cenkalti/backoff/tries.go
adding exponential back off  with a long time out.
so injector won't crash on blockchain slow start/restart phase.
=> [Injector] Exponential back off with 15mins time out on injector getting address details

consensus/consensusfsm/fsm.go, consensus/consensusfsm/fsm_test.go, consensus/scheme/rolldpos/rolldpos.go
As the mint time is fixed, a proposer could start minting block right after receiving last block. Thus, the proposer has more time to mint a block if everything goes fine.
=> Start minting block right away

config/config.go, config/config_test.go, consensus/consensusfsm/fsm.go, consensus/consensusfsm/fsm_test.go, consensus/scheme/rolldpos/rolldpos_test.go, consensus/scheme/rolldpos/rolldposctx.go, consensus/scheme/rolldpos/rolldposctx_test.go, tools/minicluster/minicluster.go
Once a delegate enters the pre-commit status (collect enough lock endorsements), it will for sure collect commit eventually with enough other delegates. If a delegate doesn't collect lock endorsements in time, it will go back to Prepare status. Thus, the eFailedToReachConsensusInTime shouldn't be there.
As the eFailedToReachConsensusInTime is deleted, ProposalInterval could be merged with DelegateInterval.
Test plan: uint test, and make minicluster
=> Remove eFailedToReachConsensusInTime

consensus/scheme/rolldpos/rolldpos.go, consensus/scheme/rolldpos/rolldposctx.go
This will prevent the potential discarding of consensus messages if blockchain height was increased by block sync.
=> use consensus height to filter incoming messages

blockchain/blockchain.go, blockchain/blockchain_test.go, server/main.go
Previously we only support recovering state db to a specific height which is lower than the blockchain height if and only if the existing state db height is lower than the target height. Now the state db can recover to any lower target height by clearing the existing state db and rebuilding it from scratch.
=> Make state recover from empty if the recovery height is lower than the current state height

action/actctx.go, action/action.go, action/action_test.go, action/builder.go, action/builder_test.go, action/claimreward.go, action/createdeposit.go, action/depositreward.go, action/execution.go, action/grantreward.go, action/protocol/execution/protocol_test.go, action/protocol/vote/protocol_test.go, action/putblock.go, action/setreward.go, action/settledeposit.go, action/stopsubchain.go, action/transfer.go, action/vote.go, api/api_test.go, blockchain/block/block_test.go, blockchain/blockdao.go, blockchain/blockdao_test.go, blockchain/genesis_test.go, blockchain/indexbuilder.go, indexservice/indexer.go, tools/util/injectorutil.go
remove dstAddr and make go action structs have one to one field mapping with it's proto definition
=> make go action structs have one to one field mapping with it's proto definition

action/protocol/execution/protocol_test.go, action/protocol/multichain/mainchain/protocol_test.go, action/protocol/multichain/mainchain/startsubchain_test.go, action/protocol/multichain/subchain/protocol_test.go, action/protocol/rewarding/protocol_test.go, actpool/actpool_test.go, api/api_test.go, blockchain/blockchain.go, blockchain/blockchain_test.go, blockchain/blockdao_test.go, blockchain/blockvalidator_test.go, blockchain/genesis/genesis.go, blocksync/blocksync_test.go, blocksync/buffer_test.go, chainservice/chainservice.go, config/config.go, config/config_test.go, consensus/consensus.go, consensus/scheme/rolldpos/epochctx.go, consensus/scheme/rolldpos/epochctx_test.go, consensus/scheme/rolldpos/rolldpos.go, consensus/scheme/rolldpos/rolldpos_test.go, consensus/scheme/rolldpos/rolldposctx.go, consensus/scheme/rolldpos/rolldposctx_test.go, e2etest/local_test.go, explorer/explorer_test.go, server/main.go, tools/minicluster/minicluster.go
Append genesis to the config struct internally to make it easy to pass genesis around. It's a breaking change.
=> IOTEX-275 Move network-wide consensus config to genesis config and refactor code

action/protocol/account/protocol_test.go, action/protocol/execution/evm/contract_test.go, action/protocol/execution/protocol_test.go, action/protocol/multichain/mainchain/createdeposit_test.go, action/protocol/multichain/mainchain/putblock_test.go, action/protocol/multichain/mainchain/startsubchain_test.go, actpool/actpool_test.go, api/api_test.go, blockchain/blockchain.go, blockchain/blockchain_test.go, blockchain/blockvalidator_test.go, consensus/scheme/rolldpos/rolldpos_test.go, explorer/explorer_test.go, state/factory/factory_test.go, state/factory/statetx.go, state/factory/workingset.go
Since we don't need state root anymore, there is no need to return state root after processing actions in block.
=> Disable returning state root from runActions

consensus/scheme/rolldpos/rolldpos_test.go, pkg/log/log.go
I know it makes sense to have debug level for unit tests, but our debug level logging are too verbose to be useful, and make the test run further slower.
Also tune some parameters. Hopefully the tests could be less fragile. Let's see.
=> IOTEX-259 Try to make consensus unit tests less likely fail

consensus/consensusfsm/fsm.go
First of all, this fix is hacky, and we need to look for a more appropriate strategy of handling block height being updated when running consensus.
Anyway, this PR is trying to prevent calibrate events from flooding, especially when a node are syncing bunch of blocks from peers. When the node is already at prepare stage, there's no sense to calibrate it any more.
=> Avoid flooding of calibrate events

Dockerfile
This is to copy the ioctl into the container image
After running a docker build and executing the new image interactively you can run command as expected
```
root@a673eb07f202:/go/src/github.com/iotexproject/iotex-core# ioctl 
ioctl is a command-line interface for interacting with IoTeX blockchain.
Usage:
ioctl [command]
Available Commands:
account     Deal with accounts of IoTeX blockchain
action      Deal with actions of IoTeX blockchain
bc          Deal with block chain of IoTeX blockchain
config      Set or get configuration for ioctl
help        Help about any command
version     Print the version number of ioctl
wallet      Manage accounts
Flags:
-h, --help   help for ioctl
Use "ioctl [command] --help" for more information about a command.
```
=> updated Dockerfile to include ioctl copy

action/protocol/execution/protocol_test.go, api/api_test.go, blockchain/blockchain.go, blockchain/blockchain_test.go, blockchain/blockvalidator_test.go, blocksync/blocksync_test.go, blocksync/buffer_test.go, config/config.go, consensus/consensus.go, consensus/scheme/rolldpos/rolldpos_test.go, consensus/scheme/rolldpos/rolldposctx.go, consensus/scheme/rolldpos/rolldposctx_test.go, e2etest/local_test.go, e2etest/util.go, explorer/explorer_test.go, test/mock/mock_blockchain/mock_blockchain.go
Producer identity is already cached in blockchain struct via config. There's no need to pass it every time we mint a block, which has two risks: always passing secure stuff around; using wrong (or different) key to mint a block.
Test plan: tests + minicluster run
=> Remove producer identity information from mint block method

blockchain/blockchain.go, server/itx/server.go, tools/minicluster/minicluster.go
Fix no-receipt after contract deployment issue in mini cluster setting.
1.Add receipt setting in validateBlock, so receipt will be sent to other servers.
2.Add server context to track which sever is in the current context for easy debuging.
=> IOTEX-290 Fix minicluster nightly build error

api/api.go
Categorize API errors by different GRPC error codes and return status error which can be converted by client.
=> IOTEX-273 Change API error schema

blocksync/blocksync.go, blocksync/buffer.go, blocksync/buffer_test.go, blocksync/slidingwindow.go, blocksync/worker.go, config/config.go
This will not necessarily improve the sync speed, because the bottleneck is at committing block side. However, this will prevent network to become the bottleneck and evenly spread the workload among all peers in the syncing mode.
Tested it with testnet v0.5.0-rc2
=> IOTEX-294 Improve block sync scheduling

action/protocol/multichain/mainchain/protocol_test.go, actpool/actpool.go, actpool/actpool_test.go, config/config.go, e2etest/local_actpool_test.go, e2etest/local_test.go, e2etest/local_transfer_test.go, test/mock/mock_actpool/mock_actpool.go, tools/minicluster/minicluster.go
Two things:
1. Make polling pending actions get rid of expired actions, so that if there's a bad action, it will eventually be removed and the block production will not be blocked forever.
2. Cleanup unused action pool API and config
=> IOTEX-276 Make polling pending actions get rid of expired actions and refactor actpool code

cli/ioctl/cmd/bc/bc.go, cli/ioctl/cmd/bc/bcheight.go, cli/ioctl/cmd/node/node.go, cli/ioctl/cmd/node/nodedelegate.go, cli/ioctl/cmd/node/nodeproductivity.go
tested on local single-node
➜  ioctl git:(ioctl) ✗ ./ioctl node delegate
blockProducers: "io1juvx5g063eu4ts832nukp4vgcwk2gnc5cu9ayd"
blockProducers: "io1llupp3n8q5x8usnr5w08j6hc6hn55x64l46rr7"
blockProducers: "io1hh97f273nhxcq8ajzcpujtt7p9pqyndfmavn9r"
blockProducers: "io1ph0u2psnd7muq5xv9623rmxdsxc4uapxhzpg02"
blockProducers: "io19kshh892255x4h5ularvr3q3al2v8cgl80fqrt"
blockProducers: "io1fxzh50pa6qc6x5cprgmgw4qrp5vw97zk5pxt3q"
blockProducers: "io1xuavja5dwde8pvy4yms06yyncad4yavghjhwra"
blockProducers: "io1eq4ehs6xx6zj9gcsax7h3qydwlxut9xcfcjras"
blockProducers: "io13sj9mzpewn25ymheukte4v39hvjdtrfp00mlyv"
blockProducers: "io158hyzrmf4a8xll7gfc8xnwlv70jgp44tzy5nvd"
blockProducers: "io1jh0ekmccywfkmj7e8qsuzsupnlk3w5337hjjg2"
blockProducers: "io1vrl48nsdm8jaujccd9cx4ve23cskr0ys6urx92" …
=> Add node productivity cmd for ioctl

Gopkg.lock, Gopkg.toml, consensus/scheme/rolldpos/epochctx.go, vendor/github.com/iotexproject/iotex-election/carrier/carrier.go
1. iotex-election will crash because of a pagination bug, upgrade to latest version which fixed that bug
2. get candidates by the first block height of an epoch
=> iotex-election fix pagination bug, and fix candidates bug

e2etest/local_transfer_test.go
Original TestLocalTransfer uses 1 second as the block produce interval, which is too aggressive for CircleCI server.
So this fix is to increase the block produce interval to  2 seconds.
=> IOTEX 336 Fix TestLocalTransfer flaky  panic on CircleCI build

action/protocol/poll/protocol.go, api/api.go
1. When reading active BPs, we should always read BPs on Epoch start height.
2. TPS in GetChainMeta is negative because time duration is negative.
=> Fix two bugs in API

cli/ioctl/cmd/account/account.go, cli/ioctl/cmd/account/accountdelete.go, cli/ioctl/cmd/account/accountimport.go, cli/ioctl/cmd/account/accountlist.go, cli/ioctl/cmd/account/accountname.go, cli/ioctl/cmd/account/accountnonce.go, cli/ioctl/cmd/account/accountupdate.go, cli/ioctl/cmd/config/config.go, cli/ioctl/cmd/node/nodereward.go
Tested on local.
-> ioctl account list
Account:
name: frank, address:io18jaldgzc8wlyfnzamgas62yu3kg5nw527czg37
name: i, address:io1vrl48nsdm8jaujccd9cx4ve23cskr0ys6urx92
name: node, address:io1u90mvrdx7tz02fh92vjd6y73et7j4d4srcl4ek
name: pro, address:io1juvx5g063eu4ts832nukp4vgcwk2gnc5cu9ayd
name: test123, address:io1ns7y0pxmklk8ceattty6n7makpw76u770u5avy
name: a, address:io1znka733xefxjjw2wqddegplwtefun0mfdmz7dw
name: boss, address:io1ed52svvdun2qv8sf2m0xnynuxfaulv6jlww7ur
-> ioctl account name io1znka733xefxjjw2wqddegplwtefun0mfdmz7dw hihi
An account #a:io1znka733xefxjjw2wqddegplwtefun0mfdmz7dw already exists.
-> ioctl account name io1m8rge0h4xvmfzkc4yup766slcvn5cwymqeenpe hihi
Succeed to name io1m8rge0h4xvmfzkc4yup766slcvn5cwymqeenpe "hihi".
-> ioctl account list
Account:
name: boss, …
=>  Add name management for ioctl

blockchain/blockchain.go, consensus/scheme/rolldpos/rolldposctx.go
1. When mint block, pass block creation timestamp as the raCtx blocktimestamp
2. On consensus reached, if commit fails, log error and early return
=> fix two bugs in consensus

action/protocol/poll/protocol.go, action/protocol/poll/protocol_test.go, api/api_test.go, server/itx/server.go
1. Port hotfix of r0.5 on master
2. Reenable API tests on reading active BPs and committee BPs
=>  IOTEX-349 Reenable unit tests of ReadActiveBlockProducersByHeight and ReadCommitteeBlockProducersByHeight

action/protocol/context.go, action/protocol/execution/evm/evm.go, action/protocol/execution/protocol_test.go, api/api_test.go, blockchain/block/block.go, blockchain/block/block_test.go, blockchain/block/header.go, blockchain/block/runnable.go, blockchain/block/testing.go, blockchain/blockchain.go, blockchain/blockchain_test.go, blockchain/blockvalidator_test.go, blocksync/blocksync_test.go, blocksync/buffer_test.go, consensus/consensus.go, consensus/scheme/rolldpos/rolldpos.go, consensus/scheme/rolldpos/rolldposctx.go, consensus/scheme/rolldpos/subchain_test.go, e2etest/local_test.go, e2etest/util.go, explorer/explorer_test.go, indexservice/indexer_test.go, server/itx/server.go, test/mock/mock_blockchain/mock_blockchain.go, testutil/timestamp.go
tested it with make test && make minicluster
=> use time.Time as block time

cli/ioctl/cmd/account/account.go, cli/ioctl/cmd/account/account_test.go, cli/ioctl/cmd/action/action.go, pkg/keypair/keypair.go, pkg/keypair/keypair_test.go, pkg/keypair/secp256k1.go, pkg/keypair/secp256k1_test.go
Add KsAccountToPrivateKey() so we can stick to action.Sign() and avoid assigning pubkey and signature bytes to iotextypes.Action{} struct
=> Use action.Sign() in ioctl sendAction()

consensus/scheme/rolldpos/rolldposctx.go
If the proposal is from other users, we already check the proposer in handleconsensusmessage. If the proposal is from the itself, no checking is needed.
=> delete redundant and wrong proposer checking

action/protocol/rewarding/admin.go, action/protocol/rewarding/protocol_test.go, action/protocol/rewarding/reward.go, action/protocol/rewarding/reward_test.go
=> Handle empty reward address and fix available balance acccounting

cli/ioctl/cmd/action/actionhash.go
Tested on local
```
→  ioctl action hash 690fb07fbb5ba3b762a7a16edea35ff1c3b02b43a6331aef88c4daa1bc933ad4
version: 1  nonce: 7  gasLimit: 122222  gasPrice: 2000000000000 Rau
senderAddress: io1znka733xefxjjw2wqddegplwtefun0mfdmz7dw (whale)
transfer: <
recipient: io18jaldgzc8wlyfnzamgas62yu3kg5nw527czg37 (nani)
amount: 123000000000000000000 Rau
payload:
>
senderPubKey: 04d0fade363080b9061844ed6b1009f35595515b31295e37e870106d3201a638856db2c3f870dbbcafc559af54574f3487dbea0d318588608d7aca8e77e4ce5ade
signature: 2e10f265fdc5944fab11afaebd258292afe8f9076157fbaca6bfdd3ece9047483fb3aa10ce187fe55d2d9c591e5eda430833b744f825a6ae34c9b34461d3940f01
#This action has been written on blockchain
returnValue:
status: 1 (Success)
actHash: 690fb07fbb5ba3b762a7a16edea35ff1c3b02b43a6331aef88c4daa1bc933ad4 …
```
=> Improve hash cmd for ioctl

Gopkg.lock, Gopkg.toml, blocksync/buffer.go, consensus/scheme/rolldpos/rolldpos.go, consensus/scheme/rolldpos/rolldposctx.go, tools/minicluster/minicluster.go, vendor/github.com/iotexproject/iotex-election/carrier/carrier.go, vendor/github.com/iotexproject/iotex-election/committee/committee.go, vendor/github.com/iotexproject/iotex-election/test/mock/mock_committee/mock_committee.go
1. Mute commit error if the cause is tip height error
2. Mute minicluster wrong height alert
3. Mute consensus error when height is 0
4. Update election logging information
=> mute error messages

config/config.go, consensus/consensusfsm/fsm.go, consensus/consensusfsm/fsm_test.go, consensus/scheme/rolldpos/rolldpos_test.go, consensus/scheme/rolldpos/rolldposctx.go, consensus/scheme/rolldpos/roundctx.go, consensus/scheme/rolldpos/roundctx_test.go, tools/minicluster/minicluster.go
In a corner case that only 2/3 or less nodes enter the commit step, the chain will get stuck. To fix the issue, the nodes in commit step should rebroadcast their commit endorsements every few seconds. Meanwhile, for the other nodes, they should process those commit endorsements from the same height but previous round.
This PR changes three things:
1. Introduce a new field COMMIT_TTL to the config for FSM, and rebroadcast commit endorsement every COMMIT_TTL
2. Update IsStaleEvent logic to accept COMMIT endorsement from previous round
3. Fix a consensus event creation time of incoming events to clock.Now()
=> rebroadcast precommit endorsement on timeout

Gopkg.lock, Gopkg.toml, chainservice/chainservice.go, config/config.go, vendor/github.com/iotexproject/iotex-election/committee/committee.go, vendor/github.com/iotexproject/iotex-election/db/kvstore.go, vendor/github.com/iotexproject/iotex-election/test/mock/mock_committee/mock_committee.go, vendor/github.com/iotexproject/iotex-election/types/candidate.go, vendor/github.com/iotexproject/iotex-election/types/result.go
Upgrade iotex-election package to v0.1.6:
1. Faster sync
2. Fix fork bug by delaying 12 blocks
3. Fix candidate filter issue
Default config is changed, but no change to iotex-cluster is needed.
=> upgrade iotex-election package to v0.1.6

blockchain/blockdao.go
Hotfix for rc8. Body cache was used for footer.
=> fix caching bug

config/config.go, consensus/consensus.go, consensus/consensusfsm/context.go, consensus/consensusfsm/fsm.go, consensus/consensusfsm/fsm_test.go, consensus/consensusfsm/mock_context_test.go, consensus/scheme/noop.go, consensus/scheme/rolldpos/rolldpos.go, consensus/scheme/rolldpos/rolldpos_test.go, consensus/scheme/rolldpos/rolldposctx.go, consensus/scheme/scheme.go, consensus/scheme/standalone.go, pkg/ha/ha.go, server/itx/server.go, test/mock/mock_consensus/mock_consensus.go
Per feedback from the community, it seems to be useful to provide HA feature for delegates. In HA, 1 server will be active and the others will standby. Once the active node is down, another will be set to active by leader election (in Part 2). The goal is 99% availability. In terms of consensus node, the two modes behavior are as follows:
- Active: handle block sync + consensus messages
- Standby: handle block sync
> What we need to do?
Add the active flag. When the flag is set to false, wait consensus fsm go back to init state, and stand by there and process no events.
> How about state sharing among the servers?
Active server will have the consensus state for the next block that, but the stand-by servers won't. It's almost okay because the active server will decommission only after it …
=> Consensus node high availability (Part 1): allow consensus node stand-by

cli/ioctl/cmd/account/accountethaddr.go, cli/ioctl/cmd/alias/alias.go
tested
```
→  ioctl account ethaddr a
io1vrl48nsdm8jaujccd9cx4ve23cskr0ys6urx92 - 0x60Ff53cE0Dd9E5de4b1869706aB32a8E2161Bc90
→  ioctl account ethaddr 0x60Ff53cE0Dd9E5de4b1869706aB32a8E2161Bc90
io1vrl48nsdm8jaujccd9cx4ve23cskr0ys6urx92 - 0x60Ff53cE0Dd9E5de4b1869706aB32a8E2161Bc90
→  ioctl account ethaddr io1vrl48nsdm8jaujccd9cx4ve23cskr0ys6urx92
io1vrl48nsdm8jaujccd9cx4ve23cskr0ys6urx92 - 0x60Ff53cE0Dd9E5de4b1869706aB32a8E2161Bc90
→  ioctl account ethaddr 60Ff53cE0Dd9E5de4b1869706aB32a8E2161Bc90
io1vrl48nsdm8jaujccd9cx4ve23cskr0ys6urx92 - 0x60Ff53cE0Dd9E5de4b1869706aB32a8E2161Bc90
```
=> Update account ethaddr cmd

.circleci/config.yml
the crypto/lib has been removed from iotex-core.
new config.yml not tested
=> Fix ioctl dirty git status in nightly build and remove useless export

consensus/scheme/rolldpos/rolldposctx.go
=> IOTEX-1025 update consensus messages

cli/ioctl/cmd/node/nodereward.go
query reward pool when no address/alias input
=> Update node reward cmd

cli/ioctl/cmd/action/actionhash.go
#1040
timestamp and blkhash can be printed now but not right.
```
version: 1  nonce: 1499  gasLimit: 10000  gasPrice: 1000000000000 Rau
senderAddress: io1znka733xefxjjw2wqddegplwtefun0mfdmz7dw (whale)
transfer: <
recipient: io1mflp9m6hcgm2qcghchsdqj3z3eccrnekx9p0ms (35)
amount: 21000000000000000000 Rau
>
senderPubKey: 04d0fade363080b9061844ed6b1009f35595515b31295e37e870106d3201a638856db2c3f870dbbcafc559af54574f3487dbea0d318588608d7aca8e77e4ce5ade
signature: 9cf2dbc00b181ea0dba35bbbe8eb41f73948f496a9f529bd684ef19aebcdd9311f3f4a72563d6b4ec4752a6e7cfcd22ac97ccfa1b8122d9899b3788a179d64a001
timeStamp: timestamp: nil Timestamp
actHash: 1170ae2da4ceefc03200eb8b93cc42ee62f0ad5407e3c782b99f8ba36117a330
blkHash: 0000000000000000000000000000000000000000000000000000000000000000
```
=> Print time stamp in action hash cmd for ioctl

p2p/agent_test.go
work on #1021 
I tested many times,there's only one failed,I think maybe ci system resources are low caused this,
so I add more time
=> TestBroadcast is flaky #1021

cli/ioctl/cmd/account/account.go, cli/ioctl/cmd/account/accountimport.go, go.mod
work on #1191 
1、
ioctl account import keystore xx UTC--2019-05-23T09-36-39.493806681Z--3ac6ad0777e76ae6974ff89bf3a719adac600077
#xx: Enter your password of keystore, which will not be exposed on the screen.
#xx: Set password
#xx: Enter password again
New account #xx is created. Keep your password, or your will lose your private key.
2、
ioctl account import keystore xx UTC--2019-05-23T09-36-39.493806681Z--3ac6ad0777e76ae6974ff89bf3a719adac600077
#xx: Enter your password of keystore, which will not be exposed on the screen.
Error: could not decrypt key with given passphrase
3、
ioctl account import keystore xxx ./nofile
#xxx: Enter your password of keystore, which will not be exposed on the screen.
Error: keystore file "./nofile" read error
4、
ioctl account import key aa
#aa: Enter your …
=> Ioctl should allow import/export from to keystore file #1191

cli/ioctl/cmd/action/actionhash.go, cli/ioctl/util/util.go
work on #1215 
1、ioctl account balance bb
io1mflp9m6hcgm2qcghchsdqj3z3eccrnekx9p0ms: 0 IOTX
2、ioctl action transfer bb 1.111111111 -s aa
Enter password #aa:
version: 1  nonce: 4  gasLimit: 10000  gasPrice: 1000000000000 Rau
senderAddress: io1vdtfpzkwpyngzvx7u2mauepnzja7kd5rryp0sg (aa)
transfer: <
recipient: io1mflp9m6hcgm2qcghchsdqj3z3eccrnekx9p0ms (bb)
**amount: 1.111111111 IOTX**
>
senderPubKey: 04ea8046cf8dc5bc9cda5f2e83e5d2d61932ad7e0e402b4f4cb65b58e9618891f54cba5cfcda873351ad9da1f5a819f54bba9e8343f2edd1ad34dcf7f35de552f3
signature: ba9822f15390ac48c63bc0efb9c2decfcc765f347ca3a92ed6892c2291f14f674d8b0f2e4a410ea88211e6b164d6d1cfcbf3a4d47a23f48786d3a678e730f1d801
Please confirm your action.
Type 'YES' to continue, quit for anything else.
yes
Action has been sent to blockchain.
Wait for …
=> ioctl action transfer uses IOTX for amount rather than Rau #1215

gasstation/gasstattion.go, gasstation/gasstattion_test.go
Working on #1205
Write a function to determine whether one action is system action or user action and check skip the block which only have system action.
I separate the TestSuggestGasPrice function in gasstation_test.go file to two function, one for normal block with one transfer user action and a system action, other function is testing for the blocks which only consist of system action. Then test their price result to see whether the logic is worked.
=> Skip system actions when estimating gas price

api/api.go, api/api_test.go, chainservice/chainservice.go
work on #1030 
There's 6 apis need action index
1、grpcurl -v -plaintext -d '{"byIndex": {"start": 10, "count": 2}}' 127.0.0.1:14014 iotexapi.APIService.GetActions
2、grpcurl -v -plaintext -d '{"byHash": {"actionHash": "61397a469bff69296c9dad88850bee167a13cd3a982b406a79321026b9bf80ab", "checkPending": false}}' 127.0.0.1:14014 iotexapi.APIService.GetActions
3、grpcurl -v -plaintext -d '{"byAddr": {"address": "io1nyjs526mnqcsx4twa7nptkg08eclsw5c2dywp4", "start": 0, "count": 1}}' 127.0.0.1:14014 iotexapi.APIService.GetActions
4、grpcurl -v -plaintext -d '{"unconfirmedByAddr": {"address": "io1nyjs526mnqcsx4twa7nptkg08eclsw5c2dywp4", "start": 1, "count": 1}}' 127.0.0.1:14014 iotexapi.APIService.GetActions
5、grpcurl -v -plaintext -d '{"actionHash": …
=> Differentiate APIs that need and don't need action index #1030

api/api.go
work on #1265 
There's only 3 apis depend on gateway plugin：
1、grpcurl -v -plaintext -d '{"byHash": {"actionHash": "61397a469bff69296c9dad88850bee167a13cd3a982b406a79321026b9bf80ab", "checkPending": false}}' 127.0.0.1:14014 iotexapi.APIService.GetActions
2、grpcurl -v -plaintext -d '{"byAddr": {"address": "io1nyjs526mnqcsx4twa7nptkg08eclsw5c2dywp4", "start": 1, "count": 1}}' 127.0.0.1:14014 iotexapi.APIService.GetActions
3、grpcurl -v -plaintext -d '{"actionHash": "61397a469bff69296c9dad88850bee167a13cd3a982b406a79321026b9bf80ab"}' 127.0.0.1:14014 iotexapi.APIService.GetReceiptByAction
=> check all api again to find out these depend on gateway plugin #1265

tools/util/injectorutil.go
The balance doesn't match because some actions are falsely checked as pending, so the balance changes are not counted into expectations.  
So the fix is to get action-receipt by action hash( GetReceiptByActionHash) before getting action by action hash(GetActionByActionHash), not vice versa that caused the issue.  That is because getting action successfully by action hash doesn't guarantee to get action-receipt successfully immediately.
=> #1271 Fix minicluster balance check mismatch

cli/ioctl/cmd/action/action.go, cli/ioctl/cmd/action/actionclaim.go, cli/ioctl/cmd/action/actiondeploy.go, cli/ioctl/cmd/action/actiondeposit.go, cli/ioctl/cmd/action/actioninvoke.go, cli/ioctl/cmd/action/actionread.go, cli/ioctl/cmd/action/actiontransfer.go, cli/ioctl/cmd/action/xrc20.go, cli/ioctl/cmd/action/xrc20allowance.go, cli/ioctl/cmd/action/xrc20approve.go, cli/ioctl/cmd/action/xrc20balanceof.go, cli/ioctl/cmd/action/xrc20const.go, cli/ioctl/cmd/action/xrc20totalsupply.go, cli/ioctl/cmd/action/xrc20transfer.go, cli/ioctl/cmd/action/xrc20transferfrom.go, cli/ioctl/cmd/alias/alias.go, cli/ioctl/flag/flag.go
1. Introduce Flag to simplify the "set" and "read"
2. Refactor action commands, remove unnecessary returns
3. Add AMOUNT_IN_IOTEX to deploy command for the case that the constructor is payable
4. Add default gas price, gas limit, and nonce
5. Support reading contract as alias
=> refactor ioctl action and xrc20 commands

cli/ioctl/cmd/action/action.go, cli/ioctl/cmd/action/xrc20.go, cli/ioctl/cmd/action/xrc20approve.go, cli/ioctl/cmd/action/xrc20transfer.go, cli/ioctl/cmd/action/xrc20transferfrom.go
Previously in the xrc20 command line, our amount do not including the decimal attribute. So now I read the decimal information by using contract information and transfer the amount with that value.
=> Small fix on xrc20 decimal issue

cli/ioctl/cmd/account/account.go, cli/ioctl/cmd/account/accountexport.go, cli/ioctl/cmd/account/accountexportpublic.go, cli/ioctl/cmd/account/accountimport.go, cli/ioctl/cmd/account/accountupdate.go, cli/ioctl/cmd/account/sign.go, cli/ioctl/cmd/action/action.go, cli/ioctl/util/util.go
During user should typing the password, if there is a system interrupt like CTRL+C will cause terminal remain in hidden input status. So I create a listener to reset the terminal status when system interrupt approach.
=> Fix one bug after system interrupt during typing password

api/api.go, api/apitestclient.go, api/blocklistener.go, api/listener.go, api/logfilter.go, api/logfilter_test.go, go.mod, go.sum, test/mock/mock_apiserviceclient/mock_apiserviceclient.go, test/mock/mock_blockchain/mock_blockchain.go
add a Responder interface to define the actual behavior when a new block arrives, this turns the Listener.Start() into common code. 
the Listener on chain just keep adding Responder -- each implements functionality for different streaming APIs
the original blockListener becomes a Responder, so is log filter added in this PR
=> Add StreamFilterLogs() to enable querying logs by topics

cli/ioctl/cmd/action/action.go, cli/ioctl/cmd/action/actionsendraw.go
work on #1319
use:
ioctl action sendraw 0a590801101518e0a712220d3130303030303030303030303052400a13313534353530303030303030303030303030301229696f3165796e39746336743738327a78347a677933686774333268707a36743876377067663532347a124104ea8046cf8dc5bc9cda5f2e83e5d2d61932ad7e0e402b4f4cb65b58e9618891f54cba5cfcda873351ad9da1f5a819f54bba9e8343f2edd1ad34dcf7f35de552f31a41eb9037e0d5c71c48acf114b2e3d68fb5313873e73e02ce30eff8ace0e6f879ca36c6ed806bacc34aeef40aab4a8629e4acc7784f94fa4eda3bbed375abf183d400
=> Make ioctl be able to send raw transaction bytes 1319

ioctl/cmd/root.go, ioctl/cmd/version/version.go, ioctl/output/format.go, ioctl/output/json.go
I take the version command as an example of format output refactoring. #935 
In new versionCmd, by default, result is printed through stdout and error is printed throught stderr.
When using the flag output-format(eg. `-o json`), output(contains error) will be printed through stdout.
Tested on windows and centos
```
// success case
-> ioctl version -o json                                      
{
"messageType": 0,
"message": {
"object": "Client",
"versionInfo": {
"packageVersion": "v0.8.0-13-gfa27c17",
"packageCommitID": "fa27c17a0c286d6df5f3c35ad9ae2c2b38e450a7",
"gitStatus": "clean",
"goVersion": "go version go1.12.6 linux/amd64",
"buildTime": "2019-07-08-CST/13:12:02"
}
}
}
{
"messageType": 0,
"message": {
"object": "api.iotex.one:443",
"versionInfo": {
"packageVersion": "v0.6.2", …
```
=> Add format output flag for versionCmd

go.mod, go.sum, ioctl/cmd/account/account.go, ioctl/cmd/account/accountbalance.go, ioctl/cmd/account/accountcreate.go, ioctl/cmd/account/accountcreateadd.go, ioctl/cmd/account/accountdelete.go, ioctl/cmd/account/accountethaddr.go, ioctl/cmd/account/accountexport.go, ioctl/cmd/account/accountexportpublic.go, ioctl/cmd/account/accountimport.go, ioctl/cmd/account/accountlist.go, ioctl/cmd/account/accountnonce.go, ioctl/cmd/account/accountsign.go, ioctl/cmd/account/accountupdate.go, ioctl/cmd/alias/aliasremove.go, ioctl/cmd/alias/aliasset.go, ioctl/output/format.go
This is a rough implementation of format output for Account Cmds. I don't match all the errors with the error code. There are still some undefined errors and we may need to integrate them after all clusters of Cmds are changed into format output.
There is also a concern about safety when using struct to wrap private key or signed message and marshal them into json format to print. I don't know whether some of the messages will be left in memory.
=>  Format ouput for Account Cmds in ioctl

ioctl/cmd/account/account.go, ioctl/cmd/account/accountverify.go
Tested on centos #1372 
```
->  ioctl account verify       
Enter private key:
Address:        io1jd7z68w3v350hk45kwhuqac9m8kdmkndsk6w7m
Public Key:     048787f3fb838b2eec8c43d51a6f2343b750c7c5246245b6d7d32c4c5911266bff5d2ad6a9f9045a2aadf3bc763e131825aa557f87d9cc8093b7b07fb47be4eefa
->  ioctl account verify -o json                        
Enter private key:
{
"messageType": 0,
"message": {
"address": "io1jd7z68w3v350hk45kwhuqac9m8kdmkndsk6w7m",
"publicKey": "048787f3fb838b2eec8c43d51a6f2343b750c7c5246245b6d7d32c4c5911266bff5d2ad6a9f9045a2aadf3bc763e131825aa557f87d9cc8093b7b07fb47be4eefa"
}
}
```
=>  Add account verify cmd for ioctl

go.sum, ioctl/cmd/account/accountbalance.go, ioctl/cmd/account/accountcreateadd.go, ioctl/cmd/account/accountdelete.go, ioctl/cmd/account/accountexport.go, ioctl/cmd/account/accountexportpublic.go, ioctl/cmd/account/accountnonce.go, ioctl/cmd/account/accountupdate.go, ioctl/cmd/action/action.go, ioctl/cmd/action/actionclaim.go, ioctl/cmd/action/actiondeploy.go, ioctl/cmd/action/actiondeposit.go, ioctl/cmd/action/actionhash.go, ioctl/cmd/action/actioninvoke.go, ioctl/cmd/action/actionread.go, ioctl/cmd/action/actionsendraw.go, ioctl/cmd/action/actiontransfer.go, ioctl/cmd/action/xrc20.go, ioctl/cmd/action/xrc20allowance.go, ioctl/cmd/action/xrc20approve.go, ioctl/cmd/action/xrc20balanceof.go, ioctl/cmd/action/xrc20totalsupply.go, ioctl/cmd/action/xrc20transfer.go, ioctl/cmd/action/xrc20transferfrom.go, ioctl/cmd/alias/alias.go, ioctl/cmd/config/configsetget.go, ioctl/cmd/version/version.go, ioctl/output/format.go, ioctl/util/util.go
Refactoring action&xrc20 cmds for format output and leaving many undefined errors, which I will resolve when finishing refactoring all clusters of ioctl cmds.
I don't quite understand the output of xrc20's read command so I followed the origin code to design the amountMessage struct.
#935
=> Format output for action cmds and xrc20 cmds

action/protocol/execution/evm/contract_test.go, action/protocol/execution/evm/evmstatedbadapter_test.go, action/protocol/execution/evm/testdata_test.go, api/api.go, go.mod, go.sum, state/factory/statedb.go
This would enable solidity 0.5.1
Please focus on 2nd commit, which adds the 2 new interfaces. It also refactors the implementation of SetCode/State, GetState
The 1st commit is just to make the test code more readable by adding test vector, and also improve test coverage by testing both Trie and Trieless DB
=> improve evmadaptor and contract test coverage

blockchain/indexbuilder.go, chainservice/chainservice.go, config/config.go
work on #1386 
example:
server -config-path=/etc/iotex/config_testnet.yaml \
-genesis-path=/etc/iotex/genesis_testnet.yaml \
-plugin=gateway -reindex=true
or
server -config-path=/etc/iotex/config_testnet.yaml \
-genesis-path=/etc/iotex/genesis_testnet.yaml \
-plugin=gateway -reindex
The index of actions will reindex from height 1 and index 0 with '-reindex'
=> Reduplicative ations with same hash shows in action list 1386

ioctl/cmd/account/account.go, ioctl/cmd/account/accountgetvotes.go
work on #1360 
Add the cli to integrate with the api.
example:
ioctl account getVotes 726f626f7462703030303136 8164200 0 10
**buckets:<voter:"13f8ebd57488019a9652120a5b2be7554aa31fba" votes:"136000000000000000000" weightedVotes:"3010304432372308021120000" remainingDuration:"168h0m0s" >**
=> Support check a single address' votes 1360

ioctl/cmd/account/accountbalance.go, ioctl/cmd/account/accountdelete.go, ioctl/cmd/account/accountexport.go, ioctl/cmd/account/accountnonce.go, ioctl/cmd/account/accountupdate.go, ioctl/cmd/action/xrc20balanceof.go, ioctl/cmd/alias/aliasset.go, ioctl/cmd/config/configsetget.go
working on #1285 
Things have been modified:
1.Some command in account.go it shows could receive zero argument in our documentation and actually they will run into index out of range error with zero argument. So I just use default account in config to be the default argument in these account commands.
2. modified alias set output message.
3.modify get output of config default account to be more friendly.
4.modified xrc20 balanceOf output when they have no balance in current contract.
=> Add more friendly message to ioctl.

ioctl/cmd/action/actiondeploy.go
The args length should be 0 or 1.
=> deploy command args length error

blockchain/blockchain.go, blockchain/blockdao.go, blockchain/blockdao_test.go, blocksync/buffer.go, config/config.go
work on #1395
Block header,body ,footer and receipt map to different dbs according to block height,
other datas still store in default db：chain.db.
The default split size is 640M，it don't need to split db when it's 0.
The split height config means it will split to diff db since that height.
The new db's name like this:
chain-00000001.db
chain-00000002.db
=> Support partitioning db by block height 1395

api/api.go, api/api_test.go, api/logfilter.go
works on #1447 
The problem of this issue is not because of filtering logic, but that the receipt field in block struct was empty. 
So I changed getLogsInBlock() to get a receipt by height and put it into the block struct.
But in the test file, the length of logs is still 0 because the block's tipheight is just around 4.
=> changed getLogsInBlock

consensus/consensusfsm/context.go, consensus/consensusfsm/fsm.go, consensus/consensusfsm/fsm_test.go, consensus/consensusfsm/mock_context_test.go, consensus/scheme/rolldpos/rolldpos.go, consensus/scheme/rolldpos/rolldposctx.go, consensus/scheme/rolldpos/roundctx.go, go.sum
Three issues in previous implementation:
1. If overtime, the initial ttl was calculated wrongly (should be +=, not -=)
2. m.produceConsensusEvent(ePrepare, ttl) won't kick the node in pre-commit status back to sPrepare status
3. interface{} with type specified won't be nil
Test with minicluster, and nightly-cluster-0
=> Fix precommit status

api/api.go, api/api_test.go, blockchain/block/body.go, blockchain/block/body_test.go, blockchain/block/utils.go, blockchain/blockchain.go, blockchain/blockchain_test.go, blockchain/blockdao.go, blockchain/blockdao_test.go, test/mock/mock_blockchain/mock_blockchain.go
Related to issue #1441.
From my understanding, the number of all transactions are even with the block height.
=> Make GetBlockMetas API only read block header. #1441

consensus/consensusfsm/fsm.go, consensus/consensusfsm/fsm_test.go, consensus/scheme/rolldpos/rolldpos_test.go, consensus/scheme/rolldpos/rolldposctx.go, consensus/scheme/rolldpos/roundcalculator.go, consensus/scheme/rolldpos/roundcalculator_test.go
Previous' test was focusing on delegate nodes. As a result, a lot of errors were printed for non-delegate nodes. This PR tries to reduce those kind of errors.
1. return the same round with no error if "now" is before the start time of current round
2. for non-delegate, skip to next round
Test plan:
1. make test && make minicluster
2. start a non-delegate node
=> Print less errors for non-delegate nodes

blockchain/blockdao.go, blockchain/blockdao_test.go
1. store tip block hash into a key "ts"
2. this PR is to prep for the upcoming change of separating index db. With this change, we can remove the namesapce "h2h" in current chain.db
=> store tip block hash

consensus/scheme/rolldpos/rolldpos.go, consensus/scheme/rolldpos/rolldpos_test.go, consensus/scheme/rolldpos/roundcalculator.go
The time of last block was calculated based on the commit time saved in block footer. As the commit time may not be consistent from delegate to delegate, it causes the problem that some nodes with a different commit time reject blocks from block sync.
Fixes:
1. Instead of checking the block producer is the right proposer according to the block time, check whether the producer is a delegate instead. With this fix, even the block commit time is different, it will still be accepted as long as the producer is a consensus delegate and there are enough endorsements.
2. Use the block timestamp as the last block time instead of commit time, to make sure that the consensus delegates get the same round number. This will cause problem that if it took more than one round on a height, the delegate who …
=> change last block time and footer validation rule

consensus/scheme/rolldpos/rolldpos.go, consensus/scheme/rolldpos/rolldpos_test.go, consensus/scheme/rolldpos/rolldposctx.go, consensus/scheme/rolldpos/rolldposctx_test.go, consensus/scheme/rolldpos/roundcalculator.go, consensus/scheme/rolldpos/roundcalculator_test.go
1. as title, so delegates can switch to using block header time in sync
2. after mainnet pass bering height, this change can be reverted (contingent on verifying full-node can sync all blocks by reverting it)
=> use bering height to synchronize last block time switch

action/protocol/execution/protocol_test.go, action/protocol/poll/staking_committee.go, api/api.go, api/api_test.go, blockchain/blockchain.go, blockchain/blockchain_test.go, blockchain/blockdao.go, blockchain/blockdao_test.go, blockchain/indexbuilder.go, blockchain/indexbuilder_test.go, chainservice/chainservice.go, config/config.go, db/counting_index.go, db/counting_index_test.go, db/db.go, db/db_bolt.go, pkg/util/byteutil/byteutil.go, test/mock/mock_blockchain/mock_blockchain.go
1. improve address <--> action indexing using counting index
2. this change allows to get rid of the time-consuming sort() when performing getActionsByIndex() and getActionsByAddress()
3. removed redundant indexing namespace "a2r"
4. improved test coverage for blockdao_test.go, and added indexbuilder_test.go
=>  improve address action index

go.mod, go.sum
1. Fix two bugs in iotex-election
2. Further improve the db performance, reduce db size from 2.7G to 74M
=> upgrade to iotex-election v0.2.2

action/protocol/poll/staking_committee.go, api/api.go, chainservice/chainservice.go, tools/actioninjector.v2/internal/client/client_test.go
As stated below, this is a confusing API. Two ways to query votes by height:
1. Query Ethereum contract
2. Query election committee
Providing an API for users to query iotex-core by ethereum height is not the right way.
=> Delete get votes api

action/const.go, action/protocol/execution/evm/evm.go, action/protocol/poll/nativestaking.go, action/protocol/poll/nativestaking_test.go, action/protocol/poll/protocol.go, action/protocol/poll/staking_committee.go, blockchain/blockchain.go, blockchain/genesis/genesis.go, server/itx/server.go
Allow config nativestakingcontractcode in the genesis so that we could start a chain with the native staking contract from scratch.
Verified the start and restart in the cluster and worked fine
=> Make native staking contract be loadable from genesis

ioctl/cmd/node/nodedelegate.go
It's a mistake without test. Sorry about that.
=> fix nextDelegates() bug of ioctl

consensus/consensusfsm/fsm.go
works on #1543 
Old calibrate event should be ignored, So try not to return error and change it to the debug logging
=> Old calibrate event not to return error 

api/api.go
When I invoke an execution from ioctl without setting gas limit, ioctl will call ExecuteContractRead to estimate gas consume. If the execution gets failure status, the error message user gets will be `Error: failed to fix Execution gaslimit: receipt status failed` that may be confusing for a non-developer.
Therefore, I'd like to change the error message that node returns to ioctl into `execution simulation gets failure status`. And user may get `Error: failed to fix Execution gaslimit: execution simulation gets failure status`
=> rewrite error message of execution simulation

consensus/consensusfsm/mock_context_test.go, misc/scripts/mockgen.sh, test/mock/mock_actioniterator/mock_actioniterator.go, test/mock/mock_actpool/mock_actpool.go, test/mock/mock_apiserviceclient/mock_apiserviceclient.go, test/mock/mock_blockchain/mock_blockchain.go, test/mock/mock_blocksync/mock_blocksync.go, test/mock/mock_chainmanager/mock_chainmanager.go, test/mock/mock_consensus/mock_consensus.go, test/mock/mock_dispatcher/mock_dispatcher.go, test/mock/mock_factory/mock_factory.go, test/mock/mock_factory/mock_workingset.go, test/mock/mock_lifecycle/mock_lifecycle.go, test/mock/mock_trie/mock_trie.go
removing existing mocks first cause mockgen failed on blocksync mock building.
=> mockgen script should not remove existing mocks

blockchain/blockchain.go, blockchain/blockdao/blockdao.go, blockchain/blockdao/blockdao_test.go, blockindex/indexer.go, blockindex/indexer_test.go
Blockdao is using a complicated interface defined in blockindex now. The PR tries to simplify the interface definition, and define it in blockdao.
Test plan: make test && make minicluster
=> define blockindexer interface in blockdao

blockchain/blockchain.go, e2etest/local_test.go, state/factory/factory.go, state/factory/statedb.go, state/factory/util.go, test/mock/mock_factory/mock_factory.go
it could happen that bc.tipHeight > 0 while state factory DB file has been deleted
sf.Initialize() should be called based upon sf.Height() == 0, but not bc.tipHeight == 0
Test plan:
make test && make minicluster
=> correctly initialize state factory

action/protocol/context.go, action/protocol/context_test.go, action/protocol/execution/evm/contract.go, action/protocol/execution/evm/evm.go, action/protocol/execution/evm/evmstatedbadapter.go, blockchain/blockchain.go, config/config.go, db/batch.go, db/batch_test.go, db/db.go, db/db_bolt.go, db/kvstore4trie.go, db/kvstore4trie_test.go, db/range_index.go, db/range_index_test.go, db/trie/branchroottrie.go, db/trie/kvstore.go, db/trie/trie.go, state/factory/factory.go, state/factory/factory_test.go, state/factory/statedb.go, state/factory/statetx.go, state/factory/workingset.go, test/mock/mock_factory/mock_workingset.go
1. for state, state is stored using a RangeIndex so that it can be retrieved later using specific height
2. for contract, "height-node" is marked for deletion and stored into a separate namespace, these nodes will be pruned later depending on height
=> Add save history as a factory option

action/protocol/poll/protocol.go, api/api_test.go, blockchain/block/block.go, blockchain/block/block_test.go, blockchain/block/builder.go, blockchain/block/builder_test.go, blockchain/block/runnable.go, blockchain/blockchain.go, blocksync/blocksync_test.go, consensus/scheme/rolldpos/rolldpos_test.go
This PR is based on #1661, please jump to the last commit to review.
RunnableActions doesn't use height, timestamp, and public key in any way. Moreover, public key could be set when signing a block with a private key.
=> Simplify run actions

action/protocol/poll/staking_committee.go, state/factory/factory.go, state/factory/statedb.go
Two bugs:
1. Fetch candidates from state db with height = 0
solution: return empty list
2. Create native staking contract in CreateGenesisStates
solution: if native staking contract address is not empty or code is empty, skip contract creation
=> fix candidates related bugs

action/protocol/execution/protocol_test.go, actpool/actpool_test.go, api/api_test.go, blockchain/blockchain.go, blockchain/blockchain_test.go, blockchain/blockvalidator_test.go, consensus/scheme/rolldpos/rolldpos_test.go, e2etest/bigint_test.go, e2etest/local_test.go, e2etest/local_transfer_test.go, state/factory/factory.go, state/factory/factory_test.go, state/factory/statedb.go, state/factory/statetx.go, state/factory/util.go, state/factory/workingset.go, test/mock/mock_factory/mock_workingset.go
1. Replace UpdateBlockLevelInfo with Finalize
2. Unify the behavior of RunAction and RunActions
3. Change version to the height going to build
4. Verify the block height stored in ctx
5. Delete all test account creation related code in unit test, and adding those test accounts into Genesis.InitBalanceMap (This change makes the PR very big. It has to be done, because of point 4.) (addressed https://github.com/iotexproject/iotex-core/issues/1668)
Test Plan:
make mockgen && make test && make minicluster
=> unify workingset api

db/batch.go, db/batch_test.go, state/factory/workingset.go
as title, should exclude in all buckets, not only "ContractKVNameSpace"
=> exclude trie deletion in all buckets for history option

action/protocol/account/protocol.go, action/protocol/account/protocol_test.go, action/protocol/account/transfer.go, action/protocol/account/transfer_test.go, action/protocol/account/util/util.go, action/protocol/execution/evm/contract_test.go, action/protocol/execution/evm/evm.go, action/protocol/execution/evm/evmstatedbadapter.go, action/protocol/execution/protocol_test.go, action/protocol/poll/protocol.go, action/protocol/rewarding/fund.go, action/protocol/rewarding/fund_test.go, action/protocol/rewarding/protocol.go, action/protocol/rewarding/protocol_test.go, action/protocol/rewarding/reward.go, action/protocol/rewarding/reward_test.go, actpool/actpool_test.go, api/api_test.go, blockchain/blockchain_test.go, blockchain/blockvalidator_test.go, blocksync/blocksync_test.go, blocksync/buffer_test.go, chainservice/chainservice.go, consensus/scheme/rolldpos/rolldpos_test.go, consensus/scheme/rolldpos/roundcalculator_test.go, e2etest/bigint_test.go, e2etest/local_test.go, gasstation/gasstattion_test.go, state/factory/factory_test.go
LoadOrCreateAccount shouldn't come with init balance parameter. This PR deletes the "init" parameter, and introduce a "createAccount" in account protocol to initialize account balance.
=> Modify load or create account

action/protocol/poll/nativestaking.go, action/protocol/poll/nativestaking_test.go, action/protocol/poll/staking_committee.go, action/protocol/rewarding/protocol.go, action/protocol/rewarding/protocol_test.go, action/protocol/rewarding/reward.go, action/protocol/rewarding/reward_test.go, api/api.go, api/api_test.go, blockchain/blockchain.go, chainservice/chainservice.go, consensus/scheme/rolldpos/roundcalculator_test.go
Both ReadContract and ProductivityByEpoch are able to get context.Context from Protocol. This PR tries to use the existing context.Context, instead of generating one, to prevent dead lock.
=> use existing context

action/protocol/execution/protocol_test.go, actpool/actpool_test.go, api/api.go, api/api_test.go, blockchain/blockchain.go, blockchain/blockchain_test.go, blockchain/blockvalidator_test.go, blocksync/blocksync.go, blocksync/blocksync_test.go, chainservice/chainservice.go, e2etest/bigint_test.go, e2etest/local_test.go, e2etest/rewarding_test.go, gasstation/gasstattion.go, gasstation/gasstattion_test.go, test/mock/mock_blockchain/mock_blockchain.go, tools/staterecoverer/staterecoverer.go
following to PR #1783, remove BlockDAO() from blockchain interface and use dao directly (not through bc)
=> remove BlockDAO() from blockchain interface

action/protocol/poll/governance_protocol.go, action/protocol/poll/lifelong_protocol.go, action/protocol/poll/protocol.go, action/protocol/poll/staking_committee.go, action/protocol/poll/util.go, api/api_test.go, consensus/consensus.go, consensus/scheme/rolldpos/rolldpos.go, consensus/scheme/rolldpos/rolldpos_test.go, consensus/scheme/rolldpos/rolldposctx.go, consensus/scheme/rolldpos/rolldposctx_test.go, consensus/scheme/rolldpos/roundcalculator.go, consensus/scheme/rolldpos/roundcalculator_test.go, consensus/scheme/scheme.go
1. In roundCalculator, instead of using candidatesByHeightFunc, use DelegatesByEpochFunc from poll protocol so that we can unify same logic 
2. refactor poll protocol 
- change name from DelegatesByHeight to CalculateCandidatesByHeight which is used for putpollresult
- clarity method/variable name since delegate/candidate is confusing
=> Use DelegatesByEpoch to unify the same logic at consensus

action/protocol/poll/governance_protocol.go, action/protocol/poll/protocol.go, action/protocol/poll/staking_committee.go, action/protocol/poll/staking_committee_test.go, action/protocol/poll/util.go, consensus/scheme/rolldpos/rolldposctx.go
Previous we called governance protocol's createPostSystemActions() in staking_committee, but we should use its own createPostSystemActions() so that it'll call correct CalculateCandidatesByHeight. 
But I'm also curious if we had any breaking chain issue because of this bug?
=> fix a bug in createPostSystemActions() at poll protocol

consensus/scheme/rolldpos/rolldposctx.go
When we write/read from eManagerDB using block pb, it won't store workingset in block. 
So in case that the pending block is read from eManagerDB, we need to regenerate ws before commit it.
=> fix a bug in eManagerDB by regenerating workingset

consensus/scheme/rolldpos/rolldpos.go
context will close the poll.db, when it is stopped first, fsm might still write into db, which caused panic on Stop().
=> stop consensus fsm before context

api/api.go, api/listener.go, blockchain/blockchain.go, blockchain/blockchain_test.go, blockchain/blockcreationsubscriber.go, blockchain/blockdao/indexbuilder.go, blockchain/blockdao/indexbuilder_test.go, chainservice/chainservice.go, test/mock/mock_blockchain/mock_blockchain.go, test/mock/mock_blockcreationsubscriber/mock_blockcreationsubscriber.go, test/mock/mock_blockdao/mock_blockdao.go
because when we broadcast block we are using goroutine, the order can be different. So make a buffer to store pending blocks and make sure to put/commit block in order
=> put/commit block in order into indexer by using buffer 

api/api.go, api/listener.go, blockchain/blockchain.go, blockchain/blockcreationsubscriber.go, blockchain/blockdao/indexbuilder.go, blockchain/blockdao/indexbuilder_test.go, chainservice/chainservice.go
Because each subscriber has same handler logic using goroutine, move this logic to blockchain.go
And when addsubscriber/removesubscriber, create the handler thread and kill it.
=> move handler goroutine logic from subscriber to blockchain

state/factory/factory.go, state/factory/statedb.go
fixed a deadlock bug by only lock/unlock mutex when accessing workingsets cache
=> Fix a deadlock bug  

action/protocol/poll/nativestaking.go, action/protocol/poll/staking_committee.go, e2etest/staking_test.go
Somehow, the height could change in one round. Change to epoch number as we assume that the Votes should only be calculated once per epoch.
=> replace buffer key from height to epoch number

action/protocol/account/protocol.go, action/protocol/account/protocol_test.go, action/protocol/account/transfer_test.go, action/protocol/account/util/util.go, action/protocol/execution/evm/contract_test.go, action/protocol/execution/evm/evm_test.go, action/protocol/execution/evm/evmstatedbadapter.go, action/protocol/execution/evm/evmstatedbadapter_test.go, action/protocol/managers.go, action/protocol/poll/governance_protocol_test.go, action/protocol/poll/lifelong_protocol_test.go, action/protocol/poll/staking_committee_test.go, action/protocol/poll/util.go, action/protocol/rewarding/protocol.go, action/protocol/rewarding/protocol_test.go, action/protocol/rewarding/reward_test.go, action/protocol/vote/candidatesutil/candidatesutil.go, actpool/actqueue_test.go, api/api_test.go, blockchain/blockchain.go, e2etest/staking_test.go, state/factory/factory.go, state/factory/factory_test.go, state/factory/statedb.go, state/factory/statetx.go, state/factory/workingset.go, test/mock/mock_chainmanager/mock_chainmanager.go, test/mock/mock_factory/mock_factory.go, test/mock/mock_factory/mock_workingset.go, tools/actioninjector.v2/internal/client/client_test.go
=> refactor StateManger/StateReader

action/protocol/execution/evm/contract.go, action/protocol/execution/evm/contract_test.go, action/protocol/execution/evm/evm_test.go, action/protocol/execution/evm/evmstatedbadapter.go, action/protocol/execution/evm/evmstatedbadapter_test.go, action/protocol/execution/evm/kvstorefortrie.go, action/protocol/execution/evm/serializablebytes.go, action/protocol/execution/protocol_test.go, action/protocol/managers.go, blockchain/blockchain_test.go, db/kvstore.go, db/kvstore4trie.go, db/mock_kvstore_test.go, db/trie/branchroottrie.go, state/factory/factory.go, state/factory/factory_test.go, state/factory/statedb.go, state/factory/twolayertrie.go, state/factory/workingset.go, test/mock/mock_chainmanager/mock_chainmanager.go
based on #1894, jump to the last commit please.
Eventually, we delete statemanager.GetDB, and use StateManager itself to simulate the DB.Get/Put/Delete.
=> Use statemanager in contract

action/protocol/vote/blacklist.go, action/protocol/vote/unproductivedelegate.go
The serialize of blacklist and unproductive delegate list both have the problem of using keys of map without sorting them. This PR fixed the two bugs.
=> fix two serialize bugs

Makefile
In Makefile, there is a duplicate ioctl command, overriding the correct command. It should be xctl.
=> Duplicate ioctl command in Makefile

ioctl/cmd/bc/bc.go, ioctl/cmd/node/nodedelegate.go
add blacklist column when reading delegate info from ioctl for testing
=> add blacklist column when reading delegate in ioctl

action/protocol/staking/candidate.go
in last commit, I removed the inactive flag. so this code is dup now, we only need to get with one key instead of try two
=> remove dup get candidate

blockchain/blockchain_test.go, db/trie/branchroottrie.go, db/trie/kvstoreimpl.go, db/trie/kvstoreimpl_test.go, db/trie/trie_test.go, db/trie/twolayertrie.go, db/trie/twolayertrie_test.go, state/factory/factory.go
Move TwoLayerTrie and KVStoreForTrie into trie package
Fix the bug of mixture usage of db.ErrNotExist and trie.ErrNotExist
=> move two layer trie and trie kvstore implementation into trie package

action/protocol/execution/evm/contract_test.go, action/protocol/execution/protocol_test.go, api/api_test.go, blockchain/blockchain_test.go, blockchain/blockdao/blockdao_test.go, blockindex/indexbuilder_test.go, blockindex/indexer_test.go, blocksync/blocksync_test.go, consensus/scheme/rolldpos/roundcalculator_test.go, db/counting_index_test.go, db/db_bolt_test.go, db/db_test.go, db/range_index_test.go, db/sql/sqlite3_test.go, db/trie/trie_test.go, e2etest/local_actpool_test.go, e2etest/local_test.go, e2etest/local_transfer_test.go, e2etest/native_staking_test.go, e2etest/rewarding_test.go, e2etest/staking_test.go, ioctl/cmd/account/account_test.go, state/factory/factory_test.go, testutil/file.go
`os.TempFile()` creates and occupies new file on Windows. Many test cleanups fails on Windows due to those occupations. Thus, I close all those files after created in this PR.
=> fix test cleanup fail on Windows

ioctl/cmd/account/account.go
for example:
strings.TrimRight(strings.TrimLeft("sm2sk-io1tx4nf330r2ewdp8u4vt9gk5rmdnkxeajcl828m.pem", "sm2sk-"), ".pem")
return：io1tx4nf330r2ewdp8u4vt9gk5rmdnkxeajcl828
=> Sporadic CI test failure 2032

action/protocol/poll/governance_protocol.go, action/protocol/rewarding/reward.go
Currently, because of hard kick-out, readCandidate API doesn't include hard-kicked out delegate at all, so for front-end/analytics it is confusing because they can't find those from list.
So I keep same hard kick-out logic, but we don't delete those from candidate list and just keep with 0 voting power. Instead, we exclude who's voting power is 0 when picking up top 36
=> Move hard kick-out logic to the place picking up top 36 

Makefile, action/protocol/poll/candidateindexer.go, action/protocol/poll/governance_protocol.go, action/protocol/poll/governance_protocol_test.go, action/protocol/poll/lifelong_protocol.go, action/protocol/poll/protocol.go, action/protocol/poll/protocol_test.go, action/protocol/poll/staking_committee_test.go, action/protocol/poll/util.go, api/api.go, api/api_test.go, blockchain/blockchain.go, chainservice/chainservice.go, config/config.go, e2etest/local_transfer_test.go, state/factory/factory_test.go, tools/minicluster/minicluster.go
Because archive mode takes too much time, add indexer to store candidate/blacklist for API call (ReadState and GetEpochMeta) 
1. implement candidateIndexer and if exists, read from indexer at ReadState() in poll.Protocol 
2. Refactor ```productivityByEpoch``` to distinguish API purpose and protocol purpose
(DelegatesByEpoch is only for protocol purpose -- related to tip) 
I will refactor ```productivityByEpoch``` in next PR to only keep current epoch data in state factory and move into poll protocol
=> add candidateIndexer to store candidate/kickoutlist for API call

action/protocol/poll/governance_protocol.go, action/protocol/poll/util.go
we have to use stateReader's tip height
for example, in startExistingBlockchain, if the blockchain Tip is higher than state factory height and restore factory, stateFactory's tip height is the right thing to compare with
=> fix a bug to use stateReader Height

action/protocol/poll/governance_protocol.go, action/protocol/poll/governance_protocol_test.go, action/protocol/poll/protocol.go, action/protocol/poll/slasher.go, action/protocol/poll/staking_committee_test.go, action/protocol/rewarding/protocol_test.go, action/protocol/rewarding/reward_test.go, action/protocol/vote/blacklist.go, action/protocol/vote/candidatesutil/candidatesutil.go, api/api_test.go, state/factory/factory_test.go
think of poll protocol as 2 parts:
1. governance (with staking V1 after Cook) or staking V2 (after Fairbank) gives out candidates list
2. slasher gives out kick-out list (after Easter)
staking_committee (and new staking_command) can then use slasher
=> move kickout code to slasher

action/protocol/poll/governance_protocol_test.go, action/protocol/poll/protocol.go, action/protocol/poll/protocol_test.go, action/protocol/poll/slasher.go, action/protocol/poll/staking_committee_test.go, action/protocol/rewarding/protocol.go, action/protocol/rewarding/protocol_test.go, action/protocol/rewarding/reward.go, action/protocol/rewarding/reward_test.go, action/protocol/rolldpos/epoch.go, api/api.go, api/api_test.go, blockchain/blockchain.go, chainservice/chainservice.go, consensus/scheme/rolldpos/roundcalculator_test.go, go.sum, state/factory/factory_test.go
Move epoch out of ProductivityByEpoch in blockchain.go, and rename it to Productivity
=> move epoch related concept out of blockchain

blockchain/blockdao/blockdao.go, test/mock/mock_blockdao/mock_blockdao.go
fix 2 bugs 
1. deadlock issue
2. In GetTopDB() in case of ```index the height --> file index mapping``` it should put index(top+1) 
For dead lock issue, the blockdao mutex is not for general usage but for creating new files/ rangeIndex files. But while previous refactoring, in the ```putBlock(), DeleteBlockToTarget()```, we lock/unlock mutex wrongly.
=> fix blockdao deadlock bug

ioctl/cmd/node/nodedelegate.go
#2078 
"Total blocks in epoch" => "Total blocks produced in epoch"
=> rename ioctl node delegate output message

action/protocol/staking/candidate.go, action/protocol/staking/candidate_center.go, action/protocol/staking/candidate_center_test.go, action/protocol/staking/candidate_statemanager.go, action/protocol/staking/handlers_test.go, action/protocol/staking/protocol.go, action/protocol/staking/read_state.go
CandidateCenter is still widely used
after we finish moving CandidateCenter to state factory + remove LRU, we can revisit if it's possible to remove it
=> [staking] remove CandidateView interface

action/protocol/poll/governance_protocol.go, action/protocol/poll/slasher.go, action/protocol/rolldpos/epoch.go, action/protocol/rolldpos/epoch_test.go, api/api.go, api/api_test.go, ioctl/cmd/bc/bc.go, ioctl/cmd/node/nodedelegate.go, ioctl/newcmd/bc/bc.go, ioctl/newcmd/node/nodedelegate.go
In API side, we decided not to use golang byteutil.BytesToUint64 but to use strconv.Parse/Format to support more general usage.
=> Update ReadState API deserialize method between bytes and uint64

db/counting_index.go, db/db_bolt.go, db/kvstore.go, db/mock_kvstore.go
the correct fix is to let index (which can use the FillPercent feature) to call a different interface WriteBatchWithFillPercent(percent), other writes (like putBlock) still use normal WriteBatch()
thus we remove the need of an LRU cache to save these index's address
=> [db] better fix to remove LRU cache from boltDB

ioctl/cmd/contract/contract.go, ioctl/cmd/contract/contractcompile.go, ioctl/cmd/root.go, ioctl/flag/flag.go, ioctl/output/format.go
This command needs local solc to complete. A contract prepare command is needed to install solc.
=> add contract compile command for ioctl

action/protocol/staking/handlers.go, action/protocol/staking/protocol.go
we can actually move out all the "p.settleAction" out from handlers.go to do it here, will have another PR to clean-up
first check-in this to unblock testing
=> [staking] early resolve invalid staking or conflict error

action/protocol/poll/candidateindexer.go, action/protocol/vote/candidatesutil/candidatesutil.go
rename kickout to probation diff: https://github.com/iotexproject/iotex-core/pull/2071
include some changes not in v0.11(https://github.com/iotexproject/iotex-core/tree/v0.11.1) like name space change and key change. this diff revert those changes.
=> revert namespace naming changes to make them consistent with v0.11

action/protocol/staking/protocol.go, blockindex/indexer.go, db/counting_index.go, db/counting_index_test.go, db/kvstore_impl.go, state/factory/factory.go, state/factory/statedb.go
when indexing a block (assume 1 transfer), it usually need to update 5 account/states: total block, total action, sender, receiver, grantreward
each account/state is represented by a counting index, so it ends up 5 calls of db.WriteBatch()
these writes can be combined into a single batch, hence only calling db.WriteBatch() 1 time
indexer.PutBlock() time reduced 50~70% according to test, here's the running time to index 3 blocks in test:
before:
==== 210.572331ms
==== 151.561612ms
==== 134.105388ms
after
==== 124.215178ms
==== 64.461701ms
==== 45.41873ms
=> [db] improve indexer write speed using common batch

ioctl/cmd/bc/bc.go, ioctl/cmd/node/nodedelegate.go, ioctl/cmd/node/nodeprobationlist.go
It will fix the issue that ```ioctl node probationlist``` before easter epoch, returned current epoch's probationlist. But it should return error.
=> fix a bug by putting a height argument in ioctl readstate request

action/protocol/staking/protocol.go, action/protocol/staking/read_state.go, action/protocol/staking/vote_bucket.go, ioctl/cmd/bc/bcbucket.go
works on #2201 
Change ReadState API side to return not error but nil result if it's withdrawn, and handle on ioctl the client side to show withdrawn bucket status.
=> change readstate API to display bucket withdrawn status on ioctl 

ioctl/cmd/node/node.go, ioctl/cmd/node/nodedelegate.go
work on #2208
1. `ioctl node delegate` still displays top 36 delegates, same as before
2. `ioctl node delegate -a` or `ioctl node delegate --all`  displays all delegates, and make delegates after first 36 sorted by votes
=> [ioctl] use -a to display all delegates 2208

ioctl/cmd/action/action.go, ioctl/cmd/action/actionclaim.go, ioctl/cmd/action/actiondeposit.go, ioctl/cmd/action/actiontransfer.go, ioctl/cmd/action/stake2Transfer.go, ioctl/cmd/action/stake2Withdraw.go, ioctl/cmd/action/stake2add.go, ioctl/cmd/action/stake2change.go, ioctl/cmd/action/stake2create.go, ioctl/cmd/action/stake2reclaim.go, ioctl/cmd/action/stake2register.go, ioctl/cmd/action/stake2release.go, ioctl/cmd/action/stake2renew.go, ioctl/cmd/action/stake2update.go, ioctl/cmd/action/xrc20allowance.go, ioctl/cmd/did/did.go, ioctl/cmd/did/diddoc.go, ioctl/cmd/did/didgenerate.go, ioctl/cmd/root.go
work on #2228 
using:
`ioctl did generate -s yy`
`Enter password #io1ladc7y0scpcs768xvusqn6r7thavafe8wyxypa:`
```
{
"@context": "https://www.w3.org/ns/did/v1",
"id": "did:io:0xff5b8f11f0c0710F68e6672009e87e5DFacea727",
"authentication": [
{
"id": "did:io:0xff5b8f11f0c0710F68e6672009e87e5DFacea727#owner",
"type": "EcdsaSecp256k1VerificationKey2019",
"controller": "did:io:0xff5b8f11f0c0710F68e6672009e87e5DFacea727",
"publicKeyHex": "033f8dc3224ed5d2212e0b89093044294c55a286a29417e20393a82a682517d6f1"
}
]
}
```
=> add ioctl did command to generate did document 2228

db/trie/mptrie/branchnode.go, db/trie/mptrie/cachenode.go, db/trie/mptrie/extensionnode.go, db/trie/mptrie/hashnode.go, db/trie/mptrie/leafiterator.go, db/trie/mptrie/leafnode.go, db/trie/mptrie/merklepatriciatrie.go, db/trie/mptrie/node.go, db/trie/mptrie/twolayertrie.go
This is the last 3rd PR for splitting PR #2107 
1. introduce cache/hash node in mptrie. From what I understood the zhi's PR, the cachenode is holding common things(serialzed stream and hash of the node). Also, while trie operation, having hash node as a field enables reducing unncessary loading by only holding meta data (hash) and load the node if necessary. We can think of hashnode is a wrapper to make the nodes light. 
2. fix a 2layertrie bug 
It doesn't include "cancel out" improvement in this PR
=> introduce cache/hash node in mptrie

Dockerfile
SSIA. Here is size difference of unpacked images, ~10 times smaller
```shell
docker images
REPOSITORY                                 TAG                 IMAGE ID            CREATED              SIZE
iot                                        0                   b8d834a3b050        2 minutes ago       189MB
iotex/iotex-core                           v1.0.0              74efb029ceb6        6 weeks ago         1.82GB
```
=> Add multistage build to decrease image size

ioctl/cmd/did/didgenerate.go
```
ioctl did generate -s testaccount
Enter password #io1vdtfpzkwpyngzvx7u2mauepnzja7kd5rryp0sg:
{
"@context": "https://www.w3.org/ns/did/v1",
"id": "did:io:0x6356908ACe09268130DEE2b7de643314BBeb3683",
"authentication": [
{
"id": "did:io:0x6356908ACe09268130DEE2b7de643314BBeb3683#owner",
"type": "EcdsaSecp256k1VerificationKey2019",
"controller": "did:io:0x6356908ACe09268130DEE2b7de643314BBeb3683",
"publicKeyHex": "03ea8046cf8dc5bc9cda5f2e83e5d2d61932ad7e0e402b4f4cb65b58e9618891f5"
}
]
}
The hex encoded SHA256 hash of the DID doc is:e123ae6f24d38786a071539970d7bc0d299d43d5316204fa16ba81b766278024
```
=> add generate did doc hash

db/trie/mptrie/merklepatriciatrie.go, db/trie/mptrie/merklepatriciatrie_test.go
in async mode, check root node instead of root hash.
=> fix IsEmpty bug in merkle patricia trie

db/trie/mptrie/merklepatriciatrie_benchmark_test.go
run with `go test -bench=. -run=BenchmarkTrie -benchtime=4x`
In the result, the "upsert times" shows the number of "upsert" actions on trie (+1/2 delete actions), and "buffer size" is the db actions. For example:
upsert times: 4 buffer size: 18
=> add benchmark test for trie operation

ioctl/cmd/node/nodedelegate.go
work on #2260 
The new command is like this:
```
ioctl node delegate -e 10518
Epoch: 10518,  Start block height: 5756041,Total blocks produced in epoch: 720
Address                                     Name           Rank   Alias   Status   Blocks   ProbatedStatus    Votes
io108h7sa5sap44e244hz649zyk5y4rqzsvnpzxh5   royalland         1           active   30                       133593082.452736305852276477
io1puxw08ze2jnv5x4943ly273tkyth56p9k6ssv9   huobiwallet       2                    0                        108755999.652091904181493681
io1kr85xacgvhg9l4hj4atr243sw540g6cssajqrz   droute            3           active   30                       99647818.571951801495599143
io10reczcaelglh5xmkay65h9vw3e5dp82e8vw0rz   metanyx           4           active   30 …
```
=> fix using wrong epoch data

action/protocol/execution/evm/contract.go, action/protocol/execution/evm/contract_test.go, action/protocol/execution/protocol_test.go
1. Move root hash calculation into snapshot and commit, @koseoyoung is testing the change on Mainnet, it has been height 5.1M/5.8M
2. Add benchmark test
async      10         462033771 ns/op
sync      10         580280197 ns/op
async      20         507928689 ns/op
sync      20         641516703 ns/op
async      40         593998320 ns/op
sync      40         767366155 ns/op
async      80         708751901 ns/op
sync      80         884618497 ns/op
test result shows that the improvement is more significant as contract gets more complicated
=> improve hot contract and add benchmark test

action/protocol/execution/evm/evm.go
time.Time{} is the 0001-1-1 00:00:00, which is invalid for users who want to use block.timestamp in simulation.
=> use tip timestamp + block interval as block time for simulation

action/protocol/execution/evm/contract.go
https://github.com/iotexproject/iotex-core/pull/2259 was supposed to improve "async mode", but was applied to "sync mode" by accident. This is a fix for that.
=> fix digest issue in contract

action/protocol/staking/handlers.go
The topics were added after permission checking, the logic of which was changed in a recent PR.
Test Plan:
Pass the first "Transfer Ownership" failure case.
=> add topics after permission checking

db/trie/mptrie/branchnode.go
Looping branch node's children in some order to have consistent result.
=> iterate branch node children in order

action/protocol/poll/slasher.go
Currently, we are checking sr.height and epoch number argument to be same in readstate().
Since we don't need to check in case of using indexer(b/c not using sr), make to skip this comparison if we are using indexer.
=> make to compare epochnumber arguments in case of not using indexer in readstate

api/api.go
work on #2276 
request:
```
grpcurl -v -plaintext -d '{"address": "io000000000000000000000000stakingprotocol"}' 127.0.0.1:14014 iotexapi.APIService.GetAccount
grpcurl -v -plaintext -d '{"address": "io0000000000000000000000rewardingprotocol"}' 127.0.0.1:14014 iotexapi.APIService.GetAccount
```
response:
```
{
"accountMeta": {
"address": "io0000000000000000000000rewardingprotocol",
"balance": "0",
},
"blockIdentifier": {
"hash": "6ba52c53ed61a04148147efe3b4a1270867342e160710fed7eedebcf3438e19d",
"height": 3
}
}
{
"accountMeta": {
"address": "io000000000000000000000000stakingprotocol",
"balance": "0",
},
"blockIdentifier": {
"hash": "6ba52c53ed61a04148147efe3b4a1270867342e160710fed7eedebcf3438e19d",
"height": 3
}
}
```
=> wrap get staking and rewarding protocol balance in GetAccount api 2276

state/factory/factory.go, state/factory/factory_test.go, state/factory/statedb.go
By default, call ValidateBlock; in test environment, skip block validation (digest validation).
=> skip block level validation in put block

ioctl/cmd/action/actiondeploy.go, ioctl/cmd/action/actioninvoke.go
disable flag parsing in deprecated cmd
Now `ioctl action deploy/invoke contract <flag> <arguments>` will not show useless information, they will return new cmd examples.
=> disable flag parsing in deprecated cmd

ioctl/cmd/did/did.go
work on #2376
ioctl did command add endpoint flag support,like this:
`ioctl did gethash io1m3wjevwhz2s58sasq0wj4luxrnqt047s687zw8 did:io:0x8601CAb8A22bA1DB04ce909E4Ec1deE5555Bf3B0 --endpoint api.testnet.iotex.one:80 --insecure`
=> ioctl did should have global flags endpoint and insecure 2376

README.md
The link of whitepaper link no longer exists. Home site is changed. Use the new url
=> Change https://www.iotex.io/research-paper -> https://iotex.io/research/

ioctl/cmd/node/nodedelegate.go, ioctl/cmd/node/nodeprobationlist.go
In [standalone](https://github.com/iotexproject/iotex-core/blob/master/config/standalone-config.yaml) mode or no consensus configurations mode, `ioctl node delegate` or `ioctl node probationlist` will crash cause no consensus registered.
=> fixed: ioctl  node delegate crashes if ROLLDPOS not register (#2390)

api/api.go, api/api_test.go
SWFT/IoTeX chat group raised the question to get all actions in a block, it needs 2 RPC calls:
1. call GetBlockMeta, to get numActions = # of actions in the block
2. call GetActionsByBlock, with start = 0, count = numActions to get all actions
with this PR, just need 1 RPC call: call GetActionsByBlock, with start = 0, count = 0 will return all actions in the block
=> api.GetActionByBlock to return all actions in block if count = -1

action/protocol/execution/protocol_test.go, api/api_test.go, blockchain/block/block_test.go, blockchain/blockchain.go, blockchain/blockdao/blockdao.go, blockchain/blockdao/blockdao_test.go, blockchain/blockdao/filedao.go, blockchain/blockdao/filedao_legacy.go, blockchain/blockdao/filedao_test.go, blockchain/integrity/integrity_test.go, blockindex/indexbuilder.go, blockindex/indexbuilder_test.go, blocksync/blocksync_test.go, chainservice/chainservice.go, e2etest/bigint_test.go, e2etest/local_test.go, gasstation/gasstattion_test.go, misc/scripts/mockgen.sh, test/mock/mock_blockdao/mock_blockdao.go, tools/iomigrater/cmds/check-height.go, tools/iomigrater/cmds/migrate-db.go
1. this PR only adds the FileDAO interface and move current block read/write code to filedao_legacy.go
2. next PR will handle the new file implementation
3. last PR will take care how to handle chain db file depending on sf.Height(), and starting chain only on statedb
=> [BlockDAO] add FileDAO interface to manage chain db file

ioctl/cmd/node/nodereward.go
```
➜  iotex-core git:(raullen) ✗ ioctl node reward pool
Total Unclaimed:	 26670626.912383428847851662 IOTX
Total Available:	 882465182.37090161749159405 IOTX
Total Balance:		 909135809.283285046339445712 IOTX
```
=> Format output of `ioctl node reward pool`

action/protocol/execution/protocol_test.go, blockchain/filedao/filedao_v2.go, blockindex/indexer.go, chainservice/chainservice.go, config/config.go, db/db_bolt.go, db/db_test.go, db/kvstorewithcache.go, e2etest/local_test.go, state/factory/factory.go, state/factory/factory_test.go, state/factory/statedb.go
works on #2457 
Define kvStoreWithCache(LRU) in stateDB to store latest states to speed up (statedb caching).
We can decide StateMaxCacheSize by experiments.
=> Add CachedStateDBOption to wrap kvstore with LRU cache in stateDB for speed up 

api/api.go
As we are doing in https://github.com/iotexproject/iotex-core/blob/master/api/logfilter.go#L45 here, in getLogs API, look up LogsBloomFilter first, and then if it exists, look up the logs in the receipts.
=> Check LogsBloomFilter before look up receipts in getLogs API

pkg/util/httputil/httputil.go
for getting better prof connection: https://golang.org/src/net/http/pprof/pprof.go
```
// Profile responds with the pprof-formatted cpu profile.
// Profiling lasts for duration specified in seconds GET parameter, or for 30 seconds if not specified.
// The package initialization registers it as /debug/pprof/profile.
```
=> increase http connections timeout

blockchain/blockdao/blockdao.go
when we rebuild bloomfilter indexer, in case of filedao_legacy, ```dao.GetBlockByHeight()``` does not include receipts. 
In order to fix a bug of rebuilding bf indexer, added ```dao.getReceipts() ```
=> fix a bf indexer rebuilding bug by adding receipts in blockdao 

ioctl/cmd/action/action.go
if solc failed or some other unexpected happens, throw an error to prevent further damage.
=> catch unexpected status

ioctl/cmd/action/xrc20allowance.go
xrc20 allowance cmd requires signer flag(L49), but currently we miss it
=> need signer flag in ioctl xrc20 allowance cmd

config/config.go
as discussed in mtg, roll out this feature in 1.2 release
=> enable split v2 DB file at every 1,000,000 blocks

action/protocol/staking/handlers.go, action/protocol/staking/handlers_test.go, action/protocol/staking/vote_reviser.go, action/protocol/staking/vote_reviser_test.go, chainservice/chainservice.go
When the new candidate is same as old one, staking handler are dealing
with 2 copies of the same candidate: vote of the first being deducted,
and vote of the second being added -- yet the second change overwrites
the first, b/c these 2 are the same candidate. This caused the total
vote to be incorrectly increased.
=> [staking] fix change candidate bug

action/actctx.go, action/action.go, action/builder_test.go, action/envelope.go, action/execution.go, action/execution_test.go, action/protocol/account/transfer_test.go, action/protocol/execution/evm/evm.go, action/protocol/execution/evm/evm_test.go, action/protocol/execution/protocol_test.go, action/protocol/poll/consortium.go, action/protocol/poll/staking_committee.go, action/putpollresult.go, action/sealedenvelope.go, action/transfer.go, action/transfer_test.go, api/api_test.go
1. removed AbstractAction.hash. Hash of an action should be at the
level of Envelope and sealed envelope
2. removed unnecessary methods
=> [action] improve envelope handling

e2etest/local_transfer_test.go
original local_transfer_test.go did not checked the return error detail information.
it may cause confusion.
for example, a test case was expected to catch error when nonce field error.
but the case maybe got an error which was throw because balance not enough.
so I add "expectedDesc" field to verify error type.
=> add expectedDesc for local_transfer_test

ioctl/cmd/account/account.go, ioctl/cmd/account/accountinfo.go
fixed #2608 
By typing `ioctl account info (ALIAS|ADDRESS)` in the ioctl CLI, the information of the account will be displayed. 
e.g.
> io1vqzcl56vlfspyaadyxhqy07jrmalx73vdaklzn:
{
"address": "io1vqzcl56vlfspyaadyxhqy07jrmalx73vdaklzn",
"balance": "0",
"nonce": 1,
"pendingNonce": 2,
"numActions": 10258,
"isContract": true,
"contractByteCode": "60806040526004361061018a5763ffffffff7c0100000000000000000000000000000000000000000000000000000000600035041663030ba25d811461018f57806307c35fc0146101b55780631b0690ed146101f257806324953eaa14610207578063286dd3f5146102705780632f54bf6e146102915780633f4ba83a146102b2578063423ce1ae146102c75780635c975abb146102eb5780635fec5c641461030057806363809953146103155780636c0a5ebd1461032a5780636e7b3017146103e557806376f70003146103fc5780637b24a5fd146104115780637b9417c8146104 …
=> add 'ioctl account info' command

action/protocol/rewarding/reward_test.go
fix #2521 
Run `go test -run TestProtocol_ClaimReward` will fail, but run `go test` will pass.
When run `go test`, func TestProtocol_Handle runs before func TestProtocol_ClaimReward. The initial balance of account was changed to 1000000 on Line 302 in `protocol_test.go` 
```
cfg.Genesis.Rewarding.InitBalanceStr = "1000000"
```
However, if func TestProtocol_Handle runs alone, its initial balance is 100000000000000000000000000
Use a variable `initBalance` to record the initial balance of account when entering func TestProtocol_Handle
=> Fix test TestProtocol_ClaimReward

blockchain/blockdao/blockdao.go
fix #2698 
The issue is caused by reuse of context in [L164](https://github.com/iotexproject/iotex-core/blob/0796d378aaedf3b802fead0090a7f26669a0c37f/blockchain/blockdao/blockdao.go#L164). As block height increases, the context var becomes larger due to reuse.
=> Solve a bug in checkIndexers()

action/protocol/staking/candidate_buckets_indexer.go, action/protocol/staking/candidate_buckets_indexer_test.go, action/protocol/staking/protocol_test.go, db/db_bolt.go, db/kvstore.go, db/mock_kvstore.go, db/range_index.go, test/mock/mock_blocksync/mock_blocksync.go, test/mock/mock_dispatcher/mock_dispatcher.go
current db may store a lot of duplicates, for example:
height: 5 --> cand{1, 2, 3}
height: 6 --> cand{1, 2, 3} // same as height 5
height: 7 --> cand{1, 2, 3} // same as height 5
height: 8 --> cand{1, 2, 3, 4}
with this change, duplicates are removed, so the db becomes:
height: 5 --> cand{1, 2, 3}
height: 8 --> cand{1, 2, 3, 4}
query for height 6/7 will fallback to height 5
=> optimize staking index DB storage

api/api.go, pkg/tracer/tracer.go, pkg/tracer/tracer_test.go
half of traces will be sampled
```
api:
tracer:
endpoint: http://localhost:14268/api/traces
samplingRatio: .5
```
=> [api]Tracing sampling support

action/protocol/context.go, action/protocol/execution/evm/evm.go, action/protocol/execution/evm/evm_test.go, action/protocol/execution/evm/evmstatedbadapter.go, action/protocol/execution/evm/evmstatedbadapter_test.go
the clearSnapshot fix is not properly implemented, so we fixed it again at LordHowe height https://github.com/iotexproject/iotex-core/commit/9dba94df2e4233d85ea4d5998f7316138933ff13
this PR is to apply the correct fix at Kamchatka height (as if we would have implemented it correctly at first time)
it is verified both Mainnet and Testnet can correctly sync with this change
=> [evm] apply clearSnapshots fix back to Kamchatka height

api/listener.go, api/read_cache.go, go.mod, go.sum, tools/minicluster/minicluster.go, tools/util/injectorutil.go
as discussed earlier, Responder and read cache in API does not need LRU, instead just need thread-safe map
tested on fullnode, register/exit Responder can work correctly
=> [api] use ttl.Cache for responder and read cache

api/web3server.go, api/web3server_test.go
GetNetworkID() should return value in string type
=> [api] fix type err in GetNetworkID()

api/web3server.go, api/web3server_test.go, api/web3server_utils.go
fix the bug that the server returns `null` instead of `[]` when calling web3 api `eth_getLogs`,
=> [api] fix web3 empty return

Makefile
`make` is not `bash`, so `mkdir -p /var/{data,log}` will only create a folder called `{data,log}`
=> [makefile] fix bug when `make run`

action/protocol/execution/evm/evm.go
this might be the reason for api node restart
=> [evm] check null pointer before dump calldata

api/web3server.go, api/web3server_test.go, api/web3server_utils.go
https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L1552
When blk number is "pending", the pending nonce of the addr in the actpool should be returned.
Otherwise, the number of confirmed nonce should be returned.
=> [api] fix nonce bug in getTransactionCount

ioctl/cmd/action/actiontransfer.go
[ioctl] action transfer should bail out if recipient is a contract  for #2962
=> [ioctl] action transfer should bail out if recipient is a contract

db/trie/mptrie/merklepatriciatrie_test.go, state/factory/factory.go
Storing the deletion write info is not essential part for archive mode. Delete the related code to reduce the size of archive mode db.
=> remove the code storing the deletion write info

actpool/actqueue.go, actpool/actqueue_test.go
- After deleting `i`th element in the array, the old `i+1`th element become `i`th element in the new array. So `i++` should be skipped. 
- Old deleting method would make heap invalid in certain scenarios. For instance, If `7` is removed from heap `[1, 5, 2, 6, 7, 3]`, the new heap `[1, 5, 2, 6, 3]` is invalid.
- func `clock.Now()` is time-consuming. Remove it out of the loop
- `append(q.index[:i], q.index[i+1:]...)` is O(n). Deleting the element can be achieved by swap it with the last element in the array. And reinitate the heap `heap.Init(&q.index)` in the end.
=> [actpool] fix iterator issue and make code more efficient in cleanTimeout

action/protocol/context.go, action/protocol/execution/evm/evm.go, blockchain/integrity/integrity_test.go
found during debugging EVM, when doing a normal contract call (not deployment), our receipt did not save the contract's address but left it empty instead. This is somehow neglected in the current codebase
=> [evm] add contract address into receipt

blockchain/integrity/integrity_test.go
This PR is based on #2984. To review, jump to https://github.com/iotexproject/iotex-core/commit/9aa2cd47caa9d5558baf11b5f9b4789c1465d514
Reading xrc20 balance is trying to simulate the implementation in evm. The right way is to use "kvstore for trie".
=> [Archive Mode] 2. Fix read xrc20 balance

Dockerfile
Docker image building will fail if `logrotate` is added with `--no-cache`  option
=> [docker] fix err when installing logrotate

action/protocol/context.go, action/protocol/execution/evm/evm.go, blockchain/integrity/integrity_test.go
`receipt.ContractAddress` is intentionally designed to only record the newly created contract address, and equal to null for regular contract calls
see https://github.com/ethereum/go-ethereum/blob/7dec26db2abcb062e676fd4972abc1d282ac3ced/core/state_processor.go#L126-L129
=> Revert "[evm] add contract address into receipt (#2978)"

ioctl/newcmd/account/account.go, ioctl/newcmd/alias/aliasimport.go, ioctl/newcmd/alias/aliasremove.go
io or os is preferred as for Go1.16+
=> [ioctl/newcmd] replace ioutil  with io or os  for Go 1.16+

actpool/actqueue.go, actpool/actqueue_test.go
close #2995 
~~`heap.Remove` is not fit in this case, I use `heap.Fix` instead of it.~~
following is my bench result
```
BenchmarkHeapFixWithInit/heap.Init-8         	 5078799	       233.5 ns/op
BenchmarkHeapFixWithInit/heap.Fix-8          	16654287	        72.61 ns/op
```
=> [actpool] use heap.Remove() instead of heap.Init() in actqueue.go

ioctl/newcmd/account/account.go, ioctl/newcmd/account/accountsign.go, ioctl/newcmd/account/accountsign_test.go
close #3001 
Add `accountsign.go` and `accountsign_test.go` in `./ioctl/newcmd/account`.
=> [ioctl/newcmd] build account sign command line into new ioctl

blockchain/integrity/benchmark_test.go, testutil/file.go
Add benchmark tests for `MintBlock`, `ValidateBlock`, `CommitBlock`
Here is an example to generate test profile
```
go test -benchmem -run=^$ -bench ^BenchmarkMintBlock$  -benchtime=30s -benchmem -memprofile memprofile.out -cpuprofile profile.out -trace trace.out
```
PS: Current `testutil.CleanupPath()` is incompatible with `*testing.B` type. So CleanupPathV2 is added for benchmark tests. In the future, they can be combined to one func.
=> [test] add integrity benchmark tests 

action/actctx.go, action/action.go, action/action_test.go, action/candidate_register.go, action/claimreward.go, action/depositreward.go, action/execution.go, action/execution_test.go, action/stake_adddeposit.go, action/stake_changecandidate.go, action/stake_create.go, action/stake_reclaim.go, action/stake_restake.go, action/stake_transferownership.go, action/transfer.go, api/coreservice.go, api/grpcserver.go, api/web3server.go, api/web3server_test.go
- move *iotextypes.Execution from readContract() and estimateGas
- add SetGasLimit(), SetNonce(), SetGasPrice() to update fields in execution instead of creating new execution
- use action.CalculateIntrinsicGas() in coreService
=> [api] move protobuf input from `ReadContract()` and `estimateGas`

action/protocol/execution/evm/contract_test.go, action/protocol/execution/protocol_test.go, action/protocol/staking/candidate_buckets_indexer_test.go, action/protocol/staking/protocol_test.go, api/grpcserver_test.go, blockchain/blockdao/blockdao_test.go, blockchain/filedao/filedao_header_test.go, blockchain/filedao/filedao_legacy_test.go, blockchain/filedao/filedao_v2_test.go, blockchain/integrity/benchmark_test.go, blockchain/integrity/integrity_test.go, blockindex/bloomfilterindexer_test.go, blockindex/indexbuilder_test.go, blockindex/indexer_test.go, blocksync/blocksync_test.go, consensus/scheme/rolldpos/roundcalculator_test.go, db/counting_index_test.go, db/db_bolt_test.go, db/db_test.go, db/range_index_test.go, db/sql/sqlite3_test.go, db/trie/mptrie/merklepatriciatrie_benchmark_test.go, db/trie/mptrie/merklepatriciatrie_test.go, e2etest/local_actpool_test.go, e2etest/local_test.go, e2etest/local_transfer_test.go, server/itx/heartbeat_test.go, state/factory/factory_test.go, state/factory/patchstore_test.go
Signed-off-by: DiptoChakrabarty <diptochuck123@gmail.com>
This PR cleans up the temp files created in the tests using the CleanFileV2 function present in the testutil package of the project
Works on issue #3060
=> clean up temp files in tests using ClenFileV2

ioctl/client.go, ioctl/client_test.go, ioctl/newcmd/account/account.go, ioctl/newcmd/account/account_test.go, ioctl/newcmd/account/accountdelete.go, ioctl/newcmd/account/accountdelete_test.go, ioctl/newcmd/account/accountlist.go, ioctl/newcmd/account/accountlist_test.go, ioctl/newcmd/account/accountsign_test.go, ioctl/newcmd/account/accountupdate.go, ioctl/newcmd/account/accountupdate_test.go, test/mock/mock_ioctlclient/mock_ioctlclient.go
callers use the same default wallet dir and StandardScryptN  StandardScryptP.
=> [ioctl/newcmd] delete NewKeyStore parameteres in ioctl.Client

api/coreservice.go, api/grpcserver.go, api/grpcserver_test.go, misc/scripts/mockgen.sh, test/mock/mock_apicoreservice/mock_apicoreservice.go
1. fix mockgen.sh
2. In current implementation of TraceTransactionStructLogs, `coreservice` was referred multiple times, for `Blockchain`, `BlockDAO`, `cfg`, `StateFactory`. Introduce `SimulateExecution` interface to `CoreServcie`, and delete `StateFactory` interface.
=> Fix mockgen and delete state factory

ioctl/util/util.go
prefix for pr 3109
https://pkg.go.dev/github.com/spf13/cobra#Command.SetOutput
=> [ioctl] deprecate cmd.SetOutput

action/protocol/managers.go, action/protocol/poll/util.go, action/protocol/staking/vote_bucket.go, db/trie/mptrie/layertwoleafiterator.go, state/factory/factory.go, state/factory/factory_test.go, state/factory/statedb.go, state/factory/util.go, state/factory/workingset.go, state/iterator.go, testutil/testdb/db.go
Fix the way of reading states. The reason is that the key storing in db may not be the key on creation and the change is irreversible.
If "keys" is not set, iterate all values. If set, read values by keys.
=> [Archive Mode] 4. replace iteration with of multiple states with keysoption

blockchain/block/block_deserializer.go, blockchain/block/block_deserializer_test.go, blockchain/block/block_test.go, blockchain/block/blockstore.go, blockchain/filedao/filedao_legacy.go, chainservice/chainservice.go, consensus/scheme/rolldpos/blockproposal.go, consensus/scheme/rolldpos/endorsementmanager.go
the purpose of this PR is to minimize change to existing code like `block.ConvertFromBlockPb(), block.Deserialize()` etc.
also as zhi proposed in our earlier discussion, this deserializer will be useful when removing global `evmNetworkID` in the future
=> [block] add block deserializer

action/action.go, action/action_test.go, action/candidateregister_test.go, action/candidateupdate_test.go, action/execution_test.go, action/protocol/generic_validator.go, action/rlp_tx_test.go, action/sealedenvelope.go, action/stake_changecandidate_test.go, action/stake_transferownership_test.go, action/stakeadddeposit_test.go, action/stakecreate_test.go, action/stakereclaim_test.go, action/stakerestake_test.go, action/transfer_test.go
Verify function is now SealedEnvelope method
=> Move Verify to SealedEnvelope

action/actctx.go, action/execution_test.go, action/protocol/account/transfer.go, action/protocol/account/transfer_test.go, action/protocol/context.go, action/protocol/context_test.go, action/protocol/execution/evm/evm_test.go, action/protocol/execution/protocol.go, action/protocol/execution/protocol_test.go, action/protocol/generic_validator_test.go, action/transfer_test.go, state/factory/factory_test.go, state/factory/workingset.go
for #3096, it's not desired to add pubkey size into action struct, so add it to context (to be used at `Validate()` time)
=> [context] add public key size into ActionCtx

action/actctx.go, action/execution_test.go, action/protocol/account/transfer.go, action/protocol/account/transfer_test.go, action/protocol/context.go, action/protocol/context_test.go, action/protocol/execution/evm/evm_test.go, action/protocol/execution/protocol.go, action/protocol/execution/protocol_test.go, action/protocol/generic_validator_test.go, action/transfer_test.go, state/factory/factory_test.go, state/factory/workingset.go
This reverts commit 2a55eedfb094643439b553d0271532455511eba0.
It is verified in that all txs on chain have signature length = 65 (see func (sealed *SealedEnvelope) LoadProto(pbAct *iotextypes.Action). The original change is not needed
=> Revert "[context] add public key size into ActionCtx (#3213)"

dispatcher/dispatcher.go
Move block sync request limit position from consumer side to producer size to prevent flooding request from one neighbor.
Fixes #3228 
- Bug fix (non-breaking change which fixes an issue)
make minicluster
- Hardware:
- Toolchain:
- SDK:
=> move block sync request limit

action/protocol/execution/evm/evm.go, action/protocol/execution/evm/evm_test.go
Change the return value of `executeInEVM` from 
https://github.com/iotexproject/iotex-core/blob/5a1fe5d978d45b07446e3750a177f5fba6876e96/action/protocol/execution/evm/evm.go#L343
to 
https://github.com/iotexproject/iotex-core/blob/fcd0379b143c032a8b1cbbfa52d10a5ec674cf24/action/protocol/execution/evm/evm.go#L335
There are too many type conversions in `executeInEVM` and it's sub function `evmErrToErrStatusCode`, which can be done once in `ExecuteContract` by
https://github.com/iotexproject/iotex-core/blob/fcd0379b143c032a8b1cbbfa52d10a5ec674cf24/action/protocol/execution/evm/evm.go#L217
Fixes #3240 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for …
=> [evm] Change the type of evm statuscode from uint64 to int32

action/protocol/account/transfer.go, action/protocol/execution/evm/contract_test.go, action/protocol/execution/evm/evmstatedbadapter.go, action/protocol/staking/handlers.go, state/account.go, state/account_test.go, state/factory/factory_test.go
The return value (error) of `AddBalance` never triggered, which can be removed.
Fixes #3239 
- Hardware:
- Toolchain:
- SDK:
=> [statedb] Refactor func (st *Account) AddBalance()

ioctl/cmd/alias/aliasexport.go, ioctl/newcmd/alias/aliasexport.go, ioctl/newcmd/alias/aliasexport_test.go
Refactor `aliasexport` command in new ioctl, with the following note.
* Use [function of client interface](https://github.com/iotexproject/iotex-core/blob/master/ioctl/client.go) .
* Replace `fmt.Println` with `cmd.Println`
* [Output package](https://github.com/iotexproject/iotex-core/blob/master/ioctl/output) is deprecated. e.g. output.PrintError could be replaced with errors.Wrap.
* Global variables (config.ReadConfig config.DefaultConfigFile etc.) have been wrapped into [client interface](https://github.com/iotexproject/iotex-core/blob/master/ioctl/client.go). Please use client interface to access them if needed
Fixes #3272 
Please describe the tests that you ran to verify your changes. Provide …
=> [ioctl] Refactor aliasexport command in new ioctl

api/coreservice.go, api/coreservice_test.go, go.sum
When start height is not set or is set to 0 falsely, an error should be returned.
- Hardware:
- Toolchain:
- SDK:
=> [api] Fix correctQueryRange

action/protocol/account/transfer.go, action/protocol/account/util/util.go, action/protocol/execution/evm/contract_test.go, action/protocol/execution/evm/evmstatedbadapter.go, action/protocol/poll/util.go, action/protocol/rewarding/protocol.go, action/protocol/rewarding/reward.go, action/protocol/staking/handlers_test.go
This PR servers 2 purposes:
1. by passing in `address.Address`, it saves 1 conversion from string to `address.Address`, and also consistent with other funcs in `util.go` using `address.Address` as input
2. a small patch for the legacy address PR: https://github.com/iotexproject/iotex-core/commit/5a1fe5d978d45b07446e3750a177f5fba6876e96#diff-9c655a6b1d90598fa3fa865bf5235dd04787e0005d400508212bad3503c893a9R68-R73, see comment in transfer.go
=> [accountutil] LoadOrCreateAccount() use address.Address as input

ioctl/client_test.go, ioctl/cmd/account/account_test.go, ioctl/cmd/alias/alias_test.go, ioctl/newcmd/account/account_test.go, ioctl/newcmd/account/accountdelete_test.go, ioctl/newcmd/account/accountexport_test.go, ioctl/newcmd/account/accountexportpublic_test.go, ioctl/newcmd/account/accountlist_test.go, ioctl/newcmd/account/accountsign_test.go, ioctl/newcmd/account/accountupdate_test.go
when executing `make test`, it may be fail in newcmd/account_test.go because creating test file is removed in cmd/account_test.go ahead.
1. add os.MkdirTemp in cmd/account_test.go to distinguish tempDir names.
2. make the same processing for MkdirTemp and CleanupPath in newcmd
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for …
=> [ioctl] fix cannot open test file when make test

ioctl/cmd/account/account_test.go, ioctl/newcmd/account/account_test.go, ioctl/newcmd/account/accountcreateadd_test.go, ioctl/newcmd/account/accountdelete_test.go, ioctl/newcmd/account/accountexport_test.go, ioctl/newcmd/account/accountexportpublic_test.go, ioctl/newcmd/account/accountimport_test.go, ioctl/newcmd/account/accountlist_test.go, ioctl/newcmd/account/accountsign_test.go, ioctl/newcmd/account/accountupdate_test.go
modify NewKeyStore arguments to shorten time of make test 
Fixes https://github.com/iotexproject/iotex-core/issues/3382
- [] Test A
- [] Test B
- Hardware:
- Toolchain:
- SDK: …
=> [ioctl] modify NewKeyStore arguments to shorten time of make test

action/protocol/staking/bucket_index.go, action/protocol/staking/bucket_index_test.go, action/protocol/staking/candidate_statemanager.go, action/protocol/staking/candidate_statereader.go, action/protocol/staking/handlers.go, action/protocol/staking/handlers_test.go
=> [staking] clean up internal interface

action/action_deserializer.go, action/action_deserializer_test.go, action/envelope.go, action/envelope_test.go, action/sealedenvelope.go, action/sealedenvelope_test.go, api/coreservice.go, blockchain/block/block_deserializer.go, blockchain/block/block_deserializer_test.go, blockchain/block/blockstore.go, blockchain/block/body.go, blockchain/filedao/filedao_legacy.go, chainservice/chainservice.go, consensus/scheme/rolldpos/blockproposal.go, consensus/scheme/rolldpos/blockproposal_test.go, consensus/scheme/rolldpos/endorsedconsensusmessage.go, consensus/scheme/rolldpos/endorsedconsensusmessage_test.go, consensus/scheme/rolldpos/endorsementmanager.go, consensus/scheme/rolldpos/endorsementmanager_test.go, consensus/scheme/rolldpos/rolldpos.go, consensus/scheme/rolldpos/rolldposctx.go, consensus/scheme/rolldpos/rolldposctx_test.go, consensus/scheme/rolldpos/roundcalculator.go, consensus/scheme/rolldpos/roundcalculator_test.go, e2etest/local_transfer_test.go, ioctl/cmd/action/action.go, ioctl/util/util.go, ioctl/util/util_test.go, tools/actioninjector.v2/internal/client/client_test.go
1. in v1.8, we add a hard-fork protection to make sure all nodes accept/expose chainID at the same height
2. this protection can be removed post v1.8
=> [action] expose chainID in the transaction

api/listener.go
Fixes #(issue)
- [] make test
- [] fullsync …
=> [api] Add mutex to chainListener

api/coreservice.go, api/grpcserver.go, api/web3server.go, api/web3server_utils.go, test/mock/mock_apicoreservice/mock_apicoreservice.go
Solve `TODO` in the codebase
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- …
=> [api] Remove ActionsByBlock() in coreService

blockchain/blockchain.go, blockchain/integrity/benchmark_test.go, blockchain/integrity/integrity_test.go, chainservice/builder.go, config/config.go, consensus/scheme/rolldpos/roundcalculator_test.go, e2etest/local_test.go, e2etest/rewarding_test.go, tools/iomigrater/cmds/check-height.go, tools/iomigrater/cmds/migrate-db.go, tools/minicluster/minicluster.go
- deprecate config.Chain.CompressBlock, which is replaced by config.DB.CompressLegacy
- remove BoltDBDaoOption, which is only used in tests.
Fixes #(issue)
fix #3461 
- [] make test
- [] fullsync …
=> [blockchain] Remove BoltDBDaoOption

ioctl/newcmd/hdwallet/hdwalletcreate.go, ioctl/newcmd/hdwallet/hdwalletcreate_test.go, ioctl/newcmd/node/node.go
Refactor `hdwalletcreate` command in new `ioctl`, with the following note.
Fixes #3283
- Hardware:
- Toolchain:
- SDK:
=> [ioctl] Build hdwallet create command line into new ioctl

api/grpcserver.go, api/grpcserver_integrity_test.go, api/grpcserver_test.go, api/http.go, api/http_test.go, api/serverV2.go, api/serverV2_test.go, api/web3server_test.go, api/websocket.go
fix #3372 
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have …
=> [api] Separate Server and Server Handler

action/protocol/account/protocol_test.go, action/protocol/account/transfer_test.go, action/protocol/generic_validator_test.go, action/protocol/poll/lifelong_protocol_test.go, action/protocol/poll/staking_committee_test.go, action/protocol/rewarding/protocol_test.go, action/protocol/rewarding/reward_test.go, blockchain/block/genesis_block_test.go, blockchain/blockdao/blockdao_test.go, blockchain/filedao/filedao_legacy_test.go, blockchain/filedao/filedao_v2_test.go, blockchain/filedao/testing.go, blockchain/integrity/benchmark_test.go, blockchain/integrity/integrity_test.go, config/config.go, consensus/scheme/rolldpos/rolldposctx_test.go, consensus/scheme/rolldpos/roundcalculator_test.go, e2etest/local_test.go, ioctl/config/config.go, p2p/agent.go, p2p/agent_test.go, server/itx/heartbeat.go
- `config.Default.Genesis` is changed to `genesis.Default`
- `p2p.Network` is changed to `p2p.Config`
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I …
=> [config] Clean up config

action/protocol/poll/protocol.go, action/protocol/poll/protocol_test.go, action/protocol/rewarding/reward_test.go, actpool/actpool.go, actpool/actpool_test.go, actpool/actqueue_test.go, actpool/config.go, api/serverV2_integrity_test.go, chainservice/builder.go, config/config.go, config/config_test.go
Fixes #3513
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [config] move config.ActPool to actpool package refactor

api/grpcserver_test.go
[api] Impletment `TestGrpcServer_GetServerMeta` by gomock CoreService interface.
Fixes #3529
=> [api] impl. TestGrpcServer_GetServerMeta

ioctl/cmd/contract/contractshare.go
fix code scan#1~#6 https://github.com/iotexproject/iotex-core/security/code-scanning/6
Fixes  https://github.com/iotexproject/iotex-core/issues/3525
- [] make test
- [] fullsync
- Hardware:
- …
=> [ioctl] fix uncontrolled data used in path expression

ioctl/cmd/contract/contractshare.go
fix code scan#7~#10 https://github.com/iotexproject/iotex-core/security/code-scanning/10
Fixes https://github.com/iotexproject/iotex-core/issues/3526
- [] make test
- [] fullsync
- Hardware:
- …
=> [ioctl] fix log entries created from user input

api/grpcserver.go, api/grpcserver_test.go, chainservice/chainservice.go
delete chainid metrics in gRPC server, added in chainservice
Fixes #3489
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I …
=> move chanid metrics to chainservice

action/protocol/rewarding/protocol.go, action/protocol/staking/bucket_pool.go, action/protocol/staking/bucket_pool_test.go, action/protocol/staking/candidate_statemanager.go, action/protocol/staking/candidate_statereader.go, action/protocol/staking/handlers_test.go, action/protocol/staking/protocol.go, action/protocol/staking/protocol_test.go, action/protocol/staking/read_state.go, action/protocol/staking/vote_bucket_test.go, action/protocol/staking/vote_reviser_test.go, e2etest/native_staking_test.go
as title
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
=> [staking] unexport namespace

api/http.go, pkg/probe/probe.go, pkg/util/httputil/httputil.go, pkg/util/httputil/httputil_test.go, server/itx/server.go
similar to https://github.com/iotexproject/iotex-core/commit/0d72eb73842e17be6651169b4b8e05b4a2648504, need to fix httputil as well
Fixes #3538
- [] fullsync
=> [httputil] add ReadHeaderTimeout

ioctl/client.go, ioctl/util/util.go, tools/actioninjector.v2/internal/client/client.go, tools/actioninjector.v2/internal/cmd/inject.go
fix all [TLS MinVersion too low](https://github.com/iotexproject/iotex-core/security/code-scanning)
Fixes  https://github.com/iotexproject/iotex-core/issues/3535
- [] make test
- [] fullsync
- …
=> [ioctl] add MinVersion in tls.Config

ioctl/doc/doc.go, pkg/recovery/recovery.go
fix gosec error: [Deferring unsafe method "Close" on type "*os.File"](https://github.com/iotexproject/iotex-core/security/code-scanning/68)
Fixes   https://github.com/iotexproject/iotex-core/issues/3532
- [] make test
- [] fullsync
**Test …
=> [pkg] fix  deferring unsafe method "Close" on type "*os.File"

ioctl/client.go, ioctl/client_test.go, ioctl/cmd/account/accountcreateadd.go, ioctl/cmd/account/accountdelete.go, ioctl/cmd/action/action.go, ioctl/cmd/action/xrc20.go, ioctl/cmd/contract/contractshare.go, ioctl/cmd/hdwallet/hdwalletdelete.go, ioctl/cmd/node/nodedelegate.go, ioctl/config/configsetget.go, ioctl/flag/flag.go, ioctl/newcmd/account/accountcreateadd.go, ioctl/newcmd/account/accountcreateadd_test.go, ioctl/newcmd/account/accountdelete.go, ioctl/newcmd/account/accountdelete_test.go, ioctl/newcmd/action/action.go, ioctl/newcmd/hdwallet/hdwalletdelete.go, ioctl/newcmd/hdwallet/hdwalletdelete_test.go, ioctl/newcmd/update/update.go, ioctl/newcmd/update/update_test.go, pkg/compress/compress.go, state/account.go, test/mock/mock_ioctlclient/mock_ioctlclient.go, tools/actioninjector.v2/internal/cmd/inject.go, tools/iomigrater/cmds/migrate-db.go
fix ioctl  [Errors unhandled](https://github.com/iotexproject/iotex-core/security/code-scanning/93)
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] My code follows …
=> [ioctl] fix  Errors unhandled

blockindex/indexer.go, db/batch/batch.go, db/batch/batch_impl.go, db/batch/batch_impl_test.go, db/batch/writeinfo.go, db/batch/writeinfo_test.go, db/counting_index.go, db/db_bolt.go, db/kvstorewithbuffer.go, db/kvstorewithbuffer_test.go, test/mock/mock_batch/mock_batch.go
Fixes #3517 
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have …
=> [db] Fix variadic interface bug

blockindex/bloomfilterindexer.go, blockindex/bloomfilterindexer_test.go, blockindex/config.go, config/config.go
move config.Indexer to blockindex package
Fixes https://github.com/iotexproject/iotex-core/issues/3505
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [blockindex] move config.Indexer to blockindex package

api/listener.go, blocksync/blocksync.go, pkg/fastrand/fastrand.go, pkg/fastrand/fastrand_test.go
fix weak random in  api and blocksync
Fixes  https://github.com/iotexproject/iotex-core/issues/3537
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> fix Use of weak random number generator

go.mod, go.sum, p2p/agent.go
It takes a large amount of time for the host to find peers in a large p2p network (`host.FindPeers(ctx)`). Therefore, this peer finding action is changed to an asynchronous one which wouldn't block the main thread to start host's p2p component
Fixes #(issue)
tests are updated in https://github.com/iotexproject/go-p2p/pull/35 …
=> [p2p] Fix p2p agent start

action/action_deserializer.go, action/protocol/execution/evm/evm.go, action/protocol/vote/probationlist.go, actpool/actpool.go, api/blocklistener.go, api/coreservice.go, api/grpcserver.go, api/grpcserver_test.go, api/types/types.go, api/web3server.go, api/web3server_integrity_test.go, api/web3server_marshal.go, api/web3server_marshal_test.go, api/web3server_utils.go, blockchain/block/block_deserializer.go, blockchain/blockchain.go, consensus/scheme/rolldpos/endorsementmanager.go, go.mod, ioctl/cmd/action/stake2.go, ioctl/cmd/action/xrc20.go, pkg/fastrand/fastrand.go, test/mock/mock_apicoreservice/mock_apicoreservice.go, tools/executiontester/blockchain/erc721_token.go
- Two deprecated methods `BlockMetas` and `BlockMetaByHash` are replaced with `BlockByHeightRange`, `BlockByHeight` and `BlockByHash`
- Old `getBlockResult` struct is removed 
- [] make test
- [] fullsync
- Hardware:
- Toolchain: …
=> [api] Remove iotextypes.BlockMeta from coreservice

config/config.go
HTTPAdminPort is opened for `pprof` server, which should be disable by default
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [Config] Disable http admin by default

dispatcher/dispatcher.go
replace `msgType, err := goproto.GetTypeFromRPCMsg(message)` with `switch (msg).(type) {}`
Fixes #3575
- Firmware version: macOS Monterey arm64
- Hardware:
- Toolchain:
- SDK:
=> HandleBroadcast use message.(type) directly

ioctl/newcmd/action/stake2withdraw.go, ioctl/newcmd/action/stake2withdraw_test.go
Build `stake2withdraw` command in new `ioctl`, with the following note.
Fixes #3333 
- Hardware:
- Toolchain:
- SDK:
=> [ioctl] Build stake2 withdraw command line into new ioctl

action/protocol/execution/evm/contract_test.go, action/protocol/execution/evm/evmstatedbadapter_test.go, action/protocol/poll/governance_protocol_test.go, action/protocol/poll/staking_committee_test.go
#3504 pre-fix, for resolve import cycle
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> remove config in evm and pool

action/protocol/staking/candidate_statereader.go
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have …
=> [action]  nil point check  in candidate_statereader

action/protocol/execution/evm/evm.go, action/protocol/execution/evm/evm_test.go, go.mod, go.sum
EIP3198 is enabled in London EVM, which accesses `evm.Context.BaseFee`. See https://github.com/ethereum/go-ethereum/commit/94451c2788295901c302c9bf5fa2f7b021c924e2#diff-c21870801ba3133fda5991da046fbfd0f83999bda1008a4af84affca83ec5eb9R171
Fixes #(issue)
=> [evm] support opBasefee

Makefile, db/config.go, db/db_bolt.go, tools/readtip/main.go
Create a tool to read tip of state db
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> tool to read tip of state db

db/counting_index.go
When testing the analyser, it was found that db counting_index.go has a data race
```
==================
WARNING: DATA RACE
Write at 0x00c000127e60 by goroutine 36:
github.com/iotexproject/iotex-core/db.(*countingIndex).addBatch()
/home/millken/.gvm/pkgsets/go1.18.6/global/pkg/mod/github.com/iotexproject/iotex-core@v1.8.3-rc4/db/counting_index.go:140 +0x3fa
github.com/iotexproject/iotex-core/db.(*countingIndex).Add()
/home/millken/.gvm/pkgsets/go1.18.6/global/pkg/mod/github.com/iotexproject/iotex-core@v1.8.3-rc4/db/counting_index.go:118 +0x77e
github.com/iotexproject/iotex-core/blockchain/filedao.addOneEntryToBatch()
/home/millken/.gvm/pkgsets/go1.18.6/global/pkg/mod/github.com/iotexproject/iotex-core@v1.8.3-rc4/blockchain/filedao/filedao_v2_util.go:126 +0xa4 …
```
=> [db]fix counting_index data race

action/protocol/protocol.go, action/protocol/staking/builder.go, action/protocol/staking/candidate_center.go, action/protocol/staking/candidate_center_extra.go, action/protocol/staking/candidate_statemanager.go, action/protocol/staking/candidate_test.go, action/protocol/staking/handlers.go, action/protocol/staking/handlers_test.go, action/protocol/staking/patchstore.go, action/protocol/staking/patchstore_test.go, action/protocol/staking/protocol.go, action/protocol/staking/protocol_test.go, action/protocol/staking/validations_test.go, action/protocol/staking/vote_reviser_test.go, blockchain/config.go, chainservice/builder.go, db/db_bolt_test.go, state/factory/factory.go, state/factory/statedb.go, state/factory/util.go, state/factory/workingset.go
=> [staking] persist cand center to statedb and patchfile

action/protocol/staking/handlers.go
as title
Fixes #(issue)
- [] fullsync
=> [staking] save owner list after PersistStakingPatchBlock

ioctl/newcmd/did/diddoc.go, ioctl/newcmd/did/didgenerate.go, ioctl/newcmd/did/didgenerate_test.go
Refactor `didgenerate` command in new `ioctl`, with the following note.
Fixes #3290 
- Hardware:
- Toolchain:
- SDK:
=> [ioctl] Build did generate command line into new ioctl

ioctl/newcmd/action/actionsendraw.go, ioctl/newcmd/action/actionsendraw_test.go
Refactor `actionsendraw` command in new `ioctl`, with the following note.
Fixes #3322 
- Hardware:
- Toolchain:
- SDK:
=> [ioctl] Build action sendraw command line into new ioctl

ioctl/newcmd/action/actionread.go, ioctl/newcmd/action/actionread_test.go
Refactor `actionread` command in new `ioctl`, with the following note.
Fixes #3321 
- Hardware:
- Toolchain:
- SDK:
****
=> [ioctl] Build action read command line into new ioctl

tools/readtip/main.go
Fixes #(issue)
- [] make test
- [] fullsync …
=> fix read tip tool bug

ioctl/newcmd/did/didderegister.go, ioctl/newcmd/did/didderegister_test.go, ioctl/newcmd/did/didgethash.go, ioctl/newcmd/did/didgeturi.go, ioctl/newcmd/did/didregister.go
Refactor `didderegister` command in new `ioctl`, with the following note.
Fixes #3667  
- Hardware:
- Toolchain:
- SDK:
****
=> [ioctl] Build did deregister command line into new ioctl

ioctl/newcmd/action/actiondeposit.go, ioctl/newcmd/action/actiondeposit_test.go, ioctl/newcmd/action/actiontransfer.go, ioctl/newcmd/action/stake2withdraw.go, ioctl/newcmd/action/xrc20transferfrom.go
Refactor `actiondeposite` command in new `ioctl`, with the following note.
Fixes #3318  
- Hardware:
- Toolchain:
- SDK:
****
=> [ioctl] Build action deposit command line into new ioctl

ioctl/newcmd/action/actionclaim.go, ioctl/newcmd/action/actionclaim_test.go
Refactor `actionclaim` command in new `ioctl`, with the following note.
Fixes #3316 
- Hardware:
- Toolchain:
- SDK:
****
=> [ioctl] Build action claim command line into new ioctl

action/protocol/staking/candidate_statereader.go, action/protocol/staking/candidate_statereader_test.go, action/protocol/staking/protocol.go, api/grpcserver_integrity_test.go, ioctl/newcmd/action/action_test.go
as title
Fixes #(issue)
- [] fullsync
=> [staking] remove unnecessary call from GetStakingStateReader

action/protocol/context.go, action/protocol/rewarding/reward.go
for safety, use HF to gate the position of this error check.
After HF, this gating can be removed (that is, with the error check moved to correct position)
Fixes #(issue)
- [] fullsync
=> [rewarding] fix error check position

action/protocol/execution/evm/evmstatedbadapter.go, action/protocol/execution/evm/evmstatedbadapter_test.go, api/web3server.go, go.mod, go.sum
=> [evm] proper handle refundSnapshot and upgrade go-ethereum release

api/coreservice.go, gasstation/gasstattion.go, gasstation/gasstattion_test.go, ioctl/cmd/action/stake2add.go
Change `cfg` field type in `GasStation` from `config.API` to `config.GasStation`.
Fixes #3718
- Firmware version: macOS Monterey 12.5.1
- Hardware: Apple M1 Pro
- Toolchain:
- SDK:
=> use config.GasStation instead of config.API

api/config.go, api/coreservice.go, api/coreservice_test.go, api/grpcserver_integrity_test.go, api/serverV2.go, api/serverV2_integrity_test.go, api/web3server_integrity_test.go, chainservice/chainservice.go, config/config.go, gasstation/config.go, gasstation/gasstattion.go, gasstation/gasstattion_test.go
In order to refactor config.API, the main modifications are:
- move config.GasStation to gasstation package
- move config.API to api package
- refactor unit test of api and gasstation package to remove dependencies on config package
Fixes #3722
- Firmware version: macOS Monterey 12.5.1
- Hardware: Apple M1 Pro
- Toolchain:
- SDK:
=> [config] move config.API to api package

Dockerfile, Makefile, hooks/build
A long term solution to solve getting version info failed when building docker image on DockerHub:
- `PACKAGE_VERSION`, `PACKAGE_COMMIT_ID`, `GIT_STATUS` are supported by env variable in Makefile
- add `PACKAGE_VERSION`, `PACKAGE_COMMIT_ID`, `GIT_STATUS` three args in Dockerfile
- add hooks to replace default docker build command  on DockerHub
Fixes #3746
- [] trigger docker build on DockerHub 
- Hardware:
- Toolchain:
- SDK:
=> update docker build command

README.md, crypto/README.md
=> Fix: typos

config/config.go, server/main.go
missing in commit https://github.com/iotexproject/iotex-core/pull/3634/commits/d485731c264fa650f93ae180cd2f76bbda018c1f#
Fixes #3634 
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have …
=> [config]Fix missing config MptrieLogPath

db/batch/writeinfo.go
Fixes #(issue)
- [] make test
- [] fullsync …
=> [db] Optimize memory relocation in writeinfo

api/grpcserver_integrity_test.go, blockchain/block/block.go, blockchain/block/header.go, blockchain/block/header_test.go
refer #3770 
Fixes #3770
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [block] deprecate ConvertToBlockHeaderPb()

state/factory/factory_test.go, state/factory/workingset.go
fix #3555 
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have …
=> [state] Remove receipt checking after runAction

ioctl/newcmd/contract/contract.go, ioctl/newcmd/contract/contract_test.go, ioctl/newcmd/contract/contracttestfunction.go, ioctl/newcmd/contract/contracttestfunction_test.go, ioctl/newcmd/contract/parse.go, ioctl/newcmd/contract/parse_test.go, ioctl/newcmd/contract/test.abi
Build contracttestfunction command in new ioctl, with the following note.
- Use [client interface](https://github.com/iotexproject/iotex-core/blob/master/ioctl/client.go) to construct the Cobra command.
- Output package is deprecated, replace it with errors package.
- Replace fmt.Println with cmd.Println
- Refactor unit test to cover the modification.
Fixes #3315 
- Firmware version: macOS Monterey
- Hardware: Apple M1 Pro
- Toolchain:
- SDK:
=> [ioctl] build contract test function command line into new ioctl

action/protocol/context.go, chainservice/builder.go, e2etest/nodeinfo_test.go, go.mod, go.sum, nodeinfo/config.go, nodeinfo/manager.go, nodeinfo/manager_test.go, test/mock/mock_nodeinfo/mock_manager.go
- Implement the isDelegate logic in nodeinfo package
- Add feature enable switch for nodeinfo
- Hardware:
- Toolchain:
- SDK:
=> implement isDelegate() in nodeinfo

api/config.go, api/serverV2.go, api/serverV2_test.go, api/web3server.go, api/web3server_integrity_test.go, api/web3server_test.go
add limit for batch request，`DefaultBatchRequestLimit` = 100, when the batch size exceeds the threshold, an error `batch too large` will be returned.
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [API] add limit batch request for web3 API

action/protocol/context.go, blockchain/integrity/benchmark_test.go, blockchain/integrity/integrity_test.go, state/factory/workingset.go, testutil/timestamp_test.go
backport haixiang's fix to master branch
Fixes #(issue)
- Hardware:
- Toolchain:
- SDK:
=> fix test and speedup validation

ioctl/cmd/did/common.go, ioctl/cmd/did/did.go, ioctl/cmd/did/didserviceadd.go, ioctl/cmd/did/didserviceremove.go
Add ioctl command for DID service
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
=> [ioctl] add did service command

action/protocol/context.go, action/protocol/rewarding/reward.go
for safety, the change is protected by hard-fork. Now that the hard-fork has passed, can remove the gating check
Fixes #(issue)
- Hardware:
- Toolchain:
- SDK:
=> [context] remove FixRewardErroCheckPosition flag

action/protocol/context.go, go.mod, state/factory/workingset.go
starting v1.10 hard-fork, the network can safely accept claim action in web3 format. the gating check can be removed
Fixes #(issue)
- [] make test
- Hardware:
- Toolchain:
- SDK:
=> [context] remove EnableWeb3Rewarding flag

action/protocol/context.go, action/protocol/staking/protocol_test.go, action/protocol/staking/staking_statereader_test.go, api/coreservice.go, blockchain/genesis/genesis.go, blockchain/genesis/heightupgrade_test.go, config/config.go, config/config_test.go, e2etest/local_transfer_test.go, state/factory/workingset.go, state/factory/workingset_test.go
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
=> [config] enforce correct chainID and enable IIP-13 at Quebec height

blockchain/genesis/genesis.go, blockindex/contractstaking/indexer.go, blockindex/contractstaking/indexer_test.go, chainservice/builder.go, e2etest/contract_staking_test.go
To optimize the startup check of the contract indexer, the main changes are as follows:
- implement the `StartHeight()` method to prepare to join the `BlockIndexerWithStartGroup` introduced in #3869 
- ignore blocks with a height lower than the deployment height of the contract when processing PutBlock.
Fixes #(issue)
- [] fullsync
- …
=> [IIP-13] contract indexer ignore blocks lower than height of contract deployment

blockindex/contractstaking/dummy_indexer.go, blockindex/contractstaking/indexer.go, blockindex/sgd_indexer.go
Fixes #(issue)
- [] make test
- [] fullsync …
=> fix PutBlock will still execute when the block height is less than startheight

blockindex/contractstaking/indexer.go, blockindex/contractstaking/indexer_test.go, chainservice/builder.go, e2etest/contract_staking_test.go
validate address when `NewContractStakingIndexer`
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
=> validate address of contract indexer

action/protocol/staking/candidate_buckets_indexer.go, action/protocol/staking/candidate_buckets_indexer_test.go, action/protocol/staking/protocol.go, action/protocol/staking/staking_statereader.go
fix two bugs on `readStateCandidates`:
- return nothing due to zero height
- miss hard-fork for Quebec
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
=> [staking] fix readStateCandidates returning empty

action/protocol/staking/candidate_statereader.go, blockindex/contractstaking/cache.go, blockindex/contractstaking/indexer_test.go
Currently, in the composite staking code, we make separate calls to `ReadStateBucketByIndices` for native and contract buckets. The desired behavior is to be able to look up a bucket by its ID in either the native or contract buckets. However, the current implementation returns an error if the ID does not exist in either bucket, resulting in an error even if the ID exists in one of them. 
The modification to make is changing the behavior of `ReadStateBucketByIndices` for native and contract buckets. Instead of returning an error when there are non-existing IDs in the parameters, we will modify it to return the existing buckets.
The reasons for choosing this approach are twofold:
- Simple: the modification is relatively simple, which allows for a straightforward implementation without …
=> [api] ReadStateBucketByIndices return existing buckets

blockindex/contractstaking/event_handler.go, blockindex/contractstaking/indexer_test.go, e2etest/contract_staking_test.go
Currently, only the transfer events triggered during the creation of a bucket are being handled. The transfer events triggered during subsequent bucket transfers are not being handled correctly.
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- …
=> [contract_indexer] fix transfer event handling

action/protocol/staking/contractstake_bucket_type.go, blockindex/contractstaking/bucket_info.go, blockindex/contractstaking/cache.go, blockindex/contractstaking/cache_test.go, blockindex/contractstaking/delta_cache.go, blockindex/contractstaking/delta_cache_test.go, blockindex/contractstaking/delta_state.go, blockindex/contractstaking/delta_state_test.go, blockindex/contractstaking/dirty_cache.go, blockindex/contractstaking/dirty_cache_test.go, blockindex/contractstaking/event_handler.go, blockindex/contractstaking/indexer.go, blockindex/contractstaking/indexer_test.go
The issue is that when `changeDelegate` is called on a bucket, the votes of the old delegate are not reduced.
The issue is caused by two factors: 
1. not remove the bucket of the old candidate from the `candidateBucketMap`
2. the `cache` read operations return a pointer, which means that the clean cache may have already been updated before the `merge`.
pre-required: #3887 
Fixes #(issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. …
=> [contractstaking]fix vote bug when change delegate

blockindex/contractstaking/cache.go, blockindex/contractstaking/cache_test.go, blockindex/contractstaking/indexer.go, blockindex/contractstaking/indexer_test.go
improve code robustness according to new comments in #3888 
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
=> [contractstaking] improve robustness

ioctl/cmd/bc/bc.go, ioctl/cmd/bc/bcdelegate.go, ioctl/cmd/node/nodedelegate.go
`ioctl node delegate` gives the delegates list of a certain epoch, but not every delegate's detailed info.
add a `ioctl bc delegate` command, like below:
```
./bin/ioctl bc delegate cpc --endpoint=api.iotex.one:443
{
name: cpc
ownerAddress: io1smh0a4ms9fc5p8v9h9l7ffgkekv032hzsdkr9a
operatorAddress: io16fknjsnhj6m5x2fawu5tqfrk6pr9r9xyz489vk
rewardAddress: io12mgttmfa2ffn9uqvn0yn37f4nz43d248l2ga85
totalWeightedVotes: 68963450.120222472655746524
selfStakeBucketIdx: 12
selfStakingTokens: 2975349.881825114451272576 IOTX
}
```
Fixes #(issue)
- [] This …
=> [ioctl] add bc delegate command

blockchain/genesis/genesis.go
as title
Fixes #(issue)
- [] fullsync
=> [iip-13] set mainnet contract address and height

chainservice/builder.go
as title
Fixes #(issue)
- [] fullsync
=> [chainservice] check SystemStakingContract and SystemSGDContract address

action/protocol/execution/evm/evm_test.go, blockchain/genesis/genesis.go, blockchain/genesis/heightupgrade_test.go
ast title
Fixes #(issue)
- [] fullsync
=> [genesis] set Quebec to activate at 07-20-2023 11pm UTC

action/candidate_register.go, action/candidate_update.go, action/candidateregister_test.go, action/candidateupdate_test.go, pkg/recovery/recovery.go
as title, issue found and reported by Jeremi
Fixes #3909 
- [] fullsync
=> [staking] fix ToEthTx() panic

api/websocket.go, pkg/recovery/recovery.go
as title
Fixes #3907
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> fix panic: concurrent write to websocket connection

action/builder.go, action/builder_test.go, action/candidate_register.go, action/candidate_update.go, action/claimreward.go, action/claimreward_test.go, action/depositreward.go, action/depositreward_test.go, action/protocol/rewarding/protocol_test.go, action/protocol/staking/protocol_test.go, action/receipt.go, action/stake_adddeposit.go, action/stake_changecandidate.go, action/stake_create.go, action/stake_reclaim.go, action/stake_restake.go, action/stake_transferownership.go
noticed this while working on #3910
Fixes #(issue)
- [] fullsync
=> [action] simplify address generation

ioctl/util/util.go
as title, this changes is not only `action transfer`, other commands will be supported
Fixes #3901 
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [ioctl] action transfer supports 0x address 

api/web3server.go, api/web3server_marshal.go
This PR is part of PR #3921 about issue #3821
Fixes #3821
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have commented my code, particularly …
=> [api] fix revert message in eth_call

action/protocol/staking/contractstake_indexer.go, action/protocol/staking/contractstake_indexer_mock.go, action/protocol/staking/protocol.go, action/protocol/staking/protocol_test.go, action/protocol/staking/staking_statereader.go, action/protocol/staking/staking_statereader_test.go, blockindex/contractstaking/cache.go, blockindex/contractstaking/cache_test.go, blockindex/contractstaking/dirty_cache.go, blockindex/contractstaking/indexer.go, blockindex/contractstaking/indexer_test.go, e2etest/contract_staking_test.go
Motivation:
Strictly limiting the blocks during PutBlock can avoid block skipping issues
Specifying the height during queries can help detect errors in the indexer at an earlier stage
Fixes #(issue)
- [] fullsync
- Hardware:
- …
=> [blockindex] restrict height for contract_staking_indexer during read operation

action/protocol/execution/evm/evm.go, blockindex/sgd_indexer.go, blockindex/sgd_indexer_test.go, e2etest/sgd_registry_test.go
Motivation:
- Strictly limiting the blocks during PutBlock can avoid block skipping issues
-  Specifying the height during queries can help detect errors in the indexer at an earlier stage
Fixes #(issue)
- [] fullsync
- Hardware: …
=> [blockindex] restrict height for sgdindexer during write and read operation

blockindex/contractstaking/indexer.go, blockindex/contractstaking/indexer_test.go, blockindex/sgd_indexer.go, blockindex/sgd_indexer_test.go
After #3926 and #3927 , read interface of the two indexers will return invalid height error at feature hard-fork height. They should return empty result when block between hard-fork and contract deploy height, instead of invalid height error.
Fixes #(issue)
- [] fullsync …
=> [blockindex] return empty result when contract not deployed

action/protocol/context.go, action/protocol/staking/contractstake_indexer.go, action/protocol/staking/contractstake_indexer_mock.go, action/protocol/staking/protocol.go, action/protocol/staking/protocol_test.go, action/protocol/staking/staking_statereader.go, action/protocol/staking/staking_statereader_test.go, action/protocol/staking/vote_bucket.go, action/protocol/staking/vote_bucket_test.go, action/protocol/staking/vote_reviser.go, action/protocol/staking/vote_reviser_test.go, blockindex/contractstaking/bucket.go, blockindex/contractstaking/cache.go, blockindex/contractstaking/cache_test.go, blockindex/contractstaking/delta_cache.go, blockindex/contractstaking/dirty_cache_test.go, blockindex/contractstaking/indexer.go, blockindex/contractstaking/indexer_test.go, chainservice/builder.go, e2etest/contract_staking_test.go
Currently, the IIP-13 `contract staking bucket` does not take into account the impact of the `staking duration` and `stake-lock` when **calculating the voting power.** It only considers the amount of IOTX staked. However, it should actually use the similar voting logic as the `native staking bucket`.
It's a hard-fork at `RedseaBlockHeight`.
- [] fullsync
- [] Other test (please …
=> [staking] fix weighted votes of contract staking bucket

action/protocol/context.go, action/protocol/execution/evm/evm_test.go, blockchain/genesis/genesis.go, blockchain/genesis/heightupgrade_test.go
As discussed, set up the v1.12 release target time
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
=> [genesis] set Redsea to activate at 11-05-2023 23:59pm UTC

action/protocol/execution/evm/evm.go
To ensure easier code maintenance in EVM, the `Params` struct is used internally to access the required parameters.
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [evm] refactor evm parameters

pkg/util/blockutil/block_time_calculator.go, pkg/util/blockutil/block_time_calculator_test.go
There are several reasons for introcuding block time calculator: 
- After the Shanghai upgrade of Ethereum, hard-fork judgment is now based on timestamps. We need to convert specified block heights into timestamps. 
- When calculating the votes for NFT Bucket, we need to convert block numbers into staking times. 
- We need a unified calculation method that takes into account the variation of BlockInterval.
It calculates the corresponding time for a given height. It supports accurate querying of historical blocks as well as prediction for future blocks. The prediction for future blocks is calculated based on the latest height and block interval.
Fixes #(issue)
- [] Code refactor or …
=> [util] implement block time calculator

action/rlp_tx.go, action/rlp_tx_test.go, action/sealedenvelope.go, api/web3server_integrity_test.go, api/web3server_marshal_test.go, api/web3server_test.go, api/web3server_utils.go
Small pre-requisite code change to make (#3965) easier.
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
=> [action] add NewEthSigner() and pass Signer as input to rlpRawHash() and rlpSignedHash()

action/protocol/execution/evm/evmstatedbadapter.go
In the Shanghai upgrade of EVM, there have been changes to the [StateDB Interface](https://github.com/ethereum/go-ethereum/blob/v1.11.5/core/vm/interface.go#L28), therefore the StatedbAdapter also needs to be modified accordingly.
The modified parts of the new StateDB Interface are as follows:
```
PrepareAccessList(sender common.Address, dest *common.Address, precompiles []common.Address, txAccesses types.AccessList)
```
=>
```
GetTransientState(addr common.Address, key common.Hash) common.Hash
SetTransientState(addr common.Address, key, value common.Hash)
Prepare(rules params.Rules, sender, coinbase common.Address, dest *common.Address, precompiles []common.Address, txAccesses types.AccessList)
```
Among them, `GetTransientState` and `SetTransientState` are prepared for EIP-1153, but …
=> [evm] Add methods for StatedbAdapter

ioctl/config/config.go, ioctl/config/configsetget.go, ioctl/newcmd/config/config.go, ioctl/newcmd/config/config_test.go
add config for znode commands
Fixes #3982 
=> feat(ioctl): add znode commands configs

action/protocol/context.go, action/protocol/execution/protocol.go, action/protocol/execution/protocol_test.go
After activating EIP-3860: Limit and meter initcode in the Shanghai upgrade, the limit on the initcode size was increased to 48KB in evm. Currently, we have a limit of 32KB on execution action size. To be compatible with this change in Ethereum, we propose to raise the limit size up to 48KB.
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [action] Increase Execution Size Limit to 48K

api/coreservice.go, api/coreservice_test.go, api/grpcserver.go
The gas price passed in actually does not affect the result of estimateGas (which only depends on gasConsumed). However, it may cause the API to return an error, such as insufficient balance. 
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- …
=> [api] fix estimateGas API error when passing gasPrice parameter

api/grpcserver.go
If a client is idle for 5 minutes, grpc server send a GOAWAY to terminate the connection
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have added tests that prove my fix is effective or that my feature …
=> [grpc] Set MaxConnectionIdle to 5 min

action/candidate_activate.go, action/candidate_selfstake.go
As a part of implementation of #3981 , this pr defines the `CandidateSelfStake` action struct to make a candidate re-selfstaked
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have added tests …
=> [action] Define CandidateSelfStake Action

ioctl/cmd/ws/wsmessage.go
upgrade w3bstream message query api
Fixes #(issue)
=> feat(ioctl): upgrade ws apis

actpool/actpool.go, actpool/config.go
Fixes #(issue)
- [] make test
- [] fullsync …
=> [actpool] fix typo for worker queue

ioctl/cmd/ws/ws.go, ioctl/cmd/ws/wsproject.go, ioctl/config/config.go, ioctl/config/configsetget.go, ioctl/newcmd/config/config.go, ioctl/newcmd/config/config_test.go
project register contract address config
Fixes #(issue)
=> feat(ioctl): project register contract addr config

action/protocol/execution/evm/evm.go, action/protocol/execution/evm/evmstatedbadapter.go
In the EVM forget to check one error. This is protected by a hard-fork flag, now the hard-fork has passed and this flag can be removed
Fixes #(issue)
- Hardware:
- Toolchain:
- SDK: …
=> [evm] remove NotCheckPutStateErrorOption()

action/protocol/staking/bucket_validation.go, action/protocol/staking/bucket_validation_test.go
introduce batch of util functions to validate a bucket, reducing redundant code
Fixes #(issue)
- Hardware:
- Toolchain:
- SDK:
- [] New and existing unit tests pass locally with my …
=> [refactor] Add bucket validation util functions

ioctl/cmd/ws/wsproject.go
use CID as project config url, instead of gateway http url
Fixes #(issue)
=> feat(ioctl): use ipfs cid as project config url

action/protocol/staking/handler_candidate_selfstake.go, action/protocol/staking/handler_candidate_selfstake_test.go, action/protocol/staking/protocol.go
`CandidateSelfStake` action accept a bucket as the self-stake bucket of the sender's candidate. The bucket can be:
- sender's bucket with enough amount
- a bucket endorsed to the candidate
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [staking] Handling CandidateSelfStake Action

action/protocol/staking/candidate.go, action/protocol/staking/candidate_center.go, action/protocol/staking/candidate_center_test.go
Due to the introduction of CandidateRegister without staking, there will occur candidate which lack staking and updates in self-staking bucket. However, the current `CandidateCenter` does not support these operations. This PR aims to resolve these issues.
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have …
=> [staking] CandidateCenter Support for Missing and Changes of Self-Stake Bucket

action/candidate_endorsement.go, action/protocol/staking/handler_candidate_endorsement.go, action/protocol/staking/handler_candidate_endorsement_test.go, action/protocol/staking/protocol.go, blockchain/genesis/genesis.go, pkg/util/byteutil/byteutil.go
Implement action handling for `CandidateEndorsement`
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] New and …
=> [staking] Handling CandidateEndorsement Action

action/protocol/execution/protocol.go, action/protocol/execution/protocol_test.go
follow the same behavior as Ethereum.
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [action] check calldata size instead of total size for 48kB init code limit

api/web3server_test.go
Fixes #4116 
- [] make test
- [] fullsync
- …
=> feat(test): add web3server unit test

actpool/actioniterator/actioniterator_test.go
Fixes #4106 
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [test] Add test for actionByPrice

blockindex/sgd_indexer.go
Reduce unnecessary hash calculations and memory allocation, remove unused code
Fixes #4147
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have performed a self-review …
=> sgdIndexer performance improvement

action/rlp_tx_test.go, actpool/actioniterator/actioniterator_test.go
Increase test coverage
Fixes #4104
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> update tests for rlp_tx.go

blockindex/contractstaking/cache.go, blockindex/contractstaking/cache_test.go
=> test(contractstaking): add unit tests

actpool/actqueue.go, actpool/queueworker.go
the nonce of queue whose account is legacy fresh isn't updated by `PendingNonceConsideringFreshAccount()` after `UseZeroNonceForFreshAccount` is activated
Fixes #4156 
- [] make test
- [] fullsync …
=> fix bug in worker.Reset()

db/batch/batch_impl.go, db/batch/kv_cache.go, db/batch/kv_cache_test.go
Reduced the computation of map keyhash, reduced `keyCacheValue` memory allocation, Mintblock time dropped by half, this PR has been tested on nightly
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] My code …
=> [db] ResetSnapshots() performance improvement

action/protocol/context.go, action/protocol/staking/bucket_validation.go, action/protocol/staking/bucket_validation_test.go, action/protocol/staking/handler_candidate_endorsement.go, action/protocol/staking/handler_candidate_endorsement_test.go, action/protocol/staking/handler_candidate_selfstake.go, action/protocol/staking/handler_candidate_selfstake_test.go, action/protocol/staking/handlers.go, action/protocol/staking/protocol.go, action/protocol/staking/protocol_test.go
Due to the introduction of endorsement, the `SelfStakeBucketIndex` field of the Candidate will not be reset between expiration and the next bucket action. Therefore, the `ContainsSelfStakingBucket` function returns true no longer to indicate whether the bucket is a valid self-stake bucket. As a result, this PR introduces a new private function `isSelfStakeBucket` to achieve this functionality.
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [staking] Replace ContainsSelfStakingBucket with isSelfStakeBucket

action/protocol/execution/evm/transient_storage.go, action/protocol/execution/evm/transient_storage_test.go
add `transientStorage` struct. next PR will implement EIP1153 transient storage in EVM
refer to Ethereum's implementation: https://github.com/ethereum/go-ethereum/pull/26003/files#diff-881df080822cc037890983e168ea0f004c9ebe26a87df47867436b415e234604
Fixes #(issue)
- [] fullsync
- …
=> [evm] add transientStorage struct

db/batch/batch_impl.go
`ResetSnapshots` occupies almost half of the time of `MintBlock` under high TPS, so we need to optimize it. 
Currently, `ResetSnapshot` is called after each action is processed, but in most cases, the number of snapshots is only 1. In this case, performing `ResetSnapshot` is not very meaningful, so we have changed it to only reset when the snapshot count exceeds 10. 
Why choose 10? This threshold will lead to too many calls of `ResetSnapshot` if it's too small, resulting in waste; a threshold that is too large may cause a significant impact on the kv read/write performance due to too many snapshots. When the threshold is set to 10, the time of `ResetSnapshots` decreases from 1s to 100ms, and the MintBlock time decreases from 2.2s to 1.3s, which is acceptable
Please delete options that are …
=> [db] Reset only if Snapshots exceed size of 10

db/db_bolt.go
In the scenario of 500 TPS, the `CommitBlock` time is relatively long (2~3s), and most of the time is spent on db.WriteBatch, requiring optimization. 
After testing and analysis, there are many duplicate redundant operations in WriteBatch (2w operations for only 6~8k keys). Therefore, before executing the write operation of db, we deduplicate the keys, keeping only the last operation for each key.
Ultimately, the `CommitBlock`  time was optimized to around 200ms.
- Hardware:
- Toolchain:
- SDK:
=> [db] Remove duplicate keys when WriteBatch

action/protocol/staking/bucket_validation.go, action/protocol/staking/bucket_validation_test.go, action/protocol/staking/handler_candidate_endorsement_test.go, action/protocol/staking/handlers.go
After delegate endorsement introduced, we cannot unstake bucket if it's a endorse bucket.
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have added tests that prove my fix is effective or that my feature …
=> [staking] Cannot Unstake if Bucket is Endorsed

ioctl/cmd/node/nodedelegate.go, ioctl/cmd/node/nodereward.go
Improve user experience, you can use `ioctl node reward unclaimed cobo` to query  without input the address.
Fixes #4149
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [ioctl]node reward unclaimed support name query

action/protocol/staking/handlers.go, action/protocol/staking/handlers_test.go, go.mod, go.sum, go.test.sh
Fix a typo error. It's not a hard-fork for the bug has not been released
- Hardware:
- Toolchain:
- SDK:
- [] Any …
=> [staking] Fix typo error

action/protocol/poll/nativestakingV2.go, action/protocol/staking/candidate_statemanager.go, action/protocol/staking/candidate_statereader.go, action/protocol/staking/handlers_test.go, action/protocol/staking/protocol.go
Since the `SelfStake` field of a `Candidate` is not cleared when an endorsement expires, the current `ActiveCandidate` function does not remove expired candidates. This PR is aimed at fixing this issue.
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] …
=> [staking] ActiveCandidate Exclude Candidate with Expired Endorsement

action/candidate_register.go, action/protocol/context.go, action/protocol/staking/handlers.go, action/protocol/staking/handlers_test.go, action/protocol/staking/validations.go, action/signedaction.go, e2etest/native_staking_test.go
We expanded the action `CandidateRegister` to support registration without staking. However, in the absence of self-staking, they will not be selected as consensus nodes.
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] My changes generate no new …
=> [staking] Candidate Register without Staking

api/coreservice.go
message batcher batches actions together and send in one shot to improve p2p network efficiency. It is gated to enable at an earlier hard-fork height. Now that hard-fork has passed, so we can remove the height check
Fixes #(issue)
- [] make test
- [] fullsync
**Test …
=> [api] remove height check for message batcher

action/protocol/context.go, action/protocol/execution/evm/evm.go, action/protocol/execution/evm/evmstatedbadapter.go, action/protocol/execution/evm/evmstatedbadapter_test.go, action/protocol/execution/evm/testdata_test.go
When `Suicide()` is called upon destruction, the contract's balance will be transferred to a beneficiary. This needs to be captured in a transaction log  
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [evm] add transaction log for Suicide()

action/protocol/execution/evm/evm.go, action/protocol/poll/consortium.go, action/protocol/poll/staking_committee.go, api/coreservice.go, blockchain/blockchain.go, blockchain/blockdao/blockindexer.go, blockchain/genesis/genesis.go, blockchain/genesis/genesis_test.go, gasstation/gasstattion.go, state/factory/factory.go, state/factory/statedb.go
as title.
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have …
=> [genesis] raise block gas limit to 50M

action/protocol/staking/protocol.go, action/protocol/staking/validations.go
New actions (i.e. CandidateEndorsement and CandidateActivate) should be rejected before HF is activated, otherwise it may lead to forks if anyone send the two actions.
After this change, there also be difference with last version:
- Old Behaviour: Not be added into actpool for action decode error
- New Behaviour: Action can be added into actpool, but will be droped when mint block for validation error
But the difference will not cause forks.
- [] make test
- Hardware:
- Toolchain:
- SDK: …
=> [action] Reject new actions before HF activated

action/protocol/context.go, action/protocol/staking/handler_candidate_endorsement_test.go, action/protocol/staking/handler_candidate_selfstake_test.go, action/protocol/staking/handlers_test.go, dispatcher/dispatcher.go, e2etest/native_staking_test.go
…ersion at Tsunami height
as title.
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [context] enable delegate endorsement and refactor fresh account conversion at Tsunami height

Makefile, blockchain/blockdao/blockdao.go, blockchain/blockdao/blockdao_test.go, blockchain/blockdao/blockindexer.go, blockchain/blockdao/blockindexer_test.go, go.test.sh
add unit test for module blockchain/blockdao
Fixes #4121 
- Hardware:
- Toolchain:
- SDK:
=> test: add unit test for module blockdao

api/coreservice.go
Fixes overflow in coreservice
- [] make test
- [] fullsync
- Hardware:
- …
=> feat(api): fix overflow in coreservice

actpool/actpool.go
The queueWorker will be blocked when put result back to a channel but the action is already timeout, b/c the `workerJob.errChan` is a channel without buffer. 
This PR change the `errChan` to a buffered channel, thus queueWorker can put result to the channel even if there is no goroutine to retrive from this channel.
Fixes #(issue)
- Hardware:
- Toolchain:
- SDK: …
=> [actpool] Fix queueWorker blocked by timeout action

action/protocol/execution/evm/evmstatedbadapter.go
To ensure data consistency, generate the missing log after the hard-fork. A separate patch file will be created later to provide missing logs before the hard-fork. 
// TODO: remove this gating once the hard-fork has passed
Fixes #(issue)
- [] fullsync
- …
=> [evm] gate the generation of suicide transaction log

.github/CODEOWNERS, blockchain/genesis/genesis.go, blockchain/genesis/heightupgrade_test.go, config/config.go, config/config_test.go
adding the height for 1.15
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [genesis] add Upernavik block height

action/protocol/execution/evm/evmstatedbadapter.go, action/protocol/execution/evm/evmstatedbadapter_test.go, action/protocol/execution/evm/testdata_test.go, blockchain/genesis/genesis.go
as title, to make code more readable following the interface name change
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [evm] rename suicide to selfDestruct

api/coreservice.go, api/grpcserver_integrity_test.go, api/web3server.go, api/web3server_test.go, blockchain/block/block_deserializer.go, blockchain/block/block_deserializer_test.go, blockchain/filedao/filedao_v2.go, blockchain/filedao/filedao_v2_util.go, blockchain/filedao/testing.go, test/mock/mock_apicoreservice/mock_apicoreservice.go
`getTransactionReceipt` is monitored to consume lots of cpu resources when serving for web3 requests.
Block and Receipt are deserialized and cached separtedly to reduce duplicate computing
Fixes #(issue)
- [] make test
- [] fullsync
**Test …
=> [blockdao] Optimize derialization when retrieving receipts

action/protocol/context.go, action/protocol/execution/evm/evm.go, action/protocol/execution/evm/evmstatedbadapter.go, action/protocol/execution/evm/evmstatedbadapter_test.go
1. revert to the same snapshot version again should cause a panic(). make it the same behavior as in ethereum
2. panic on unrecoverable errors (like store state/account fail)
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- …
=> [evm] panic on unrecoverable error

.github/CODEOWNERS, action/rlp_tx.go, action/rlp_tx_test.go, api/web3server.go, api/web3server_test.go
After v1.13.0, `DecodeEtherTx()` is used to decode web3 action. `DecodeRawTx` is obsolete and can be removed
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- …
=> [action] remove DecodeRawTx()

api/web3server.go
The trace APIs we implement cannot get the state of the transaction at that time, and most of the results obtained by calling the trace APIs is wrong (eg. #4208) . Enable this feature after archive mode supports it.
Fixes #(issue)
- [] make test
- [] fullsync
- Firmware …
=> [api]disable debug_trace APIs before archive mode is supported

action/evm_transaction.go, action/execution.go, action/execution_test.go, action/protocol/execution/evm/evm.go, action/protocol/execution/evm/evm_test.go, action/protocol/execution/protocol.go, action/protocol/poll/consortium.go, action/protocol/poll/staking_committee.go
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] My code follows the …
=> [action] add EvmTransaction to represent actions that run in EVM

action/protocol/context.go, action/protocol/staking/handlers.go, action/protocol/staking/protocol.go, action/protocol/staking/validations.go, action/signedaction.go, action/signedaction_test.go, e2etest/native_staking_test.go
Make up missing parts for CandidateTransferOwnership
Related PR:
https://github.com/iotexproject/iotex-core/pull/4236
https://github.com/iotexproject/iotex-core/pull/4239
https://github.com/iotexproject/iotex-core/pull/4245
https://github.com/iotexproject/iotex-core/pull/4250
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [staking] enable CandidateTransferOwnership at CandidateIdentifiedByOwner feature

ioctl/cmd/action/stake2.go, ioctl/cmd/action/stake2transfer_ownership.go
ioctl Add stake2 transferownership command, allow delegate to transfer the ownership to a new address
```
ioctl stake2 transferownership  <alias|newOwnerAddress> [payload]
```
Related PR:
https://github.com/iotexproject/iotex-core/pull/4236
https://github.com/iotexproject/iotex-core/pull/4239
https://github.com/iotexproject/iotex-core/pull/4245
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test …
=> [ioctl] Add stake2 transferownership command

ioctl/cmd/ioid/applyioid.go, ioctl/cmd/ioid/contracts/abis/Project.json, ioctl/cmd/ioid/contracts/abis/ProjectRegistry.json, ioctl/cmd/ioid/contracts/abis/ioID.json, ioctl/cmd/ioid/contracts/abis/ioIDRegistry.json, ioctl/cmd/ioid/contracts/abis/ioIDStore.json, ioctl/cmd/ioid/contracts/project.go, ioctl/cmd/ioid/contracts/projectregistry.go, ioctl/cmd/ioid/ioid.go, ioctl/cmd/ioid/project.go, ioctl/cmd/ioid/projectdevice.go, ioctl/cmd/ioid/projectregister.go
1. Refactor ioID cmd
2. Register project add name parameter
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
=> refactor ioID cmd

action/protocol/staking/contractstake_indexer.go, action/protocol/staking/contractstake_indexer_mock.go, action/protocol/staking/protocol.go, action/protocol/staking/protocol_test.go, action/protocol/staking/staking_statereader.go, action/protocol/staking/staking_statereader_test.go, blockindex/contractstaking/indexer.go
This refactoring will simplify the integration work of the coming new staking contract indexer, with the main changes including:
- removing `CandidateVotes()` from the indexer interface, with vote counting implementation move to the staking protocol
- adding `ContractAddress()` in the indexer interface
- introducing `[]indexers` in statereader, and implementation of various read interfaces based on it.
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] My code follows the …
=> [staking] refactor statereader to support multiple contract indexers

action/signedaction.go
Add WithChainID option for SignedAction functions
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] New and existing unit tests pass …
=> [action] Sign action with ChainID

action/protocol/staking/candidate_center_test.go, action/protocol/staking/handler_candidate_transfer_ownership_test.go, action/protocol/staking/protocol.go, e2etest/e2etest.go, e2etest/expect.go, e2etest/native_staking_test.go
The pr introduce e2etest framework to simplify add test cases, focusing on construct actions and expectations. 
Futhermore, add testcases via the frameworks for original action handlings after candidate ownership transfer.
based on #4294 
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [e2etest] add tests for original actions after candidate ownership transfer

action/protocol/staking/candidate_statereader.go, action/protocol/staking/ethabi/common/candidatebyaddress.go, action/protocol/staking/ethabi/common/types.go, action/protocol/staking/ethabi/stakebase_test.go, action/protocol/staking/ethabi/v1/stakecandidatebyaddress_test.go, action/protocol/staking/ethabi/v1/stakecandidatebyname_test.go, action/protocol/staking/ethabi/v1/stakecandidates_test.go, action/protocol/staking/ethabi/v3/builder.go, action/protocol/staking/ethabi/v3/stake_candidatebyaddress.go, action/protocol/staking/ethabi/v3/stake_candidatebyid.go, action/protocol/staking/ethabi/v3/stake_candidatebyname.go, action/protocol/staking/ethabi/v3/stake_candidates.go, action/protocol/staking/ethabi/v3/stakecandidatebyaddress_test.go, action/protocol/staking/ethabi/v3/stakecandidatebyid_test.go, action/protocol/staking/ethabi/v3/stakecandidatebyname_test.go, action/protocol/staking/ethabi/v3/stakecandidates_test.go, action/protocol/staking/handlers.go, e2etest/native_staking_test.go, go.mod, go.sum
Due to the introduction of a new `ID` as a unique identifier by the Candidate, the following modifications need to be made to the API: 
- Upgrade the `candidateByAddress`, `candidateByName`, and `candidates` APIs to v3, adding 'id' to the returned results. 
- Add a new API called `candidateByID`; the original meaning of the `candidateByAddress` is to query based on the owner's address.
It's based on https://github.com/iotexproject/iotex-proto/pull/151
- [] make test
- [] fullsync
- Hardware:
- …
=> [staking] ReadState API support Candidate ID

action/protocol/staking/candidate_center.go, action/protocol/staking/candidate_statemanager.go, action/protocol/staking/candidate_statereader.go, action/protocol/staking/handler_candidate_transfer_ownership.go, action/protocol/staking/handlers.go, action/protocol/staking/protocol.go, action/protocol/staking/read_state.go, action/protocol/staking/staking_statereader_test.go, e2etest/native_staking_test.go
To make it easier to understand the API returning candidates, clear the self-stake if endorsement has expired but not been updated yet.
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have …
=> [api] clear candidate selfstake if endorsement expired

state/factory/workingset.go
if unfolding a tx returns error, the tx should be removed from actpool so it won't keep stuck there
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [workingset] remove action from actpool upon tx container error

action/protocol/context.go, action/protocol/staking/builder.go, action/protocol/staking/handler_candidate_selfstake_test.go, action/protocol/staking/handler_candidate_transfer_ownership_test.go, action/protocol/staking/handlers.go, action/protocol/staking/handlers_test.go, action/protocol/staking/protocol.go, action/protocol/staking/protocol_test.go, action/protocol/staking/validations_test.go, action/protocol/staking/vote_reviser_test.go, blockchain/config.go, blockchain/genesis/genesis.go, chainservice/builder.go, chainservice/chainservice.go, e2etest/e2etest.go, e2etest/local_actpool_test.go, e2etest/local_test.go, e2etest/local_transfer_test.go, e2etest/native_staking_test.go, e2etest/nodeinfo_test.go, e2etest/rewarding_test.go, e2etest/staking_test.go, server/itx/heartbeat_test.go, server/itx/server_test.go, systemcontractindex/stakingindex/bucket.go, systemcontractindex/stakingindex/index.go
This pr introduce new staking indexer for staking protocol, which include two mainly changes:
- can retrive new staking contract buckets by staking api
- new staking contract votes for candidate
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] My …
=> [staking] enable new staking index

action/protocol/execution/evm/evm.go, action/protocol/execution/evm/evm_test.go, action/protocol/execution/protocol_test.go
as title
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [evm] defer Cancun enabling

action/candidate_endorsement.go, action/protocol/staking/endorsement.go, action/protocol/staking/endorsement_statemanager.go, action/protocol/staking/handler_candidate_endorsement.go, action/protocol/staking/handler_candidate_endorsement_test.go, action/protocol/staking/protocol.go, action/protocol/staking/read_state.go, action/protocol/staking/validations.go, action/rlp_tx_test.go, action/signedaction.go, go.mod, go.sum, ioctl/cmd/action/stake2endorse.go
In this PR, a new field `Op` is introduced. `OpLegacy`, the default value, is for the current implementation of `CandidateEndorsement` action. And the others are new ops.
As it has been gated in action/protocol/staking/validations.go, only legacy actions are allowed. A follow up PR will add a hardfork to allow the new ops.
Fixes #(issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. …
=> add endorsement op but only allow legacy

action/candidate_endorsement.go, action/protocol/context.go, action/protocol/staking/bucket_validation.go, action/protocol/staking/bucket_validation_test.go, action/protocol/staking/candidate_statereader.go, action/protocol/staking/endorsement_statemanager.go, action/protocol/staking/endorsement_statemanager_test.go, action/protocol/staking/handler_candidate_endorsement.go, action/protocol/staking/handler_candidate_selfstake.go, action/protocol/staking/handler_candidate_transfer_ownership.go, action/protocol/staking/handler_stake_migrate.go, action/protocol/staking/handler_stake_migrate_test.go, action/protocol/staking/handlers.go, action/protocol/staking/protocol.go, action/protocol/staking/protocol_test.go, action/protocol/staking/read_state.go, action/protocol/staking/validations.go, action/rlp_tx_test.go, action/signedaction.go, e2etest/e2etest.go, e2etest/expect.go, e2etest/native_staking_test.go
jump to commit https://github.com/iotexproject/iotex-core/pull/4315/files/ad13942b2d72e3fd6b4168c9ece8dffa4af8fa10..c9cbbe0ca978ead3ff6a8c9d87cb8ff4c935c5f3 to review: add a new hard fork flag, `EnforceLegacyEndorsement`
Fixes #(issue)
- [] make test
- [] fullsync
- [] …
=> Enforce legacy endorsement feature ctx

action/protocol/staking/builder.go, action/protocol/staking/handler_candidate_selfstake_test.go, action/protocol/staking/handler_candidate_transfer_ownership_test.go, action/protocol/staking/handler_stake_migrate_test.go, action/protocol/staking/handlers_test.go, action/protocol/staking/protocol.go, action/protocol/staking/protocol_test.go, action/protocol/staking/validations_test.go, action/protocol/staking/vote_reviser.go, action/protocol/staking/vote_reviser_test.go, chainservice/builder.go
jump to https://github.com/iotexproject/iotex-core/pull/4312/files/c9cbbe0ca978ead3ff6a8c9d87cb8ff4c935c5f3..7536390e8fbcde722b1209ef5676d3b2b2adabdc to review. add a feature to revise endorsements of self stake buckets
Fixes #(issue)
- [] make test
- [] fullsync
- [] …
=> revise self stake buckets

action/protocol/staking/handlers.go
The check for duplicate candidate IDs during registration should be placed after the hard fork, as the ID is introduced only after the hard fork.
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have added …
=> [staking] only validate duplicate candidate id after HF

action/protocol/staking/handler_candidate_transfer_ownership.go, action/protocol/staking/handlers.go, e2etest/e2etest.go, e2etest/expect.go, e2etest/native_staking_test.go
1. ensure that there is no conflict between the owner and identifier during candidateRegister and candidateTransferOwnership.
2. can transfer the candidate back to the previous owner.
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] My …
=> [staking] make transfering ownership back valid

api/coreservice.go, e2etest/native_staking_test.go
as title
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- …
=> [api] fix estimateGas panic for StakeMigrate

action/protocol/staking/ethabi/common/candidatebyaddress.go, action/protocol/staking/ethabi/common/candidatebyname.go, action/protocol/staking/ethabi/common/candidates.go, action/protocol/staking/ethabi/v1/stake_candidatebyaddress.go, action/protocol/staking/ethabi/v1/stake_candidatebyname.go, action/protocol/staking/ethabi/v1/stake_candidates.go
In the staking v1 version api, the PR temporarily changes `SelfStakeBucketIndex` to max uint32 if its value equals to max uint64 , to assist the older version of iopay in resolving overflow issues. This code can be removed after the iopay update.
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [api] candidates v1 temporarily changes to max uint32 from max uint64

action/protocol/execution/evm/evm.go
mainnet API log shows panic caused by invalid ex.Contract (string length = 4, not 41 for valid address).
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] My code …
=> [evm] fix invalid contract address causing SimulateExecution() panic

api/coreservice.go
getLogs has two issues: 
1. if bfIndexer behinds dao 1 height, the returned result may be incorrect. 
3. Modifying the page size internally may result in missing returned results.
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] My …
=> [api] fix inaccurate result of getLogs

action/protocol/staking/candidate_statereader.go, action/protocol/staking/protocol.go, action/protocol/staking/read_state.go
A new bug is found in the staking protocol, that is self-staked data is not cleared in candidate after unstake self-stake bucket operatio.  This bug fix will require the next hard fork. For now, returned candidates will be repaired in the API.
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [api] correct candidate selfstake

action/protocol/staking/staking_statereader.go, e2etest/e2etest.go, e2etest/native_staking_test.go
use id instead of owner when counting votes, which only affect api, not the consensus. 
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [api] Fix nft bucket votes counting

api/web3server_utils.go
When parsing the topic filter, `nil` should be parsed as `[]string{}` instead of `[]string{""}`.
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have added tests that prove my fix is effective or that my …
=> [api] Fix parsing of log filter

api/config.go, api/context.go, api/coreservice.go, api/grpcserver.go, api/grpcserver_test.go, api/listener.go, api/metrics.go, api/serverV2.go, api/serverV2_test.go, api/web3server.go, api/web3server_test.go, api/websocket.go
Temporarily relax #4373 , increase global listen limits to 5000 from 500
Ultimately, the api `eth_subscribe` and `eth_unsubscribe` should only take effect for websockets, and related listeners should be cleaned up after the connection is disconnected. The limitations can also be revised to apply to the number of listeners per connection.
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [API] increase api listener limit

action/protocol/managers.go, api/coreservice.go, e2etest/native_staking_test.go, state/factory/factory.go, state/factory/statedb.go, test/mock/mock_apicoreservice/mock_apicoreservice.go, test/mock/mock_factory/mock_factory.go
When estimating the gas for the `MigrateStake` transaction, the `amount` of the native bucket is not returned to the sender. If the sender's balance is insufficient for the bucket amount, an `insufficient balance for transfer` error will be returned.
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [api] fix estimateGas for migrateStake

action/evm_transaction.go, action/execution.go, action/protocol/execution/evm/evm.go, action/protocol/execution/evm/evm_test.go, action/protocol/execution/protocol.go, action/protocol/poll/consortium.go, action/protocol/poll/staking_committee.go
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- …
=> [action] deprecate EvmTransaction{} struct, to be replace by Envelope

actpool/actpool.go, actpool/actpool_test.go, actpool/actqueue.go, actpool/config.go, actpool/queueworker.go, test/mock/mock_actpool/mock_actpool.go
There are many differences between Blob-tx and regular tx, requiring different validation rules to ensure the correctness of transactions while maintaining program performance.
Based on #4366 
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [actpool] validation for blobtx

action/protocol/account/transfer.go, action/protocol/execution/evm/evm.go, action/protocol/execution/evm/evm_test.go, action/protocol/poll/consortium.go, action/protocol/poll/staking_committee.go, action/protocol/protocol.go, action/protocol/rewarding/fund.go, action/protocol/rewarding/protocol.go, action/protocol/staking/handler_stake_migrate_test.go, action/protocol/staking/handlers_test.go, action/protocol/staking/protocol.go, action/rlp_tx_test.go, go.mod, go.sum, state/factory/workingset.go
The basefee introduced by EIP-1559 used to be burned directly, but now it has been changed to be transferred to the rewarding pool.
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have added tests that prove …
=> [eip1559] basefee into rewardingpool

api/coreservice.go, api/types/types.go, api/web3server.go, api/web3server_marshal_test.go, test/mock/mock_apicoreservice/mock_apicoreservice.go
introduce new api `eth_getBlobSidecars` to return blobs in a block.
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] New and …
=> [api] eth_getBlobSidecar

action/actctx.go, action/blob_data.go, action/blob_data_test.go, action/builder.go, action/builder_test.go, action/envelope.go, action/protocol/execution/protocol_test.go, action/rlp_tx.go, action/rlp_tx_test.go, action/tx_access_list.go, action/tx_blob.go, action/tx_blob_test.go, action/tx_container.go, action/tx_dynamic_fee.go, action/tx_legacy.go, test/mock/mock_envelope/mock_envelope.go
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] My …
=> [action] enable dynamic fee tx

action/blob_data.go, blockchain/block/block.go, blockchain/block/block_test.go, blockchain/block/blockstore.go, blockchain/block/testing.go, blockchain/blockdao/blob_store_test.go, blockchain/filedao/filedao_v2_test.go, blockchain/filedao/filedao_v2_util.go, blockchain/filedao/staging_buffer.go, blockchain/integrity/integrity_test.go, chainservice/builder.go
Fixes #(issue)
- [] make test
- [] fullsync …
=> [block] blocksync to use block.WithBlobSidecars()

action/protocol/context.go, action/protocol/execution/evm/evm.go, action/protocol/execution/evm/evmstatedbadapter.go, action/protocol/execution/evm/evmstatedbadapter_test.go
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] My …
=> [evm] implement EIP-6780 SELFDESTRUCT only in same transaction

state/factory/workingset.go
the `AccumulatedTips` of blockCtx will be updated after one action handled, so it should be re-wrapped into ctx for next action handling
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have added tests that …
=> [workingset] fix expired blockctx for validate block

actpool/actpool.go, actpool/actqueue.go, actpool/actqueue_test.go, actpool/queueworker.go, actpool/validator.go
Move blob count per account checking before proof verification in actpool, because verification is time-consuming calling.
Implement it in two steps:
- add subscriber in actpool to knowing actions for other components
- make a new validator to wrap the checking, and put it front to generic_validator
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [actpool] check blob count before verifying proof

action/protocol/context.go, action/protocol/staking/handlers.go, action/protocol/staking/handlers_test.go, action/protocol/staking/vote_reviser.go, action/protocol/staking/vote_reviser_test.go, chainservice/builder.go
Fixes #4336 , including two parts:
- clean selfstake when handling unstake action in staking protocol
- revise candiate selfstake at VanuatuBlockHeight
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have added tests that …
=> [staking] Fix unstake not clean selfstake

action/protocol/context.go, state/factory/workingset.go
currently it first calls `protocol.Validate()` for all txs in the block, then calls `runAction` for all txs in the block
it should be calling these 2 funcs for the first tx, then next in the block, to make it the same as `pickAndRunActions`
Fixes #(issue)
- [] make test
- …
=> [workingset] validate each tx before run it

api/coreservice.go, api/grpcserver_integrity_test.go, api/web3server.go, api/web3server_test.go
Fixes #4389 
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] Any …
=> [api] Fix execution reverted message in eth_call

chainservice/builder.go, chainservice/builder_test.go
The current estimate of the latest height is incorrect, which will cause the verification of blocks to fail when the blob has expired during synchronization with lagging nodes.
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] My changes generate no new …
=> [blocksync] Fix estimate tip height

api/coreservice.go, api/web3server_utils.go
Root-cause of issue 4485 is that tx is still pending (in actpool) so it is in container format, so we need to convert it to concrete tx type before returning to `eth_getTransactionByHash`.
Fixes #4485
The code change has been tested locally to fix the hardhat deploy issue
- [] fullsync
**Test …
=> [api] convert container tx in actpool

action/protocol/execution/evm/evm.go, action/protocol/execution/protocol_test.go, api/coreservice.go, chainservice/builder.go, e2etest/staking_test.go, state/factory/factory.go, state/factory/factory_test.go, state/factory/statedb.go, test/mock/mock_factory/mock_factory.go
2 methods don't need to be in the `factory` interface.
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I …
=> [factory] move SimulateExecution() out of factory interface

blockchain/blockdao/blob_store_test.go, blockchain/filedao/filedao_v2_test.go, blockchain/filedao/filedao_v2_util.go, blockchain/filedao/staging_buffer.go
as title
Fixes #4489
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have made corresponding changes to …
=> [filedao] get recent blocks from staging buffer

action/protocol/context.go, action/protocol/execution/evm/evm.go, action/protocol/execution/evm/evmstatedbadapter.go
as title.
Fixes #4491
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I …
=> [evm] fix RevertSnapshot

action/envelope.go, action/protocol/protocol.go, action/protocol/rewarding/protocol.go, action/protocol/staking/protocol.go, go.mod, test/mock/mock_envelope/mock_envelope.go
as title.
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] …
=> [action] simplify TxCommon interface

api/web3server.go, api/web3server_test.go, api/web3server_utils.go
estimategas as legacyTx for new types tx may cause OutOfGas error
based on #4479 
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] …
=> [api] Fix out of gas for new types tx

blockchain/integrity/integrity_test.go, state/factory/factory_test.go, state/factory/statedb.go
as title, the return value of `WorkingSetAtHeight` is actually NOT used, but return an error stops the code from continuing to execute.
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [factory] fix statedb WorkingSetAtHeight

action/sealedenvelope.go, api/coreservice.go, state/factory/workingset.go
This issue did not trigger any invalid actions to be included in the block, so it only needs to be fixed at the API level.
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have added tests that prove my fix is …
=> [api] Fix not reject unprotected && unwhitelisted action

blockchain/blockdao/blockindexer.go, blockindex/bloomfilterindexer.go, blockindex/contractstaking/indexer.go, blockindex/indexer.go, blockindex/indexer_test.go, blockindex/sync_indexers.go, state/factory/factory.go, state/factory/statedb.go, systemcontractindex/stakingindex/index.go, test/mock/mock_blockdao/mock_blockindexer.go, test/mock/mock_blockdao/mock_blockindexer_withstart.go, test/mock/mock_blockindex/mock_blockindex.go, test/mock/mock_blockindex/mock_indexer.go, test/mock/mock_factory/mock_factory.go
as discussed, `DeleteTipBlock()` is not meaningful for indexers, so remove this from interface.
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have …
=> [blockindex] remove DeleteTipBlock()

api/web3server_utils.go
as title
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] …
=> Fix panic if account error

blockchain/blockchain.go, test/mock/mock_blockchain/mock_blockchain.go
this is needed to set chain's context at certain height for archive-mode.
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have performed …
=> [blockchain] add ContextAtHeight()

action/protocol/staking/builder.go, action/protocol/staking/protocol.go, blockchain/config.go, chainservice/builder.go
If a full-node runs from 0 without stopping, it will stop at Okhotsk height for the candidate alias bug. This PR fix the issue by manually resetting the candidate states in `CreatePreStates`
Fixes #(issue)
- Hardware:
- Toolchain:
- SDK:
- [] My code …
=> [staking] fix alias for non-stop node

api/web3server.go, api/web3server_integrity_test.go, api/web3server_utils.go
it's based on #4527 
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] …
=> [api] impl eth_blobBaseFee

db/db_versioned.go, db/db_versioned_test.go
as title.
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have …
=> [db] implement CommitToDB() for BoltDBVersioned

action/protocol/context.go, action/protocol/generic_validator.go, state/factory/workingset.go
as title, remove the flag after HF activated.
Fixes #(issue)
- [] make test
- Hardware:
- Toolchain:
- SDK:
- [] I have …
=> [protocol] verify container format always

action/protocol/context.go, action/protocol/generic_validator.go
as title, fix the following bug.
Fixes #4561 
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> [context] tolerate empty candidate name

action/protocol/staking/staking_statereader_test.go, blockindex/contractstaking/indexer_test.go, e2etest/contract_staking_test.go, ioctl/cmd/bc/bcdelegate.go, nodeinfo/manager.go
Since Go 1.21, the functions in x/exp used here can already be replaced by functions from the standard library.
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> refactor: replace golang.org/x/exp with stdlib

db/db_pebble_test.go, server/itx/server_test.go
TempDir returns a temporary directory for the test to use.The directory is automatically removed when the test and
all its subtests complete. More info  https://pkg.go.dev/testing#B.TempDir
- [] fullsync
- Hardware:
- Toolchain:
- …
=> refactor: use t.TempDir() instead of os.MkdirTemp

blockchain/blockchain.go, blockchain/config.go, blockchain/config_test.go, chainservice/builder.go, consensus/consensus.go, consensus/consensusfsm/context.go, consensus/consensusfsm/fsm.go, consensus/consensusfsm/fsm_test.go, consensus/consensusfsm/mock_context_test.go, consensus/scheme/rolldpos/rolldpos.go, consensus/scheme/rolldpos/rolldpos_test.go, consensus/scheme/rolldpos/rolldposctx.go, consensus/scheme/rolldpos/rolldposctx_test.go, consensus/scheme/rolldpos/roundcalculator.go, consensus/scheme/rolldpos/roundctx.go, e2etest/nodeinfo_test.go, endorsement/endorsement.go, nodeinfo/manager.go, nodeinfo/manager_test.go, server/itx/heartbeat.go, server/main.go, state/factory/factory.go, state/factory/statedb.go, test/mock/mock_blockchain/mock_blockchain.go, tools/minicluster/minicluster.go
as title
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I …
=> support multiple producers

action/protocol/context.go, action/protocol/execution/protocol.go, action/protocol/poll/consortium.go, action/protocol/poll/governance_protocol.go, action/protocol/poll/governance_protocol_test.go, action/protocol/poll/protocol.go, action/protocol/poll/staking_committee_test.go, api/coreservice.go, api/coreservice_test.go, api/grpcserver_integrity_test.go, api/serverV2.go, api/serverV2_integrity_test.go, blockchain/blockchain.go, chainservice/builder.go, chainservice/chainservice.go, e2etest/local_test.go, state/factory/factory_test.go, tools/actioninjector.v2/internal/client/client_test.go
as title
base #4592 
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have commented my code, particularly …
=> [refactor] move getBlockTime and getBlockHash funcs into blockchain context

action/protocol/execution/evm/evm_test.go, blockchain/genesis/genesis.go, blockchain/genesis/heightupgrade_test.go, config/config.go, config/config_test.go
Fixes #(issue)
- [] make test
- [] fullsync …
=> introduce the wakeBlockHeight as next hardfork

db/db_versioned.go, db/kvstore_versioned.go, db/kvstore_versioned_test.go
as title.
based on (#4517)
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I …
=> [db] KvWithVersion to handle both versioned and non-versioned namespace

action/protocol/context.go, state/factory/workingset.go
as title
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> add feature flag for system action validation

action/protocol/context.go, action/protocol/poll/util.go, action/protocol/protocol.go, action/protocol/staking/candidate_statemanager.go, action/protocol/staking/candidate_statereader.go, action/protocol/staking/contractstake_indexer.go, action/protocol/staking/contractstake_indexer_mock.go, action/protocol/staking/protocol.go, action/protocol/staking/protocol_test.go, action/protocol/staking/viewdata.go, blockindex/contractstaking/cache.go, blockindex/contractstaking/event_handler.go, blockindex/contractstaking/indexer.go, blockindex/contractstaking/stakeview.go, chainservice/builder.go, consensus/scheme/rolldpos/rolldposctx.go, state/factory/workingset.go, systemcontractindex/common.go, systemcontractindex/stakingindex/event_handler.go, systemcontractindex/stakingindex/index.go, systemcontractindex/stakingindex/mute_handler.go, systemcontractindex/stakingindex/stakeview.go
This PR fixes the issue of validation failure when minting block include the putpollresult transaction in advance. The cause of this issue was that the contract staking indexer was one block behind when preparing the next proposal.
Now, the contract staking states are stored in the protocol's view, and a PostActionHandler has been added during execution to ensure that contract staking data can be updated immediately after each transaction execution.
Can review them in order by commit:
- staking protocol bdc28e1a0f79c32456b898fe98559405ab9d5ca8
- v1 contract indexer 3ef41632c6cbb597b9ecaeaa4656011eab4509f2
- v2&v3 contract indexer 0d62ee7cae9bd97ca76e1e522d3cd3383478ae31
- [] Code …
=> [staking] Read contract votes from protocol view

state/factory/factory_test.go
mint two blocks sequentially, read the states (account balances) from the corresponding state readers.
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] My code …
=> read states from uncommitted state readers

action/protocol/staking/protocol_test.go, action/protocol/staking/viewdata.go, action/protocol/staking/viewdata_test.go, state/factory/factory_test.go, state/factory/statedb.go
1. Unit test for staking.ViewData
2. Unit test for view read and write
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …
=> unit test for view

action/protocol/rewarding/reward_test.go, blockchain/genesis/genesis.go, blockchain/genesis/genesis_test.go, chainservice/builder_test.go, consensus/consensusfsm/consensus_ttl.go, consensus/consensusfsm/consensus_ttl_test.go
Adjust Wake block reward to 4iotx and block interval to 2.5s. Correspondingly, the AcceptBlockTTL and AcceptProposalEndorsementTTL are reduced to 0.8s, AcceptLockEndorsementTTL and CommitTTL are reduced to 0.45s.
Fixes #(issue)
- [] make test
- [] fullsync
- [] Other test …
=> adjust wake block interval and block reward

actpool/actpool.go, actpool/queueworker.go, actpool/validator.go, api/action_radio.go, api/action_radio_test.go, api/context.go, api/coreservice.go
Currently, actions received from the API and the P2P network both are being broadcast again, which can cause congestion in the P2P network. It has now been changed to only broadcast transactions coming from the API.
- [] make test
- [] fullsync
- …
=> Only broadcast actions from api

action/protocol/staking/bucket_pool_test.go, action/protocol/staking/candidate_statereader.go, action/protocol/staking/viewdata.go, action/protocol/staking/viewdata_test.go, blockindex/contractstaking/indexer.go, blockindex/contractstaking/stakeview.go, systemcontractindex/stakingindex/cache.go, systemcontractindex/stakingindex/cowcache.go, systemcontractindex/stakingindex/cowcache_test.go, systemcontractindex/stakingindex/event_handler.go, systemcontractindex/stakingindex/index.go, systemcontractindex/stakingindex/stakeview.go
Fixes #(issue)
- [] make test
- [] fullsync …
=> cow cache for staking view

action/claimreward.go, action/protocol/execution/evm/evmstatedbadapter.go, action/protocol/rewarding/reward.go, blockchain/genesis/genesis.go, blockchain/integrity/integrity_test.go, consensus/scheme/rolldpos/rolldpos.go, e2etest/local_transfer_test.go, ioctl/doc/doc.go
fix some minor issues in the comments
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] Any dependent changes have …
=> chore: fix some minor issues in the comments

api/coreservice.go, api/coreservice_with_height.go
fix these two bugs:
1. `eth_call` on latest return nothing
```
curl  https://archive-mainnet.iotex.io \
-X POST \
-H "Content-Type: application/json" \
--data '{"method":"eth_call","params":[{"from": null,"to":"0x8114746e4308a4d3ff2a74b66414ff35657fa0e2","data":"0x8da5cb5b"}, "latest"
],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","id":1,"result":"0x"}
```
2. `eth_call` error on block WakeBlockHeight-1
```
curl  https://archive-mainnet.iotex.io \
-X POST \
-H "Content-Type: application/json" \
--data '{"method":"eth_call","params":[{"from": null,"to":"0x8114746e4308a4d3ff2a74b66414ff35657fa0e2","data":"0x8da5cb5b"}, "0x232F4B8"
],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","id":1,"error":{"code":13,"message":"exceeds block gas limit"}}
```
- [] New …
=> Fix archive simulate bugs

action/protocol/execution/evm/evm.go
Since the hardfork timestamp relies on retrieval from the blockchain, it causes the node to depend on the chaindb at the hardfork height. To eliminate this dependency, the hardfork timestamp is changed to a time based on the current block timestamp, as it only requires maintaining the chronological order of the timestamps.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also …
=> use relative hardfork timestamp instead of reading from blockchain
