iotexproject/iotex-core

blocksync/blocksync_test.go
config/config.go
e2etest/config_local_delegate.yaml
e2etest/net_test.go
network/overlay_test.go
network/peermanager.go
network/rpcserver.go
simulator/consensus_sim_server.go

Rename config.Network.IP to config.Network.Host

---

simulator/consensus_sim_server.go
tools/addrgen/internal/cmd/createconfig.go
tools/addrgen/internal/cmd/generate.go
tools/addrgen/internal/cmd/root.go

remove std log.

---

README.md

we support go version `>=1.10.2 && < 1.11`

Update README.md on go version requirements

---

actpool/actpool.go
dispatch/dispatch.go

reduce some noisy log  in dispatch and actpool
add error metrics in dispatch

reduce some noisy log and add some metrics

---

blockchain/blockchain.go
chainservice/chainservice.go
config/config.go
consensus/scheme/rolldpos/rolldpos_test.go
e2etest/local_actpool_test.go
e2etest/local_test.go
e2etest/net_test.go
server/itx/heartbeat.go
server/itx/server.go
server/main.go
tools/actioninjector/actioninjector_test.go

- add `chainservice` to group actpool, blockchain, consensus, blocksync and explorer
- make `itx/server` able to hold multiple `chainservice`

IOTEX-46 make iotex node able to start multiple chains

---

tools/addrgen/internal/cmd/createconfig.go
tools/addrgen/internal/cmd/generate.go

- make addrgen tool generate only keypair
- avoid use legacy method

make addrgen tool generate only keypair

---

network/overlay_test.go

@CoderZhi Thanks bro! You're the best!

Auto formate network/overlay_test.go

---

Gopkg.lock
Gopkg.toml
config/config.go
db/rds/rds.go
db/rds/rds_test.go
db/rds/util.go

add rds and unit test

---

action/subchain/datamodel.go
action/subchain/datamodel_test.go
state/account.go
state/candidate.go
state/candidate_test.go
state/factory.go
state/state.go
state/workingset.go

In addition, refactor the gob based ser/des code to share, and refactor the candidate ser/des interface.

IOTEX-86 Make chain related state struct implement state interface

---

action/subchain/protocol.go
action/subchain/protocol_test.go
pkg/hash/hash.go
state/factory.go
state/workingset.go
test/mock/mock_state/mock_state.go

This would work correctly before landing #190

IOTEX-86 Implement state manipulation for start sub-chain action

---

state/factory.go
state/state.go
state/workingset.go

Simplify how to print the type in a message string

---

consensus/scheme/rolldpos/fsm.go

Discard events of lower height

add height to consensus event

---

consensus/scheme/rolldpos/fsm.go
consensus/scheme/rolldpos/fsm_test.go

when system error happens in FSM, move fsm back to epoch_start.

---

state/factory.go
trie/trie.go

1. Adjust some lock types
2. Delete loadRoot, which contains lock in the private function
3. Add a TODO in trie.query

fix a few locks

---

consensus/scheme/rolldpos/rolldpos_test.go

This will help the Consensus components start at almost the same time that it is easier to reach consensus.

Fix test failure with goroutine

---

consensus/scheme/rolldpos/fsm.go

Unify the endorsement event processing with processEndorseEvent

create processEndorseEvent function

---

action/stopsubchain_test.go

add unit test for substopchain

add unit test for substopchain

---

consensus/scheme/rolldpos/fsm.go

If the number of delegates is less than 4, we request all delegates reach agreement

special handling when number of delegates is less than 4

---

action/subchain/datamodel.go
action/subchain/startsubchain.go
blockchain/blockchain.go
config/config.go
test/mock/mock_blockchain/mock_blockchain.go

Generate start subchain receipt, and pass subchain address to chain config

pass subchain address to chain config

---

blockchain/evmstatedbadapter.go
blockchain/evmstatedbadapter_test.go

Account won't be created in evm when adding balance to a totally new account

Create an account if it doesn't exist when AddBlance

---

action/protocols/multichain/mainchain/datamodel.go
action/protocols/multichain/mainchain/datamodel_test.go
action/protocols/multichain/mainchain/protocol.go
action/protocols/multichain/mainchain/protocol_test.go
action/protocols/multichain/mainchain/putblock.go
action/protocols/multichain/mainchain/putblock_test.go
action/protocols/multichain/mainchain/startsubchain.go
action/protocols/multichain/mainchain/startsubchain_test.go
action/protocols/multichain/subchain/protocol.go
server/itx/server.go
server/itx/subchain.go

Also, removed the hard coded mainchain id

IOTEX-136 Create multichain dir and split mainchain and subchain protocols

---

blocksync/blocksync.go
blocksync/buffer.go
blocksync/buffer_test.go

StartHeight will always be confirmedheight+1, and there is no dummy block to replace.

Remove startHeight and refine the logic of Flush function

---

endorsement/endorsementset.go
endorsement/endorsementset_test.go

Add some unit test for AddEndorsement function

replace endorsements from old round

---

action/protocols/multichain/mainchain/protocol.go
explorer/explorer.go
explorer/explorer_test.go
explorer/idl/explorer.idl
explorer/idl/explorer/explorer.go
explorer/mockexplorer.go
explorer/mockexplorer_test.go
test/mock/mock_explorer/mock_explorer.go

I removed the hardcode address/pk/sk btw.

IOTEX-137 Make explorer accept deposit request

---

Makefile
consensus/scheme/rolldpos/fsm.go

Accidentally checked in the debug code

delete debug code

---

blockchain/blockchain.go
indexservice/server.go
server/itx/server.go
server/itx/subchain.go

1. Add lock to Subscribe and Unsubscribe
2. Make sure only start each subchain once
3. Cleanup channels on unsubscribe

start sub chain once

---

action/action.go
action/builder.go
action/createdeposit.go
action/createdeposit_test.go
action/execution.go
action/putblock.go
action/putblock_test.go
action/secretproposal.go
action/secretwitness.go
action/settledeposit.go
action/settledeposit_test.go
action/startsubchain.go
action/startsubchain_test.go
action/stopsubchain.go
action/stopsubchain_test.go
action/transfer.go
action/vote.go
blockchain/block.go
blockchain/block_test.go
chainservice/chainservice.go
consensus/scheme/rolldpos/fsmevent.go
consensus/scheme/rolldpos/subchain_test.go
explorer/explorer.go
indexservice/indexer_test.go

- return error on action LoadProto if proto is not valid.
- use action builder in LoadProto
- add SetGasPriceByBytes for action builder
- also add some comments for action builder

return error on action LoadProto

---

actpool/actioniterator.go
actpool/actioniterator_test.go

add actioniterator. The design is describe in https://docs.google.com/document/d/1IzeYjG2i68ra4HThHjk-0PDQaaJgEAGLe8ZopA_5lsA/edit?ts=5bea6894

add actioniterator for action pick

---

action/protocols/multichain/mainchain/createdeposit_test.go
action/settledeposit.go
e2etest/multichain_test.go
explorer/explorer.go
state/factory.go

Fix the getDeposits explorer api together here.

Return empty account if it doesn't exist to accept action from non-existing account

---

state/factory/workingset.go
trie/trie.go
trie/trie_test.go

delete function NewTrieSharedBatch

refactor trie constructor with option

---

consensus/scheme/rolldpos/rolldpos_test.go
state/factory/factory.go
state/factory/factory_test.go
trie/trie.go

Move the redundant code to Start function

refactor the options and start function of factory

---

action/protocol/execution/evm/contract.go
action/protocol/execution/evm/evmstatedbadapter.go
action/protocol/execution/evm/evmstatedbadapter_test.go
db/trie/branchnode.go
db/trie/branchroottrie.go
db/trie/context.go
db/trie/extensionnode.go
db/trie/leafiterator.go
db/trie/leafnode.go
db/trie/trie.go
db/trie/trienode.go

based on #345, implement ForEachStorage interface of stateDB

Implement for each storage

---

server/itx/server.go
server/itx/subchain.go

add chainservice to dispatcher after chain service started

fix panic on nil db

---

blockchain/blockchain.go
chainservice/chainservice.go
server/itx/server.go
server/itx/subchain.go

Basically using a mutex to prevent a sub-chain service from being started for multiple times

IOTEX-183 Fix the bug of starting sub-chain and potential racing

---

action/protocol/execution/evm/evmstatedbadapter.go
action/protocol/execution/evm/evmstatedbadapter_test.go

Test Plan: unit test added to the cover the corner case
Will port this change to branch r0.4 too

IOTEX-195 Return 0 big int when there's a error on getting balance

---

accounts/keystore/accountmanager_test.go
accounts/keystore/keystore.go
accounts/keystore/keystore_test.go
accounts/keystore/single_accountmanager_test.go
action/protocol/execution/evm/evm.go
action/protocol/generic_validator.go
action/transfer.go
actpool/actpool_test.go
blockchain/block/block_test.go
blockchain/blockchain.go
blockchain/blockchain_test.go
blockchain/blockdao_test.go
blockchain/blockvalidator_test.go
blockchain/genesis/genesis.go

Moving it to gensis package. Later on, we will refactor and more all chain-wide configs to this package

IOTEX-209 Conslidate block gas limit consts and set it to 20,000,000

---

explorer/explorer.go

revert action sorting in explorer

revert action sorting in explorer

---

Gopkg.lock
staking/iotx_contract_test.go
staking/staking_test.go

Test CallOpts.BlockNumber, which is to specify the block height to query.

Test Web3 Api

---

actpool/actpool.go
actpool/actqueue.go
actpool/actqueue_test.go
actpool/options.go
config/config.go

add ttl on action in action pool
test plan:
unit test

add ttl on action in action pool (action queue)

---

README.md
action/protocol/execution/protocol_test.go
address/address.go
address/address_v1.go
address/address_v1_test.go
blockchain/block/block_test.go
blockchain/blockchain_test.go
blockchain/genesis_test.go
e2etest/local_test.go
e2etest/util.go
state/factory/factory_test.go
tools/actioninjector/actioninjector.go
tools/actioninjector/actioninjector_test.go

Remove version from address so that the address consists of a 20-byte public key hash.

IOTEX-233 Remove version from address

---

action/protocol/execution/evm/contract.go
action/protocol/execution/evm/contract_test.go
action/protocol/execution/evm/evmstatedbadapter.go
db/trie/trie.go

add a prefix to contract trie hash func

---

consensus/scheme/rolldpos/rolldposctx.go

To keep the proposer prepares the same block for different rounds of the same height

inherit block from last round of the same height

---

Gopkg.lock
Gopkg.toml
vendor/github.com/iotexproject/go-p2p/Gopkg.lock
vendor/github.com/iotexproject/go-p2p/Gopkg.toml
vendor/github.com/libp2p/go-libp2p-pubsub/.travis.yml
vendor/github.com/libp2p/go-libp2p-pubsub/comm.go
vendor/github.com/libp2p/go-libp2p-pubsub/gossipsub.go
vendor/github.com/libp2p/go-libp2p-pubsub/notify.go
vendor/github.com/libp2p/go-libp2p-pubsub/package.json
vendor/github.com/libp2p/go-libp2p-pubsub/pubsub.go
vendor/github.com/multiformats/go-multiaddr/README.md
vendor/github.com/multiformats/go-multiaddr/codec.go
vendor/github.com/multiformats/go-multiaddr/component.go
vendor/github.com/multiformats/go-multiaddr/interface.go
vendor/github.com/multiformats/go-multiaddr/multiaddr.go
vendor/github.com/multiformats/go-multiaddr/package.json
vendor/github.com/multiformats/go-multiaddr/protocol.go
vendor/github.com/multiformats/go-multiaddr/protocols.go
vendor/github.com/multiformats/go-multiaddr/transcoders.go
vendor/github.com/multiformats/go-multiaddr/util.go
vendor/github.com/multiformats/go-multiaddr/varint.go

unit tested
not breaking anything

bump libp2p versions

---

consensus/scheme/rolldpos/rolldpos_test.go
tools/actioninjector.v2/injector.go
tools/actioninjector.v2/internal/client/client.go
tools/actioninjector.v2/internal/cmd/random.go
tools/actioninjector.v2/internal/cmd/root.go

add action injector for grpc.
- simplified code.
- removed injection for vote

add grpc action injector

---

Gopkg.lock
api/api.go
vendor/github.com/grpc-ecosystem/go-grpc-prometheus/.gitignore
vendor/github.com/grpc-ecosystem/go-grpc-prometheus/.travis.yml
vendor/github.com/grpc-ecosystem/go-grpc-prometheus/CHANGELOG.md
vendor/github.com/grpc-ecosystem/go-grpc-prometheus/LICENSE
vendor/github.com/grpc-ecosystem/go-grpc-prometheus/README.md
vendor/github.com/grpc-ecosystem/go-grpc-prometheus/client.go
vendor/github.com/grpc-ecosystem/go-grpc-prometheus/client_metrics.go
vendor/github.com/grpc-ecosystem/go-grpc-prometheus/client_reporter.go
vendor/github.com/grpc-ecosystem/go-grpc-prometheus/makefile
vendor/github.com/grpc-ecosystem/go-grpc-prometheus/metric_options.go
vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server.go
vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_metrics.go
vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_reporter.go
vendor/github.com/grpc-ecosystem/go-grpc-prometheus/util.go

now we can get api prometheus metrics easily
https://github.com/grpc-ecosystem/go-grpc-prometheus

add grpc prometheus adopter

---

tools/actioninjector.v2/internal/client/client_test.go

add client_test in actioninjector.v2

add client_test in actioninjector.v2

---

cli/ioctl/README.md
cli/ioctl/cmd/bc/bc.go
cli/ioctl/cmd/bc/bcheight.go
cli/ioctl/cmd/root.go

add bc cmd

---

.codecov.yml

Lower the codecov bar to avoid always showing the unhealthy build status

---

consensus/consensusfsm/fsm.go
consensus/consensusfsm/fsm_test.go

1. Add sPrepare->eCalibrate as an invalid transition
2. Add unit test for this case

add more test for calibrate

---

blockchain/block/block.go
blockchain/block/builder.go
blockchain/block/builder_test.go
blockchain/block/runnable.go
blockchain/blockchain.go
blockchain/genesis_test.go
cli/ioctl/cmd/account/accountcreate.go
config/config.go
config/config_test.go
consensus/consensus.go
consensus/consensusfsm/fsm.go
consensus/consensusfsm/fsm_test.go
e2etest/local_actpool_test.go
e2etest/local_test.go
e2etest/multichain_test.go
e2etest/rewarding_test.go
indexservice/server.go
server/main.go
tools/minicluster/minicluster.go

It will break config. Verified in the cluster

Remove PK from config and producing a block

---

cli/ioctl/cmd/config/config.go
cli/ioctl/cmd/config/configendpoint.go
cli/ioctl/cmd/wallet/wallet.go
cli/ioctl/cmd/wallet/walletcreate.go
cli/ioctl/cmd/wallet/walletlist.go

Test wallet create and wallet list locally

Use yaml schema instead of self defined schema to organize config file

---

e2etest/local_transfer_test.go

Increase block generation speed to reduce local transfer test in e2etest suite.

Increase local transfer test speed

---

cli/ioctl/README.md
cli/ioctl/cmd/node/node.go
cli/ioctl/cmd/node/nodedelegate.go
cli/ioctl/cmd/root.go

Add nodeDelegateCmd for ioctl and clean up for bcHeightCmd
teseted on local single-node
➜  ioctl git:(ioctl) ✗ ./ioctl node delegate
blockProducers: "io1juvx5g063eu4ts832nukp4vgcwk2gnc5cu9ayd"
blockProducers: "io1llupp3n8q5x8usnr5w08j6hc6hn55x64l46rr7"
blockProducers: "io1hh97f273nhxcq8ajzcpujtt7p9pqyndfmavn9r"
blockProducers: "io1ph0u2psnd7muq5xv9623rmxdsxc4uapxhzpg02"
blockProducers: "io19kshh892255x4h5ularvr3q3al2v8cgl80fqrt"
blockProducers: "io1fxzh50pa6qc6x5cprgmgw4qrp5vw97zk5pxt3q"
blockProducers: "io1xuavja5dwde8pvy4yms06yyncad4yavghjhwra"
blockProducers: "io1eq4ehs6xx6zj9gcsax7h3qydwlxut9xcfcjras"
blockProducers: "io13sj9mzpewn25ymheukte4v39hvjdtrfp00mlyv"
blockProducers: "io158hyzrmf4a8xll7gfc8xnwlv70jgp44tzy5nvd"
blockProducers: "io1jh0ekmccywfkmj7e8qsuzsupnlk3w5337hjjg2" …

Add nodeDelegateCmd for ioctl

---

cli/ioctl/cmd/account/account.go
cli/ioctl/cmd/account/accountbalance.go
cli/ioctl/cmd/account/accountnonce.go
cli/ioctl/cmd/action/action.go
cli/ioctl/cmd/action/actiondeploy.go
cli/ioctl/cmd/action/actioninvoke.go
cli/ioctl/cmd/action/actiontransfer.go
cli/ioctl/validator/validator.go

tested on local single-node
➜  ioctl git:(ioctl) ✗ ./ioctl account list
name: boss, address:io1llupp3n8q5x8usnr5w08j6hc6hn55x64l46rr7
name: fake, address:io1xje007qlk8apvg3y5ps4lr3y7ke8zy5vrpgsgf
➜  ioctl git:(ioctl) ✗ ./ioctl account balance boss
io1llupp3n8q5x8usnr5w08j6hc6hn55x64l46rr7: 100000000000000000000000000
➜  ioctl git:(ioctl) ✗ ./ioctl action transfer fake 123132123 ILILILILLIL -s boss -l 40000 -p 765
Enter password #boss:
Action has been sent to blockchain.
Wait for several seconds and query this action by hash:
6aa1a7c0c33e003f2354e99e9836337e718bd4d99306108bc47bd993b1d713bc
➜  ioctl git:(ioctl) ✗ ./ioctl action hash 6aa1a7c0c33e003f2354e99e9836337e718bd4d99306108bc47bd993b1d713bc
senderAddress: io1llupp3n8q5x8usnr5w08j6hc6hn55x64l46rr7
version: 1
nonce: 1
gasLimit: 40000 …

Support address alias for all ioctl cmd

---

.circleci/config.yml
go.test.sh

#630 makes it hard to access the test logs.

Revert PR 646 and PR 630

---

cli/ioctl/cmd/account/account.go
cli/ioctl/cmd/account/accountimport.go

IOTEX-316 silent private key importing for ioctl

---

blockchain/genesis/genesis.go
chainservice/chainservice.go

Move GravityChainHeightInterval to genesis

---

config/config.go
e2etest/config_local_delegate.yaml
pkg/log/log.go
pkg/probe/probe.go
server/itx/server.go
server/main.go
tools/minicluster/minicluster.go

- combine metrics and probe port
- move log config and pprof to admin port

combine metrics and probe port

---

cli/ioctl/cmd/account/account.go
cli/ioctl/cmd/account/accountupdate.go

account update cmd can be used for changing password of account.

Add account update cmd for ioctl

---

Makefile
cli/ioctl/buildcli.sh

Add ioctl target in Makefile and use flag to add version info in buildcli.sh.

Add ioctl target and add version info in buildcli.sh

---

blockchain/blockchain.go

IOTEX-358 Fix pulling delegate productivity

---

action/protocol/execution/evm/evm.go
consensus/scheme/rolldpos/rolldposctx.go
dispatcher/dispatcher.go

Lock endorsement shouldn't be generated if block hash is nil

fix producing lock endorsement on nil

---

e2etest/local_actpool_test.go
e2etest/local_test.go
p2p/agent.go
p2p/agent_test.go
server/itx/server.go

Note that this will not block malicious nodes

Make P2P care about the messages from the honest nodes using the same genesis

---

cli/ioctl/cmd/update/update.go
install-cli.sh

Add sudo for ioctl install

---

action/protocol/account/transfer.go
action/protocol/vote/protocol.go
api/api_test.go

Add action hash to receipt so that receipt can be fetched by hash.

Add action hash and status to transfer receipt and vote receipt

---

cli/ioctl/cmd/action/actionclaim.go
cli/ioctl/cmd/action/actiontransfer.go

IOTEX-367 Move data as optional input for ioctl

---

e2etest/local_transfer_test.go

To make sure all test accounts are created during height = 0

Increase TestLocalTransfer block interval time 

---

consensus/consensusfsm/fsm_test.go
consensus/scheme/rolldpos/rolldpos.go

If message height is higher than consensus height + 1, ignore the message. Add a few consensus unit tests

ignore consensus message if sync is in process

---

cli/ioctl/cmd/action/actionhash.go
cli/ioctl/cmd/bc/bcblock.go

`Producer Public Key` should be `Producer Address`

Fix block cmd

---

tools/minicluster/minicluster.go
tools/util/injectorutil.go

to enable to debug nightly build balance check failure

Add more logs and disable execution injection for minicluster

---

cli/ioctl/cmd/alias/aliaslist.go

Sort alias list when print

---

.gitignore

Git ignore release dir

---

blockchain/blockdao_test.go
cli/ioctl/cmd/account/account_test.go
db/sql/sqlite3_test.go

Removed hardcoded Tempfile in few more test files #615

---

Makefile

Shrink ioctl binary

---

action/protocol/execution/evm/evm.go
action/protocol/execution/protocol_test.go
action/protocol/execution/testdata/changestate.json
action/protocol/execution/testdata/changestate.sol
action/protocol/execution/testdata/infiniteloop.json

Add changestate test for execute protocol.

IOTEX-371 Add execute test

---

cli/ioctl/cmd/account/accountbalance.go
cli/ioctl/cmd/account/accountcreate.go
cli/ioctl/cmd/account/accountcreateadd.go
cli/ioctl/cmd/account/accountdelete.go
cli/ioctl/cmd/account/accountexport.go
cli/ioctl/cmd/account/accountimport.go
cli/ioctl/cmd/account/accountlist.go
cli/ioctl/cmd/account/accountnonce.go
cli/ioctl/cmd/account/accountupdate.go
cli/ioctl/cmd/action/actionclaim.go
cli/ioctl/cmd/action/actiondeploy.go
cli/ioctl/cmd/action/actionhash.go
cli/ioctl/cmd/action/actioninvoke.go
cli/ioctl/cmd/action/actiontransfer.go
cli/ioctl/cmd/alias/aliasremove.go
cli/ioctl/cmd/alias/aliasset.go
cli/ioctl/cmd/bc/bcblock.go
cli/ioctl/cmd/bc/bcinfo.go
cli/ioctl/cmd/config/configsetget.go
cli/ioctl/cmd/node/nodedelegate.go
cli/ioctl/cmd/node/nodereward.go
cli/ioctl/cmd/update/update.go
cli/ioctl/cmd/version/version.go

Use fmt.Println() rather than println().

Fix stderr error

---

config/config.go
consensus/consensus.go
consensus/consensusfsm/fsm_test.go
consensus/scheme/noop.go
consensus/scheme/rolldpos/rolldpos.go
consensus/scheme/rolldpos/rolldposctx.go
pkg/log/log.go
server/main.go

1. Less consensus message
2. The consensus logging could be controlled with 
```curl -X PUT -d '{"level":"debug"}' localhost:9009/logging/consensus```
3. More details will be shown in debug mode

add separate logging for consensus

---

p2p/agent.go

change the logic from connect to at least 1 bootnode to more than 50% bootnodes

connect to more than 50% of boot node

---

cli/ioctl/cmd/account/account.go
cli/ioctl/cmd/account/accountethaddr.go

Add account ethaddr cmd

---

cli/ioctl/cmd/account/account.go
cli/ioctl/cmd/action/action.go
cli/ioctl/cmd/alias/aliasexport.go
cli/ioctl/cmd/bc/bc.go
cli/ioctl/cmd/node/node.go

Add an endpoint flag and fix a flag mistake

---

Gopkg.lock
pkg/probe/probe.go
pkg/util/httputil/httputil.go
pkg/util/netutil/netutil.go
server/itx/server.go
vendor/golang.org/x/net/netutil/listen.go

add max number of connection limit to http servers too 400 connections

add max number of connection limit to http servers

---

action/protocol/execution/testdata/cashier.json

Add unit test for smart contract fallback function

add test for fallback function

---

action/protocol/execution/protocol_test.go
action/protocol/execution/testdata/infiniteloop.json

Fix early return in protocol_test.go

---

cli/ioctl/cmd/account/account.go
cli/ioctl/cmd/action/action.go
cli/ioctl/cmd/action/actionhash.go
cli/ioctl/cmd/bc/bc.go
cli/ioctl/cmd/bc/bcblock.go
cli/ioctl/cmd/config/config.go
cli/ioctl/cmd/node/node.go
cli/ioctl/cmd/node/nodedelegate.go
cli/ioctl/cmd/node/nodereward.go
cli/ioctl/cmd/version/version.go
cli/ioctl/util/util.go

ioctl connects endpoint with TLS by default and add insecure flag

---

action/protocol/account/transfer.go
action/protocol/account/transfer_test.go

Unit test verified that the nonce is increased and gas charged is correct.

add nonce on transfer failure and add unit tests

---

cli/ioctl/cmd/account/account.go
cli/ioctl/cmd/action/action.go
cli/ioctl/cmd/action/actionhash.go
cli/ioctl/cmd/bc/bc.go
cli/ioctl/cmd/bc/bcblock.go
cli/ioctl/cmd/config/config.go
cli/ioctl/cmd/config/configsetget.go
cli/ioctl/cmd/node/node.go
cli/ioctl/cmd/node/nodedelegate.go
cli/ioctl/cmd/node/nodereward.go
cli/ioctl/cmd/version/version.go
cli/ioctl/util/util.go

Add secureConnect config for ioctl

---

cli/ioctl/cmd/account/accountdelete.go

delete cmd will delete both private key and address alias.
#1067

Update account delete cmd for ioctl

---

api/api_test.go
blockchain/blockchain.go
blockchain/blockchain_test.go
consensus/scheme/rolldpos/rolldpos_test.go
explorer/explorer_test.go
gasstation/gasstattion_test.go

This reverts commit fd846ab4ce3d867b5b038f09e1978b9cee64b43a.

Revert "Add a memorial transfer into the first block (#1065)"

---

.circleci/circleci_github_release.sh
.circleci/config.yml
.travis.yml
install-bookkeeper.sh

#1010
1, circleci add Environment Variables --> GITHUB_TOKEN ( Write Privilege)
2, cp "circleci_github_release.sh" yout local computer --> change CIRCLE_TOKEN="<YOUR_ACCESS_TOKEN>"
3, Use: sh circleci_github_release.sh -v "v0.5.1-rc4" [-b "branch"]

Automatically published release , travis test windows , bookkeeper tools install

---

action/protocol/execution/protocol_test.go
action/protocol/multichain/mainchain/protocol_test.go
action/protocol/multichain/mainchain/startsubchain_test.go
blockchain/blockchain_test.go
consensus/consensusfsm/fsm_test.go
db/trie/trie_test.go
gasstation/gasstattion_test.go

Fix unexpected blockchain stop before finishing the contract tests

---

Makefile
action/transfer_test.go
actpool/actpool_test.go
api/api.go
api/api_test.go
blockchain/blockchain_test.go
blocksync/blocksync_test.go
chainservice/chainservice.go
cli/ioctl/cmd/account/accountimport.go
consensus/consensusfsm/fsm_test.go
consensus/scheme/rolldpos/rolldpos.go
consensus/scheme/rolldpos/rolldpos_test.go
db/db_badger.go
db/db_test.go
state/factory/factory_test.go
state/factory/statedb.go

Fix lint-rich warnings #681 first batch

---

action/protocol/poll/protocol_test.go

iotexAdd unit tests for protocol_test.go #638

---

cli/ioctl/cmd/action/action.go
cli/ioctl/cmd/action/actionclaim.go
cli/ioctl/cmd/action/actiondeploy.go
cli/ioctl/cmd/action/actiondeposit.go
cli/ioctl/cmd/action/actionread.go
cli/ioctl/cmd/action/actiontransfer.go

action invoke returns the hash, action hash returns receipt of execution
add 'action read' command which runs ReadContract() and returns the result on command line
Testing plan:
make test

Add ioctl action read command to read contract

---

e2etest/local_transfer_test.go

fix e2etest/local_transfer_test.go doesn't stop prob server

---

e2etest/rewarding_test.go

.Increase block interval
. Disable Async index write

Fix Sporadic TestBlockEpochReward failure #1173

---

action/protocol/poll/protocol.go

work on https://github.com/iotexproject/iotex-election/issues/64

Downgrade the logs of showing the invalid operator/reward address. #64

---

consensus/consensusfsm/fsm.go
consensus/scheme/rolldpos/rolldposctx.go
go.mod

Add the consensus metrics to help decision make of shortening block interval

Improve consensus metrics

---

api/api.go

https://github.com/iotexproject/iotex-core/issues/1185

Reverse the order of db queries in GetActionsByIndex API

---

blockchain/genesis/genesis.go

Update pacific block height

---

action/protocol/poll/protocol.go
action/protocol/poll/protocol_test.go
api/api_test.go
blockchain/blockchain.go
config/config.go
go.mod
go.sum
server/itx/server.go

work on #1194
According to #1210 (review)
First fixs poll protocol initializes.
Tests in my local computer shows that wait for about 6 minutes util initialize ok

Node crash after moving to iotex-election 0.1.10 #1194

---

.circleci/config.yml

enable nightly_bin_build_darwin

---

blockchain/blockdao.go
blockchain/indexbuilder.go
chainservice/chainservice.go

Move total actions count from index service to basic block store #1234

---

README.md

Add the reference to iip

---

api/api.go

change GetChainMeta api Response

---

server/itx/heartbeat_test.go

https://github.com/iotexproject/iotex-core/issues/1269
Unblock tests

Skip TestNewHeartbeatHandler because of data race

---

consensus/scheme/rolldpos/rolldpos.go
consensus/scheme/rolldpos/rolldposctx.go

The two metrics were removed accidentally. Add it back as people are asking for them.

Revive two consensus metrics

---

cli/ioctl/cmd/action/xrc20transfer.go

In latest version of xrc20 function, the description of transfer command is wrong, now I modify it.

change some comment

---

action/action.go
action/claimreward.go
action/createdeposit.go
action/depositreward.go
action/execution.go
action/grantreward.go
action/putblock.go
action/putblock_test.go
action/putpollresult.go
action/settledeposit.go
action/startsubchain.go
action/stopsubchain.go
action/transfer.go
action/transfer_test.go
blockchain/block/block_test.go
blockchain/block/header.go

Conform the serialize/deserialize methods in the codebase #1250

---

blockchain/block/header.go
blockchain/blockchain_test.go

pls focus on 2nd commit, the first commit is just remove/refactor duplicate code

Test coverage for bloom filter and duplicate topic fix

---

action/protocol/poll/protocol.go
config/config.go

Node takes a while to get the first eth data committed 1294

---

action/const.go
action/protocol/context.go
action/protocol/context_test.go
action/protocol/execution/evm/evm.go
action/protocol/execution/protocol_test.go
action/protocol/generic_validator.go
action/protocol/generic_validator_test.go
action/protocol/multichain/mainchain/protocol_test.go
actpool/actpool_test.go
api/api.go
api/api_test.go
blockchain/blockchain.go
blockchain/blockchain_test.go
blockchain/blockdao_test.go
blockchain/blockvalidator.go
blockchain/blockvalidator_test.go
blocksync/blocksync_test.go
blocksync/buffer_test.go
cli/ioctl/cmd/action/actionread.go
consensus/scheme/rolldpos/rolldpos_test.go
e2etest/bigint_test.go
e2etest/local_test.go
gasstation/gasstattion.go
gasstation/gasstattion_test.go
server/itx/server.go
tools/executiontester/executiontester.go
tools/minicluster/minicluster.go

Implement: https://github.com/iotexproject/iips/blob/master/iip-3.md

Remove per action gas limit cap

---

go.mod
p2p/agent_test.go

Sporadic TestBroadcast failure 1298

---

action/protocol/rewarding/admin.go
action/protocol/rewarding/admin_test.go
api/api_test.go
blockchain/blockchain.go
blockchain/genesis/genesis.go
blockchain/genesis/genesis_test.go

Implementation of https://github.com/iotexproject/iips/blob/master/iip-2.md
Also, cleanup some default rewarding settings in genesis.go, to make it consistent with the number we used in mainnet.

Change epoch reward from 12.5K to 15K

---

consensus/scheme/rolldpos/rolldpos_test.go
consensus/scheme/rolldpos/rolldposctx.go
e2etest/rewarding_test.go

work on #1288
fix all test fail when run make test

Flaky rolldpos test

---

ioctl/cmd/alias/aliasimport.go
ioctl/cmd/alias/aliasset.go

tested on windows and centos
#1339

Fix multi-aliases bug

---

config/config_test.go

Fix TestNewConfigWithWrongConfigPath for windows

---

actpool/actpool_test.go

Revive test coverage 1140

---

go.mod

Make crypto computation tolerate client heterogeneity 1320

---

blockchain/genesis/genesis.go

According to https://member.iotex.io/polls

Increase epoch reward to 18,750 IOTX

---

go.mod
go.sum
ioctl/cmd/alias/alias.go
ioctl/cmd/alias/alias_test.go
ioctl/cmd/alias/aliasexport.go
ioctl/cmd/alias/aliasimport.go
ioctl/cmd/alias/aliaslist.go
ioctl/cmd/alias/aliasremove.go
ioctl/cmd/alias/aliasset.go
ioctl/cmd/version/version.go
ioctl/output/format.go

 Format output for alias Cmds

---

api/api.go
api/api_test.go
go.mod

work on #1024
example:
grpcurl -v -plaintext -d '{"execution": {"amount": "0", "contract": "","data":"YIBgQFI0gBVhABBXYACA/VtQYQEjYAECYAKBYAAZFpBVUDNz//////////////////////////8WYAECYAOBYAAZFpBVUGADVGACVBdgBIFgABkWkFVQYQKugGEAZWAAOWAA8wBggGBAUmAENhBhAHhXYAA1fAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkARj/////xaAYwzA4fsUYQB9V4BjKPNxqhRhALBXgGNrHXUrFGEA31eAY9S4OZIUYQESV4Bj2uqFxRRhAUVXgGPrb9lqFGEBiFdbYACA/Vs0gBVhAIlXYACA/VtQYQCSYQG7VltgQFGAgmAAGRZgABkWgVJgIAGRUFBgQFGAkQOQ81s0gBVhALxXYACA/VtQYQDFYQHBVltgQFGAghUVFRWBUmAgAZFQUGBAUYCRA5DzWzSAFWEA61dgAID9W1BhAPRhAddWW2BAUYCCYAAZFmAAGRaBUmAgAZFQUGBAUYCRA5DzWzSAFWEBHldgAID9W1BhASdhAd1WW2BAUYCCYAAZFmAAGRaBUmAgAZFQUGBAUYCRA5DzWzSAFWEBUVdgAID9W1BhAYZgBIA2A4EBkICANXP//////////////////////////xaQYCABkJKRkFBQUGEB41ZbAFs0gBVhAZRXYACA/VtQYQGdYQJ8VltgQFGAgmAAGR …

estimate gas for deploy contract is zero 1024

---

api/api.go
api/api_test.go
go.mod
ioctl/cmd/bc/bcinfo.go

fix tps in chainmeta api 1363

---

blockchain/genesis/genesis.go
go.mod
go.sum

it should happen about 20 days later

Update AleutianBlockHeight to 864001

---

go.mod
ioctl/cmd/action/action.go
ioctl/cmd/action/actionclaim.go
ioctl/cmd/action/actiondeploy.go
ioctl/cmd/action/actiondeposit.go
ioctl/cmd/action/actioninvoke.go
ioctl/cmd/action/actiontransfer.go
ioctl/cmd/action/xrc20approve.go
ioctl/cmd/action/xrc20transfer.go
ioctl/cmd/action/xrc20transferfrom.go
ioctl/flag/flag.go

#1362 
Tested on centos.
Test fails on windows due to #1365

Add passwordFlag(-P) and yesFlag(-y) for ioctl

---

ioctl/cmd/account/accountgetvotes.go
ioctl/cmd/bc/bc.go
ioctl/cmd/bc/bcblock.go
ioctl/cmd/bc/bcinfo.go
ioctl/cmd/config/config.go
ioctl/cmd/config/configsetget.go
ioctl/cmd/node/node.go
ioctl/cmd/node/nodedelegate.go
ioctl/cmd/node/nodereward.go

Format output for node and config cmds

---

consensus/scheme/rolldpos/rolldposctx.go
server/itx/heartbeat.go

I added iotex_consensus_height metric and modify the heartbeat.go to log the consensus metrics
works on #1389

Add iotex_consensus_height metric and Modify the heartbeat (#1389) 

---

ioctl/cmd/account/accountbalance.go
ioctl/cmd/account/accountdelete.go
ioctl/cmd/account/accountexport.go
ioctl/cmd/account/accountexportpublic.go
ioctl/cmd/account/accountnonce.go
ioctl/cmd/account/accountupdate.go

Tested on CentOS and Windows. #1409

Fix ioctl args problem

---

action/protocol/execution/protocol_test.go
action/protocol/execution/testdata/wireconnection.json
action/protocol/execution/testdata/wireconnection.sol

added a unit test to verify the problem which might cause #1422

Add wireconnection unit test to verify smart contract deployment issue

---

api/api.go
api/api_test.go
go.mod
go.sum

works on #1444 
added logsbloom field in blockmeta

Logsbloom in blockmeta

---

config/config.go

set SplitDBSizeMB default to 0

---

blockchain/blockchain.go
blockchain/blockvalidator.go
blockchain/blockvalidator_test.go

Check blacklist when processing a block #1464

---

go.mod
state/tracker/balancechange.go

There's build and run error after 1471

---

blockchain/blockchain.go
blockchain/blockvalidator_test.go
consensus/scheme/rolldpos/endorsementmanager.go
consensus/scheme/rolldpos/endorsementmanager_test.go

fixed bugs in the endorsementManager cleanup, and added unit tests

eManager cleanup

---

server/itx/heartbeat_test.go

TestNewHeartbeatHandler sporadic failure 1484

---

action/protocol/poll/staking_committee.go
chainservice/chainservice.go
server/itx/server.go
state/candidate.go

Fix three issues related to new poll protocol:
1. Validate function should use the new protocol
2. After bering height, the native staking shouldn't be nil
3. Score threshold filtering happens in iotex-core

Fix new poll protocol

---

action/protocol/poll/staking_committee.go
action/protocol/protocol.go
blockchain/blockchain.go
consensus/consensus.go
consensus/scheme/rolldpos/rolldpos.go
consensus/scheme/rolldpos/rolldpos_test.go
consensus/scheme/rolldpos/rolldposctx.go
consensus/scheme/rolldpos/roundcalculator.go

make chainmanager interface for consensus

---

p2p/agent.go

add a lru cache to avoid bad unicast connection

---

action/protocol/poll/nativestaking.go
action/protocol/poll/staking_committee.go
chainservice/chainservice.go

Sort merged result with util.Sort implemented in iotex-election

sort merged result

---

api/apitestclient.go
go.sum
test/mock/mock_apiserviceclient/mock_apiserviceclient.go

According to change of iotex-proto, api service client interface and mock api client service have to be updated for compatibility

update api service client interface 

---

api/api.go
api/api_test.go
blockchain/blockdao/blockdao.go

Fix a bug in getActionsByAddress

---

action/protocol/rolldpos/epoch.go
blockchain/blockchain.go
blockchain/genesis/genesis.go
chainservice/chainservice.go
config/config.go
config/heightupgrade.go
consensus/consensusfsm/consensus_ttl.go

we name our fork height alphabetically by famous landmarks in Pacific ocean, this time cannot find a good name starting with 'D', so use the Dardanelles strait which connects sea of Marmara to Mediterranean sea

rename Hudson to Dardanelles

---

action/protocol/poll/protocol.go
chainservice/chainservice.go
server/itx/server.go

1. move registerDefaultProtocols() and adding action validators into chainservice New() 
2. make newProtocol function in poll protocol

move registerProtocols from server to chainservice

---

.golangci.yml

wsl is annoying now.
try some diff rule setup

try to change golangci rules

---

api/api.go
blockchain/blockchain.go

Work on https://github.com/iotexproject/iotex-core/issues/1609

Modify EstimateActionGasConsumption API

---

Makefile

Fix Makefile to erase index.db

fix Makefile to erase index.db 

---

action/protocol/context.go
action/protocol/context_test.go

works on #1689 
First, define the new contexts which are classified by their groups

definition of splitted contexts

---

api/api.go
blockindex/indexer.go
blockindex/indexer_test.go
db/counting_index.go
db/counting_index_test.go
db/db.go
db/db_bolt.go
db/kvstore_bucketfill.go

1. implement CountingIndex API using KVStore API
2. CreateCountingIndexNX becomes CreateCountingIndexNX(KVStore, name)

decouple CountingIndex from KVStore interface

---

action/protocol/context.go
action/protocol/execution/protocol_test.go
action/protocol/generic_validator_test.go
action/protocol/managers.go
action/protocol/poll/nativestaking.go
action/protocol/poll/nativestaking_test.go
action/protocol/poll/protocol.go
action/protocol/poll/staking_committee.go
api/api.go
api/api_test.go
blockchain/blockchain.go
blockchain/blockchain_test.go
blockchain/blockvalidator.go
blockchain/blockvalidator_test.go
chainservice/chainservice.go
gasstation/gasstattion.go
state/factory/util.go
test/mock/mock_blockchain/mock_blockchain.go
test/mock/mock_chainmanager/mock_chainmanager.go

Move SimulateExecution from blockchain to factory

Move simulation to factory

---

action/protocol/execution/protocol_test.go
actpool/actpool_test.go
api/api.go
api/api_test.go
blockchain/blockchain.go
blockchain/blockchain_test.go
blockchain/blockvalidator_test.go
consensus/scheme/rolldpos/rolldpos_test.go
e2etest/bigint_test.go
e2etest/rewarding_test.go
state/factory/factory.go
state/factory/factory_test.go
state/factory/statedb.go
state/factory/statetx.go
state/factory/util.go
state/factory/workingset.go
test/mock/mock_factory/mock_factory.go

remove actionHandlers in WorkingSet and pass registry through runActionsCtx

remove actionhandlers in workingset and pass registry through context

---

crypto/cryptosort.go
crypto/cryptosort_test.go

add test for SortCandidates and improve SortCandidates func

---

blockchain/blockdao/blockdao.go
blockindex/indexer.go
db/counting_index.go
db/db.go
db/db_bolt.go
db/range_index.go
db/range_index_test.go
state/factory/statetx.go

test plan:
make test && make minicluster

decouple RangeIndex from KVStore interface

---

misc/scripts/mockgen.sh

fix mockgen issue

---

action/protocol/poll/staking_committee.go

fix bug for #1735

---

action/protocol/execution/evm/evmstatedbadapter_test.go
blockchain/blockdao/blockdao.go
blockindex/indexer.go
db/counting_index.go
db/db.go
db/db_bolt.go
db/db_test.go
db/kvstore4trie.go
state/factory/statetx.go
state/factory/workingset.go

Rename KVStore.Commit to KVStore.WriteBatch

rename Commit to WriteBatch

---

action/protocol/protocol.go

issue: https://github.com/iotexproject/iotex-core/issues/1621

update description of ActionEnvelopeValidator interface

---

action/protocol/execution/evm/evmstatedbadapter_test.go
api/logfilter_test.go
blockchain/blockchain_test.go
blockchain/blockdao/indexbuilder_test.go
blockindex/index_test.go
consensus/scheme/rolldpos/rolldposctx.go
db/range_index_test.go
state/candidate_test.go

#1721 
It has been deleted by mistake.

investigate and fix go reports complaints

---

action/protocol/poll/staking_committee.go
blockchain/blockchain.go
blockchain/blockvalidator.go
blockchain/blockvalidator_test.go
state/factory/factory.go
state/factory/statedb.go
test/mock/mock_factory/mock_factory.go

1. To wrap workingSet into state factory, first move RunActions to state factory 
2. changed blockValidator unit test accordingly

move RunActions to state factory

---

chainservice/chainservice.go
e2etest/local_transfer_test.go
e2etest/rewarding_test.go

In Standalone mode, we cannot get the productivity by epoch. Updating the unit test TestBlockReward to RollDPoSScheme, and add a delay to TestLocalTransfer.

fix rewarding bug #1750 #1759

---

action/protocol/execution/protocol_test.go
actpool/actpool.go
actpool/actpool_test.go
actpool/actqueue.go
actpool/actqueue_test.go
api/api.go
api/api_test.go
blockchain/blockchain.go
blockchain/blockchain_test.go
blockchain/blockvalidator_test.go
blocksync/blocksync_test.go
blocksync/buffer_test.go
chainservice/chainservice.go
consensus/scheme/rolldpos/rolldpos_test.go
consensus/scheme/rolldpos/rolldposctx_test.go
consensus/scheme/rolldpos/roundcalculator_test.go
e2etest/bigint_test.go
e2etest/local_test.go
e2etest/local_transfer_test.go
e2etest/rewarding_test.go
gasstation/gasstattion.go
gasstation/gasstattion_test.go
test/mock/mock_blockchain/mock_blockchain.go
tools/actioninjector.v2/internal/client/client_test.go
tools/minicluster/minicluster.go
tools/staterecoverer/staterecoverer.go

works on #1601  
remove Factory() API from blockchain and use state factory directly (not through the bc) 
next step is remove BlockDAO() same as here

Remove Factory() from blockchain

---

action/protocol/account/transfer_test.go
action/protocol/execution/protocol_test.go
action/protocol/rewarding/protocol.go
action/protocol/rewarding/protocol_test.go
action/protocol/rewarding/reward.go
action/protocol/rewarding/reward_test.go
api/api_test.go
blockchain/blockchain_test.go
chainservice/chainservice.go
consensus/scheme/rolldpos/roundcalculator_test.go
e2etest/bigint_test.go
e2etest/local_test.go
gasstation/gasstattion_test.go

works on #1781 
try not to pass rolldpos protocol directly, but through the context registry

Change to pass rolldpos protocol through context

---

go.sum
ioctl/util/util.go

fix ioctl's secret read on Windows

---

action/protocol/poll/governance_protocol.go
action/protocol/poll/governance_protocol_test.go
action/protocol/poll/lifelong_protocol.go
action/protocol/poll/lifelong_protocol_test.go
action/protocol/poll/protocol.go
action/protocol/poll/protocol_test.go
action/protocol/poll/staking_committee.go
action/protocol/poll/util.go

works on #1766 
1. split poll protocol.go -> protocol/ governance_protocol/ lifelong_protocol /util file 
2. split unit test files -> protocol_test/ governanace_protocol/ lifelong_protocol 
3. refactor NewProtocol() in poll protocol

split poll protocol files and unit tests

---

Dockerfile
tools/bot/Dockerfile

bump our go version to 1.13.5

---

blockchain/blockchain.go
blockchain/blockdao/blockdao.go
blockchain/blockdao/blockdao_test.go
blockchain/blockdao/indexbuilder.go
blockchain/blockdao/indexbuilder_test.go
test/mock/mock_blockdao/mock_blockdao.go

Move blockchain.tipHash, tipHeight into blockdao 1779

---

api/api.go
blockchain/blockchain.go
blockchain/blockchain_test.go
blockchain/blockdao/blockdao.go

Move HeaderByXXX FooterByXXX implementation logic into block.DAO 1815

---

.circleci/config.yml

Reverts iotexproject/iotex-core#1807

Revert "change build ioctl new dir"

---

blockchain/blockchain.go
blockchain/blockminter.go
blockchain/blockminter_test.go

Just like blockValidator, create blockMinter and move mintNewBlock logic from blockchain

Create blockminter 

---

blockchain/blockdao/indexbuilder.go
go.mod
go.sum
ioctl/cmd/account/account.go
ioctl/cmd/account/account_test.go
ioctl/cmd/account/accountimport.go

//TODO: implement load/store to PEM file

ioctl change for new key support

---

go.mod
go.sum

try to remove bad dependency xerror 0421b64034aa to fix build

try to fix build

---

ioctl/client.go
ioctl/newcmd/alias/aliaslist.go
ioctl/newcmd/alias/aliaslist_test.go

add new ioctl alias list command and test

---

.circleci/config.yml

change docker golang version for nightly build

---

action/protocol/staking/protocol.go
go.mod
go.sum

1. update proto package
2. add skeleton for staking protocol, implementation to be done

add staking protocol and update proto package for staking message

---

ioctl/client.go
ioctl/newcmd/update/update.go
ioctl/newcmd/update/update_test.go
test/mock/mock_ioctlclient/mock_ioctlclient.go

The previous unit test failed.

fix new ioctl update command

---

action/protocol/vote/candidatesutil/candidatesutil.go

Failed to sync block from start in testnet

---

blockchain/genesis/genesis.go
consensus/consensus.go
consensus/scheme/rolldpos/rolldposctx_test.go
consensus/scheme/rolldpos/roundcalculator.go
consensus/scheme/rolldpos/roundcalculator_test.go

should pass genesis through context when get Delegates()

fix bug to include genesis in a context 

---

action/protocol/account/util/util.go
action/protocol/managers.go
state/factory/factory.go
state/factory/statedb.go
state/factory/statetx.go
state/factory/workingset.go
test/mock/mock_chainmanager/mock_chainmanager.go
test/mock/mock_factory/mock_factory.go
test/mock/mock_factory/mock_workingset.go

implement StateAtHeight() as an option 1869

---

action/protocol/staking/vote_bucket.go
action/protocol/staking/vote_bucket_test.go
state/factory/factory.go
state/factory/statedb.go

3 APIs for staking protocol for create, get, delete voting bucket
stakingGetBucket, stakingPutBucket, stakingDelBucket

add stakingGet/Put/DelBucket API

---

action/protocol/poll/util.go
action/protocol/vote/candidatesutil/candidatesutil.go

The db operation is redundant, but to be backward compatible, add it back for pre-easter blocks.

fix backward compatible bug

---

action/stake_adddeposit.go
action/stake_move.go
action/stake_reclaim.go
action/stake_restake.go
action/stakeadddeposit_test.go
action/stakecreate_test.go
action/stakemove_test.go
action/stakereclaim_test.go
action/stakerestake_test.go

add unit test for action/stake_xxx.go 1903

---

action/protocol/poll/governance_protocol.go
action/protocol/poll/governance_protocol_test.go
action/protocol/rewarding/protocol.go
action/protocol/rewarding/reward.go
action/protocol/vote/blacklist.go
action/protocol/vote/blacklist_test.go
blockchain/genesis/genesis.go
ioctl/cmd/bc/bc.go
ioctl/cmd/node/nodedelegate.go

previous the intensity rate was range from 0 to 1, where the 0 is hard kick out 
from now, the intensity rate is going to be 0 to 100, where the 100 is hard kick out , so the calculation is modified here

reverse the number of intensity rate

---

action/protocol/staking/delegate.go
action/protocol/staking/delegate_map.go
action/protocol/staking/delegate_test.go

and some API to manage Delegate, to unblock Zhefeng's handler work

add delegate map into staking protocol struct

---

ioctl/cmd/account/account_test.go

fix parallel conflict in ioctl unit test

---

blockchain/blockchain.go
blockchain/blockdao/blockdao.go
blockchain/blockdao/blockdao_test.go
blockindex/indexbuilder.go
blockindex/indexbuilder_test.go
blockindex/indexer.go
blockindex/indexer_test.go
chainservice/chainservice.go
test/mock/mock_blockdao/mock_blockdao.go

Move IndexBuilder into blockindex package and delete Commit API

Move index builder to blockindex

---

action/protocol/staking/vote_bucket_test.go
db/db_bolt.go
db/db_test.go
db/kvstore.go
db/kvstore_impl.go
db/kvstorewithbuffer.go
db/mock_kvstore.go
misc/scripts/mockgen.sh

this will be used to quickly scan the stateDB to filter out active delegates upon Start()

add Filter() to KVStore

---

db/batch/kv_cache_test.go
db/kvstore_impl_test.go

resubmit  for https://github.com/iotexproject/iotex-core/pull/1930

kvcache and kvstore UT

---

action/protocol/staking/candidate_center.go
action/protocol/staking/candidate_test.go

1. also add self staking bucket index
2. remove serialize() per earlier comment

use string as key for candidate map

---

action/protocol/context.go
action/protocol/context_test.go

delete history from bc context

---

state/factory/factory.go

when restart, fix initialize bug

fix a factory initialize bug 

---

action/protocol/managers.go
action/protocol/mock_protocol_test.go
misc/scripts/mockgen.sh
state/factory/factory.go
state/factory/statedb.go
state/factory/workingset.go
state/iterator.go
test/mock/mock_chainmanager/mock_chainmanager.go
test/mock/mock_factory/mock_factory.go

Introduce state.Iterator and a dummy implement state.iterator
Add a new api "States" to protocol.StateReader
Implement the "States" api in state.factory.factory and state.factory.statedb

add states api to state reader

---

action/protocol/staking/bucket_index.go
action/protocol/staking/bucket_index_test.go
action/protocol/staking/candidate.go
action/protocol/staking/candidate_center.go
action/protocol/staking/candidate_test.go
action/protocol/staking/handlers.go
action/protocol/staking/protocol_test.go

1. add the API
2. implementation in next PR

add get/put/delCandidateIndex

---

action/candidate_register.go
action/candidateregister_test.go
action/protocol/staking/validations_test.go
action/stake_adddeposit.go
action/stake_create.go
action/stakeadddeposit_test.go
action/stakecreate_test.go
action/stakereclaim_test.go

sanity check amount in stake/register message 1993

---

action/protocol/staking/protocol.go
action/protocol/staking/protocol_test.go

https://golang.org/ref/spec#Iota

fix const using iota

---

action/protocol/staking/candidate_center.go
action/protocol/staking/validations.go
action/protocol/staking/validations_test.go

add test for staking/register message validators 2006

---

action/protocol/staking/candidate.go
action/protocol/staking/handlers.go
action/protocol/staking/handlers_test.go
action/protocol/staking/protocol.go
action/protocol/staking/protocol_test.go
action/protocol/staking/validations.go
action/protocol/staking/validations_test.go
blockchain/genesis/genesis.go
chainservice/chainservice.go
config/config.go
e2etest/native_staking_test.go
e2etest/staking_test.go

use rau string as token unit and format in config to be consistent with others

use rau string as token unit and format in config

---

action/protocol/poll/protocol.go
action/protocol/poll/protocol_test.go
action/protocol/poll/staking_command.go
action/protocol/poll/staking_committee.go
action/protocol/poll/staking_committee_test.go
action/protocol/rewarding/reward.go
chainservice/chainservice.go

pls focus on 2nd commit
1st commit is just to revert earlier changes

add staking_command to integrate staking_committee and V2

---

Makefile
action/protocol/rewarding/reward.go
chainservice/chainservice.go
config/config.go

1. merge gateway with candidateGateway 
2. add EnableSystemLogIndexer (default: false)

merge gateway and add EnableSystemLogIndexer flag

---

action/protocol/rewarding/reward.go
blockchain/genesis/genesis.go
config/heightupgrade_test.go

set up Easter Height (04/06/2020, tentative) and change default kickout period and intensity rate to the decided one.

set up Easter variable

---

blockchain/blockdao/blockdao.go

start from tip+1, end with blockdao.tipHeight

fix a bug when restarting with indexer

---

state/candidate.go
state/iterator_test.go

Unit test for state.Iterator
https://github.com/iotexproject/iotex-core/issues/1979
@CoderZhi

Add state iterator unit test case

---

action/protocol/execution/evm/evm.go
state/factory/factory.go
state/factory/factory_test.go
state/factory/statedb.go
state/factory/util.go
state/factory/workingset.go

These util functions are part of the working set implementation. Put them back to the right place.

move util function to workingSet

---

tools/minicluster/minicluster.go

work on #2069
I have tested "make minicluster" with win10 and ubuntu,#2069's error cannot reproduce
This pr fix "rm file error" with win10.

make minicluster height and balance mismatch

---

action/protocol/poll/governance_protocol.go
action/protocol/vote/blacklist.go
go.mod
go.sum
ioctl/cmd/bc/bc.go
ioctl/cmd/node/nodedelegate.go
ioctl/newcmd/bc/bc.go
ioctl/newcmd/node/nodedelegate.go

Update proto to rename to probation and change readState API method name

Update proto to rename to probation 

---

action/protocol/registry.go
state/factory/factory.go
state/factory/statedb.go

Three bugs:
1. Lock on factory/statedb Start will trigger a dead lock as some protocol will read factory state
2. Add protocol start into statedb.go
3. Put current height before create genesis states in statedb
Test:
1. Successfully start archive mode from 0 and sync with mainnet
2. Successfully start trieless mode from 0 and sync with mainnet

fix factory bugs

---

action/protocol/execution/protocol_test.go
action/protocol/generic_validator.go
actpool/actpool.go
actpool/actpool_test.go
api/api.go
api/api_test.go
blockchain/blockchain.go
blockchain/blockchain_test.go
blocksync/blocksync_test.go
blocksync/buffer_test.go
chainservice/chainservice.go
consensus/scheme/rolldpos/rolldpos_test.go
consensus/scheme/rolldpos/roundcalculator_test.go
e2etest/bigint_test.go
e2etest/local_test.go
e2etest/local_transfer_test.go
gasstation/gasstattion_test.go
state/factory/factory.go
state/factory/factory_test.go
state/factory/statedb.go
state/factory/workingset.go
test/mock/mock_factory/mock_factory.go

1. Move registry from blockchain to factory.
2. Correspondingly, move protocol.Validate into state factory mint/validate function
3. TODO: move some basic protocol validation code into action struct, will be in next PR

move registry into factory

---

Makefile

fix xctl build directory

---

action/protocol/poll/governance_protocol_test.go
action/protocol/poll/nativestaking.go
action/protocol/poll/staking_committee_test.go
action/protocol/poll/util.go
e2etest/staking_test.go

1. fix createPosySystemActions bug
2. fix shifting logic to delete nextkey data

fix createPosySystemActions bug for Easter release 

---

action/actctx.go
action/action.go
action/candidate_register.go
action/claimreward.go
action/depositreward.go
action/execution.go
action/protocol/account/transfer.go
action/protocol/account/transfer_test.go
action/protocol/execution/protocol.go
action/protocol/execution/protocol_test.go
action/protocol/generic_validator.go
action/protocol/generic_validator_test.go
action/protocol/staking/validations.go
action/stake_adddeposit.go
action/stake_create.go
action/transfer.go
actpool/actpool.go
e2etest/local_transfer_test.go

1. Add SelfCheck API to Action
2. Call SelfCheck in actpool.go

split protocol validation

---

action/protocol/poll/governance_protocol_test.go
action/protocol/poll/protocol.go
action/protocol/poll/protocol_test.go
action/protocol/poll/slasher.go
action/protocol/poll/staking_committee_test.go
action/protocol/poll/util.go
action/protocol/rewarding/reward_test.go
action/protocol/vote/candidatesutil/candidatesutil.go
api/api_test.go
blockchain/blockchain_test.go
chainservice/chainservice.go
state/factory/factory_test.go

combine CandidatesFromDB and CandidatesByHeight func and use it to fix putpollresult bug properly

combine candidatesFromDB function and fix putpollresult bug by using it 

---

action/protocol/managers.go
action/protocol/mock_protocol_test.go
action/protocol/poll/consortium.go
action/protocol/poll/nativestakingV2.go
action/protocol/poll/staking_command.go
action/protocol/poll/staking_committee.go
action/protocol/protocol.go
action/protocol/registry.go
action/protocol/staking/candidate_center.go
action/protocol/staking/candidate_center_test.go
action/protocol/staking/candidate_statemanager.go
action/protocol/staking/handlers_test.go
action/protocol/staking/protocol.go
action/protocol/staking/protocol_test.go
action/protocol/staking/vote_bucket_test.go
state/factory/factory.go
state/factory/historyfactory.go
state/factory/statedb.go
state/factory/util.go
state/factory/workingset.go
test/mock/mock_chainmanager/mock_chainmanager.go
test/mock/mock_factory/mock_factory.go

1. read cand center from state factory/SR, and write the updated value upon commit
2. delete LRU cache
3. staking protocol code is now also same as before, only used 2 more funcs: NewCandidateStateManager(), and getOrCreateCandCenter()

store protocol's view in factory

---

action/protocol/poll/governance_protocol.go
action/protocol/poll/nativestakingV2.go
action/protocol/poll/slasher.go

fix a nsv2 bug to use slasher CreateGenesisStates to handle corner case

fix a nsv2 bug to use slasher CreateGenesisStates

---

api/api.go
api/api_test.go
systemlog/systemlog.go
systemlog/systemlog_test.go

Giving more detail status of error for evm transfer APIs.

update systemlog indexer and evm transfer api

---

blockchain/genesis/genesis.go
config/heightupgrade_test.go

04/22/2020 4pm PDT 
epoch 8744 / height 4478761

update easter height

---

ioctl/cmd/action/stake2.go
ioctl/cmd/action/stake2change.go

add ioctl stake2 change cmd

---

ioctl/cmd/action/stake2.go
ioctl/cmd/action/stake2register.go

add ioctl stake2 register cmd

---

ioctl/cmd/action/stake2.go
ioctl/cmd/action/stake2release.go

add ioctl stake2 release cmd

---

ioctl/cmd/action/stake2.go
ioctl/cmd/action/stake2Transfer.go

add ioctl stake2 tranfer cmd

---

ioctl/cmd/action/stake2.go
ioctl/cmd/action/stake2add.go

add ioctl stake2 add cmd

---

ioctl/cmd/action/stake2.go
ioctl/cmd/action/stake2update.go

add ioctl stake2 update cmd

---

ioctl/cmd/action/stake2.go
ioctl/cmd/action/stake2Withdraw.go

add ioctl stake2 withdraw cmd

---

ioctl/cmd/action/stake2.go
ioctl/cmd/action/stake2create.go
ioctl/cmd/action/stake2renew.go

add ioctl stake2 renew cmd

---

action/protocol/staking/handlers.go
action/protocol/staking/handlers_test.go

early-resolve certain staking error 2092

---

ioctl/cmd/node/nodereward.go

node reward wrong sub command returns error

---

consensus/scheme/rolldpos/roundcalculator.go

to stop the flooding of error messages caused by the same problem.

fix flooding of error messages

---

action/protocol/staking/candidate.go

consensus need operator address not owner address

[staking] fix bug that put owner address to consensus

---

action/protocol/account/protocol.go
action/protocol/account/transfer.go
action/protocol/account/transfer_test.go
action/protocol/execution/protocol.go
action/protocol/execution/protocol_test.go
action/protocol/mock_protocol_test.go
action/protocol/poll/consortium.go
action/protocol/poll/governance_protocol.go
action/protocol/poll/governance_protocol_test.go
action/protocol/poll/lifelong_protocol.go
action/protocol/poll/nativestakingV2.go
action/protocol/poll/protocol.go
action/protocol/poll/staking_command.go
action/protocol/poll/staking_committee.go
action/protocol/poll/staking_committee_test.go
action/protocol/protocol.go
action/protocol/staking/handlers.go
action/protocol/staking/handlers_test.go
action/protocol/staking/protocol.go
go.mod
state/factory/factory_test.go
state/factory/workingset.go
test/mock/mock_poll/mock_poll.go

1. Add back action validator interface
2. Move intrinsic gas check into working set (except EVM, which is too complicated to this PR)

add back validator interface

---

state/factory/workingset.go

The error will be further thrown that in function 'Validate'.
Test plan: make test && make minicluster

return error on processing error

---

ioctl/cmd/node/nodedelegate.go
ioctl/config/config.go

work on #2169
ioctl node delegate output after fairbank:
```
Epoch: 4808,  Start block height: 3360961,Total blocks produced in epoch: 275
Address                                     Name           Rank   Alias   Status   Blocks   ProbatedStatus    Votes
io14jp9s6mp85g2x00spq66cmdds4qe2ge5r0p72d   robotbp00021      1           active   12                       13752651.268634533599636965
io1s3z2pr47u47p69zn7phshgenckw6tr70tex80k   robotbp00018      2           active   11                       2289700.876322665986934979
io1eckfc699y4shqkc9ms8ts9sa254e5vtqyazkar   robotbp00020      3           active   11                       2289609.296529794438734839
io1dh8uwmva79vhk8mec998f7qgfud7jyz9v8lede   robotbp00013      4           active   11                       2289495.966536115897837167 …
```

add delegate's Name in 'ioctl node delegate' output 2169

---

action/protocol/staking/protocol.go
action/protocol/staking/read_state.go
go.mod
go.sum
ioctl/cmd/bc/bc.go
ioctl/cmd/bc/bcblock.go
ioctl/cmd/bc/bcbucketlist.go
ioctl/cmd/bc/bucket.go

add getBucketsByIndexes API and ioctl commands to get vote bucket data

---

ioctl/cmd/node/nodedelegate.go
ioctl/config/config.go
ioctl/config/configsetget.go

work on #2177
add command：
```
ioctl config set nsv2height 3123456
ioctl config get nsv2height
```

config set nsv2height 2177

---

ioctl/cmd/action/stake2.go
ioctl/cmd/action/stake2create.go
ioctl/cmd/action/stake2register.go
ioctl/cmd/action/stake2renew.go
ioctl/cmd/node/nodedelegate.go

1. change name auto-restake -> auto-stake
2. delete next flag in ```node delegate```
3. fix typo 
4. delete action deploy/invoke commands

Update stale ioctl

---

ioctl/cmd/bc/bcbucketlist.go

handle empty bucketlist in ioctl

---

action/protocol/account/protocol_test.go

add some test case for action/protocol/account/protocol.go to improve test coverage

Add some test case for action/protocol/account/protocol.go

---

ioctl/cmd/action/actiondeploy.go
ioctl/cmd/action/actioninvoke.go

Delete duplicate ioctl commands related to contract

---

action/protocol/execution/evm/contract.go
db/trie/mptrie/branchnode.go
db/trie/mptrie/cachenode.go
db/trie/mptrie/extensionnode.go
db/trie/mptrie/hashnode.go
db/trie/mptrie/leafnode.go
db/trie/mptrie/merklepatriciatrie.go
db/trie/mptrie/merklepatriciatrie_test.go
db/trie/mptrie/node.go
db/trie/mptrie/twolayertrie.go
db/trie/mptrie/twolayertrie_test.go
db/trie/trie.go
state/factory/factory.go

split PR #2107 
introduce async option in trie to flush data once(when get root hash or stop) for reducing DB writes.

introduce async option in trie to reduce DB writes 

---

ioctl/cmd/action/action.go
ioctl/cmd/did/did.go
ioctl/cmd/did/didderegister.go
ioctl/cmd/did/didgenerate.go
ioctl/cmd/did/didgethash.go
ioctl/cmd/did/didgeturi.go
ioctl/cmd/did/didregister.go
ioctl/cmd/did/didupdate.go

Add the following command:
1. 
`ioctl did register io1m3wjevwhz2s58sasq0wj4luxrnqt047s687zw8 033f8dc3224ed5d2212e0b89093044294c55a286a29417e20393a82a682517d6 https://ipfs.io/ipfs/QmayYwTNcSFQGXdfehs2tt2M9KMzQMe9J1VmrGyk8MSien -s aaa`
2. 
`ioctl did update io1m3wjevwhz2s58sasq0wj4luxrnqt047s687zw8 2f14ebc83172fbde3d8e16145a43b995fb6eb871a55d94058a1ded5575670fa8 https://ipfs.io/ipfs/QmayYwTNcSFQGXdfehs2tt2M9KMzQMe9J1VmrGyk8MSien -s aaa`
3.
`ioctl did deregister io1m3wjevwhz2s58sasq0wj4luxrnqt047s687zw8 -s aaa`
4. 
`ioctl did gethash io1m3wjevwhz2s58sasq0wj4luxrnqt047s687zw8 did:io:0x6356908ACe09268130DEE2b7de643314BBeb3683`
5. 
`ioctl did geturi io1m3wjevwhz2s58sasq0wj4luxrnqt047s687zw8 did:io:0x6356908ACe09268130DEE2b7de643314BBeb3683`

add did command

---

action/protocol/rolldpos/epoch_test.go

feat: Add unit test for rolldpos protocol

---

action/protocol/execution/evm/contract.go
action/protocol/execution/evm/contract_test.go
action/protocol/execution/evm/evm.go
action/protocol/execution/evm/evm_test.go
action/protocol/execution/evm/evmstatedbadapter.go
action/protocol/execution/evm/evmstatedbadapter_test.go

Apply new trie change(cache/hash node + async option) to contract trie  
@yutongp if the Greenland hard fork is too tight, I will make another height for this change.

Apply new trie improvement to contract trie  

---

api/api.go
go.mod
go.sum
tools/actioninjector.v2/internal/client/client_test.go

work on #2251
Request:
```grpcurl -v -plaintext -d '{"address": "io1mflp9m6hcgm2qcghchsdqj3z3eccrnekx9p0ms"}' 127.0.0.1:14014 iotexapi.APIService.GetAccount```
Response contents:
```
{
"accountMeta": {
"address": "io1mflp9m6hcgm2qcghchsdqj3z3eccrnekx9p0ms",
"balance": "0",
"pendingNonce": 1
},
"blockIdentifier": {
"hash": "6ba52c53ed61a04148147efe3b4a1270867342e160710fed7eedebcf3438e19d",
"height": 3
}
}
```

get account return block information 2251

---

go.mod
ioctl/cmd/bc/bcblock.go

`ioctl bc block` returns all actions with `--verbose` flag

---

action/protocol/account/protocol.go
action/protocol/execution/protocol.go
action/protocol/mock_protocol_test.go
action/protocol/poll/consortium.go
action/protocol/poll/governance_protocol.go
action/protocol/poll/lifelong_protocol.go
action/protocol/poll/nativestakingV2.go
action/protocol/poll/slasher.go
action/protocol/poll/staking_command.go
action/protocol/poll/staking_committee.go
action/protocol/protocol.go
action/protocol/rewarding/admin.go
action/protocol/rewarding/fund.go
action/protocol/rewarding/fund_test.go
action/protocol/rewarding/protocol.go
action/protocol/rewarding/protocol_test.go
action/protocol/rewarding/reward.go
action/protocol/rewarding/reward_test.go
action/protocol/rolldpos/epoch.go
action/protocol/rolldpos/epoch_test.go
action/protocol/staking/protocol.go
api/api.go
e2etest/rewarding_test.go
go.mod
go.sum
test/mock/mock_poll/mock_poll.go

Add height for Readstate api response 

---

action/protocol/rewarding/admin.go
action/protocol/rewarding/fund.go
action/protocol/rewarding/protocol.go
action/protocol/rewarding/protocol_test.go
action/protocol/rewarding/reward.go
action/protocol/rewarding/reward_test.go
action/protocol/staking/bucket_index_test.go
action/protocol/staking/bucket_pool_test.go
action/protocol/staking/candidate_test.go
action/protocol/staking/handlers_test.go
action/protocol/staking/protocol_test.go
action/protocol/staking/vote_bucket_test.go
e2etest/rewarding_test.go
testutil/testdb/db.go

migrate rewarding data on greenland height

---

api/api.go

fix nil filter input in GetLogs and StreamLogs

---

action/protocol/staking/bucket_pool.go
action/protocol/staking/bucket_pool_test.go
action/protocol/staking/candidate_statemanager.go
action/protocol/staking/candidate_statereader.go
action/protocol/staking/handlers.go
action/protocol/staking/handlers_test.go
action/protocol/staking/protocol.go
action/protocol/staking/protocol_test.go

Some part is still not clear, e.g., use sm.Height or blkCtx.BlockHeight. But this PR clear up the logic to make it clear. Again, we shouldn't pay so many attention to "efficiency" but "easy to understand".

unify exist and create to simplify the logic of bucket pool

---

action/protocol/staking/bucket_pool.go
action/protocol/staking/bucket_pool_test.go
action/protocol/staking/protocol.go
action/protocol/staking/protocol_test.go

After greenland, there will alway be a state of bucket stats

create bucket stats state in prestates of greenland

---

server/itx/server.go

Reverts iotexproject/iotex-core#2334

Revert "start blockchain before p2p network (#2330)"

---

ioctl/cmd/account/accountbalance.go

support ioctl account balance command for staking and reward pool addr

---

action/protocol/account/protocol.go
action/protocol/account/transfer.go
action/protocol/account/transfer_test.go
action/protocol/execution/evm/evm.go
action/protocol/execution/evm/evm_test.go
action/protocol/execution/evm/evmstatedbadapter.go
action/protocol/poll/consortium.go
action/protocol/poll/staking_committee.go
action/protocol/rewarding/fund.go
action/protocol/rewarding/fund_test.go
action/protocol/rewarding/protocol.go
action/protocol/rewarding/reward_test.go
action/protocol/staking/handlers.go
action/protocol/staking/handlers_test.go
action/protocol/staking/protocol.go

add log to gas deposit

---

action/protocol/staking/bucket_pool.go
action/protocol/staking/candidate_center.go
action/protocol/staking/candidate_center_test.go
action/protocol/staking/candidate_statemanager.go
action/protocol/staking/candidate_statereader.go
action/protocol/staking/handlers_test.go

[staking] remove CandidateCenter interface

---

action/protocol/staking/candidate_buckets_indexer.go
action/protocol/staking/protocol.go

return right data and height when user query with latest height

make staking indexer return latest data with right height

---

action/protocol/account/transfer_test.go
action/protocol/execution/evm/evm.go
api/api.go
api/api_test.go
blockchain/block/block.go
blockchain/block/systemlog.go
blockchain/block/systemlog_test.go
blockchain/blockdao/blockdao.go
go.mod
go.sum
test/mock/mock_blockdao/mock_blockdao.go

commit 1: update iotex-proto
commit 2: fix the ErrCodeStoreOutOfGas issue

Code store out of gas

---

state/factory/factory.go
state/factory/statedb.go
state/factory/workingset.go

cache receipts in workingset

---

ioctl/cmd/bc/bcblock.go

fix ioctl bc block cmd bug

---

tools/minicluster/minicluster.go
tools/util/injectorutil.go

1. decrease fees in execution
2. no test staking in minicluster
3. fatal if balances mismatch

fixed: minicluster balances mismatch

---

blockchain/blockchain.go
state/factory/workingset.go

Add back this metric which was deleted.

add number of block actions

---

Makefile
config/standalone-genesis.yaml

for https://github.com/iotexproject/iotex-core/issues/2380

add test account with initial balance in standalone mode

---

ioctl/config/configsetget.go

language config fix for ioctl

---

ioctl/cmd/contract/contractinvoke.go
ioctl/cmd/contract/contractinvokefunction.go
ioctl/cmd/contract/contracttestbytecode.go
ioctl/cmd/contract/contracttestfunction.go

fix spelling mistakes in ioctl contract package

fix spelling mistakes in ioctl contract package

---

ioctl/cmd/bc/bcblock.go

1. hex block output
2. fixed print same action hash in all actions

hex ioctl block output

---

ioctl/cmd/bc/bcblock.go

[ioctl] log.Data hex output

---

blockchain/blockchain.go
blockchain/blockdao/blockdao.go
blockchain/blockdao/blockdao_test.go
blockchain/filedao/filedao.go
blockchain/filedao/filedao_header.go
blockchain/filedao/filedao_header_test.go
blockchain/filedao/filedao_legacy.go
blockchain/filedao/filedao_test.go
blockchain/filedao/filedao_util.go
blockchain/filedao/filedao_v2.go
blockchain/filedao/filedao_v2_manager.go
blockchain/filedao/filedao_v2_test.go
blockchain/filedao/filedao_v2_util.go
blockchain/filedao/staging_buffer.go
blockchain/integrity/integrity_test.go
blockindex/indexbuilder_test.go
chainservice/chainservice.go
config/config.go
consensus/scheme/rolldpos/roundcalculator_test.go
db/db_bolt.go
db/db_bolt_test.go
db/db_test.go
e2etest/local_test.go
server/itx/heartbeat_test.go
tools/iomigrater/cmds/check-height.go
tools/iomigrater/cmds/migrate-db.go

update regarding discussion with Zhi
1. the migration tool is the 2nd commit "code for migration"
2. storage improvement is 30%, using a snapshot of 10G, after migration it reduce to 7G

[filedao] check legacy and V2 files in cfg.DbPath

---

ioctl/cmd/action/action.go

Fix the extra space before "answer yes..."

Remove an extra space before "answer yes..."

---

config/config.go

feature need more verification in cluster

set state cache default to false.

---

go.mod
ioctl/cmd/action/xrc20.go

fix xrc20 amount parsing

---

blockchain/filedao/filedao_legacy_test.go

add fileDAOLegacy.PutBlock fileDAOLegacy.DeleteTipBlock fileDAOLegacy.getBlockValue testing
#2477 @yutongp

[filedao] add blockchain/filedao/filedao_legacy.go testing

---

api/api.go
api/api_test.go
api/apitestclient.go
go.mod
go.sum
test/mock/mock_apiserviceclient/mock_apiserviceclient.go

implement GetActPoolActions

---

ioctl/cmd/action/action.go

set default gasLimit

---

tools/devenv/control.sh

renamed:    control -> control.sh

typo error	

---

install-cli.sh

fix bug ioctl unstable update

---

api/api_test.go

more tests for api/api.go #2476

---

action/protocol/staking/candidate_statereader_test.go
action/protocol/staking/protocol_test.go

More unit tests for staking protocol #2385

---

blockchain/genesis/genesis.go
config/heightupgrade.go
config/heightupgrade_test.go

need this for the GetBlockHash fix, and also export require error msg outside of EVM

[config] add Hawaii height

---

blockchain/integrity/integrity_test.go

test for getBlockHash #2534

---

ioctl/cmd/action/action.go

fix Wrong tx url in ioctl actions output when sent to testnet #2537

---

action/protocol/execution/evm/evm.go
action/protocol/execution/evm/evmstatedbadapter.go
action/protocol/execution/protocol_test.go
action/protocol/execution/testdata/multisend.json
action/receipt.go
action/receipt_test.go
go.mod
go.sum
ioctl/cmd/action/actionhash.go

Add execution revert message in receipt 

---

api/api.go
go.sum
tools/bot/pkg/util/grpcutil/grpc.go

After Hawaii height, EstimateActionGasConsumption API will return execution revert msg as well even before sending tx.

modify EstimateActionGasConsumption api to return execution revert error

---

ioctl/cmd/action/action.go

`ctrl/cmd`+`click`on a URL and it will open in the default browser, or right click on a URL.

Make iotexscan url clickable #2560

---

blockindex/bloomfilterindexer.go

reduce bloomfilter db size by setting bucket fillpercent = 1.0

---

tools/ioctl/buildcli.sh

fix cgo network problem

---

Makefile

fix bug for execute make run

---

blockchain/blockchain.go
blockchain/blockdao/blockdao.go
blockchain/filedao/filedao.go
blockchain/filedao/filedao_util.go
chainservice/chainservice.go

fix crash when the db file cant be access

check db file permission

---

action/protocol/execution/evm/evm.go
action/protocol/execution/evm/evmstatedbadapter.go
db/trie/mptrie/twolayertrie.go

1. sort cached contracts in state db adapter
2. sort layer two keys in two layer trie

sort map keys

---

action/protocol/execution/evm/evm_test.go
api/api.go
api/api_test.go

Related to 
https://github.com/iotexproject/iotex-core/pull/1628
https://github.com/iotexproject/iotex-core/issues/1609

[api] fix excessively large gas estimate

---

e2etest/local_transfer_test.go

fix TestLocalTransfer failed #2589

---

action/action.go
action/builder.go
action/envelope.go
action/envelope_test.go
action/execution_test.go
action/sealedenvelope.go
action/transfer_test.go

1. pls focus on 2nd commit, the 1st commit is mostly a clean-up
2. WIP to adjust/fix tests

[action] make Envelope an interface

---

api/api.go
api/api_test.go
ioctl/cmd/bc/bcblock.go

also added tx dump, in case the failed tx happen again, the protobuf bytes are dumped so we can know the root-cause

 [ioctl] allow get block number 0 (genesis block)

---

action/protocol/execution/evm/evm.go
action/protocol/execution/evm/evm_test.go

chainID implementation:
https://github.com/ethereum/go-ethereum/blob/d8ff53dfb8a516f47db37dbc7fd7ad18a1e8a125/core/vm/eips.go#L85-L102

[evm] support chainID starting Hawaii height

---

action/protocol/execution/evm/evm.go
action/protocol/execution/evm/evm_test.go

This reverts commit 398ff6ace915783614617eb4a3625ef6d69b3cd4.

Revert "[evm] support chainID starting Hawaii height (#2613)"

---

blocksync/blocksync.go
blocksync/blocksync_test.go
blocksync/buffer.go
blocksync/buffer_test.go
blocksync/worker.go
chainservice/chainservice.go
consensus/consensusfsm/mock_context_test.go
dispatcher/dispatcher.go
dispatcher/dispatcher_test.go
p2p/agent.go
server/itx/heartbeat.go
test/mock/mock_blocksync/mock_blocksync.go
test/mock/mock_dispatcher/mock_dispatcher.go

refine the block sync related code

Refine dispatcher and block sync

---

server/main.go

fix: remove masterKey from logging issue#2633

---

actpool/actqueue.go
actpool/actqueue_test.go
blockchain/blockchain.go
consensus/consensus.go
consensus/consensusfsm/fsm.go
consensus/consensusfsm/fsm_test.go
consensus/scheme/rolldpos/rolldpos.go
consensus/scheme/rolldpos/rolldpos_test.go
consensus/scheme/rolldpos/rolldposctx.go
consensus/scheme/rolldpos/rolldposctx_test.go
go.mod
go.sum
pkg/prometheustimer/timer.go
pkg/routine/delaytask.go
pkg/routine/delaytask_test.go
pkg/routine/options.go
pkg/routine/recurringtask.go
pkg/routine/recurringtask_test.go
testutil/timestamp.go

Reverts iotexproject/iotex-core#2557

Revert "remove github.com/facebookgo/clock dependency #2556"

---

p2p/agent.go

This reverts commit 80e1bd4580634b81a862582ca9a847fef6f1d384.

Revert "[p2p] re-connect in case of network disconnect (#2570)"

---

action/protocol/execution/evm/evm.go
action/protocol/execution/evm/evmstatedbadapter.go
action/protocol/execution/testdata/factory.json
action/protocol/execution/testdata/reentry-attack.json
go.mod
go.sum

1. Add func "InitNonce" in StateDB
2. If usePendingNonce is enabled:
InitNonce will be 1
GetNonce return pending nonce
SetNonce will receive next pending nonce

get and set nonce in state db adapter

---

blocksync/blocksync.go
blocksync/blocksync_test.go
blocksync/buffer.go
blocksync/buffer_test.go
blocksync/uniqueue.go
chainservice/chainservice.go
config/config.go
dispatcher/dispatcher.go
dispatcher/dispatcher_test.go
e2etest/local_actpool_test.go
e2etest/local_test.go
p2p/agent.go
p2p/agent_test.go

1. add blocklist in blocksync
2. add limit rate in dispatcher

better block sync strategy 2

---

config/config.go
e2etest/local_actpool_test.go
e2etest/local_test.go
p2p/agent.go
p2p/agent_test.go
server/itx/heartbeat.go
server/itx/server.go

as part of https://github.com/iotexproject/iotex-core/issues/2694

move network config into p2p

---

blocksync/blocksync.go
blocksync/blocksync_test.go
blocksync/buffer.go

flush blocks right after receiving a block

flush right after receiving block

---

gasstation/gasstattion_test.go

fix issue#2700

---

ioctl/newcmd/account/accountdelete_test.go

fix issue #2730

---

action/protocol/staking/protocol.go

the log level was not appropriate.

change info to debug in staking protocol

---

blocksync/blocksync.go

change commit block failure log level to error

---

blocksync/blocksync.go
blocksync/buffer.go

target height was not set if the block height is larger than tip height + buffer size.
This PR set target height to tip height + buffer size, if blockchain is far behind.

set target height if block height is out of buffer size

---

.codecov.yml
blockchain/blockdao/blockdao.go

fix typo, and add the whole directory "tools"

Fix codecov

---

.codecov.yml

bump coverage target

---

action/action_test.go
action/execution_test.go
action/protocol/generic_validator_test.go
action/protocol/poll/governance_protocol_test.go
action/protocol/poll/staking_committee_test.go
action/transfer_test.go
actpool/actpool_test.go
blockchain/block/validator_test.go

Resolves #2881
replaced <code>require.True(strings.Contains(a, b))</code> pattern with <code>require.Contains(a, b)</code>

[test] simplified tests

---

README.md

[readme] update go version in readme

---

action/action.go
action/const.go
action/protocol/execution/evm/evm.go
actpool/actpool.go

some small issues when I pick the PR to r1.6 branch

remove duplicate value in case clause

---

api/coreservice.go
api/grpcserver.go
api/serverV2.go
api/web3server.go
go.mod
go.sum

restore api tracing and prometheus on grpc server

[api] add tracer and metrics

---

api/api.go
api/coreservice.go
api/grpcserver.go
api/grpcserver_test.go

issue found during rosetta testing

[api] fix null BlockIdentifier for rewarding pool address query

---

api/web3server.go
api/web3server_utils.go

similar with fix #2927
the array in response should be [] instead of null. The null value is due to the unallocated memory of the array

[api] fix unallocated memory of array 

---

api/web3server.go
api/web3server_test.go
api/web3server_utils.go

This is my first time working in go and in iotex-core so i'd love some feedback. Thanks!
1. How would I test these changes? I ran make and make test to completion. 
2. I named an import ioctl (due to two imports named util) - is this good or is there a better name?
3. Is there anything I can do better (ex Formatting the PR, Consolidating commits, test plan, code style, etc.)

Replace removeHexPrefix() with util.Remove0xPrefix

---

state/factory/statedb.go

currentChainHeight is only written in `ws.Commit(ctx)`, which is protected by a write lock: https://github.com/iotexproject/iotex-core/blob/master/state/factory/statedb.go#L424-L440 
for all other places, read lock should suffice
test coverage:
1. make test
2. verified on full-node it can successfully commit/sync blocks

[statedb] use read lock to access currentChainHeight in reader funcs

---

api/coreservice.go
api/grpcserver.go
api/web3server.go
api/web3server_utils.go

[api] refactor gas estimation code out of core service 

---

api/coreservice.go
api/grpcserver_test.go

[api] del  ActionByActionHash   for #2869

[api] integrate GetActionByActionHash

---

api/web3server_utils.go
ioctl/cmd/account/accountethaddr.go
ioctl/cmd/alias/alias.go
ioctl/cmd/contract/parse.go
ioctl/cmd/did/didgenerate.go
ioctl/newcmd/alias/alias.go
ioctl/util/util.go
pkg/util/addrutil/addrutil.go
tools/multisend/multisend.go

[ioctl] move IoAddrToEvmAddr to pkg/util/addrutil/addrutil.go

---

ioctl/newcmd/account/account.go
ioctl/newcmd/account/accountnonce.go
ioctl/newcmd/account/accountnonce_test.go

[ioctl] add account nonce  #2938

[ioctl] add account nonce

---

ioctl/cmd/account/accountdelete.go

add break if found in accountDelete

[ioctl/cmd] add break if found in accountDelete

---

go.mod
go.sum

The update involved two prs:
https://github.com/iotexproject/go-pkgs/pull/30
https://github.com/iotexproject/go-pkgs/pull/31

[goMod] update go-pkg package

---

ioctl/newcmd/account/account.go
ioctl/newcmd/hdwallet/hdwallet.go
ioctl/newcmd/hdwallet/hdwallet_test.go
ioctl/newcmd/hdwallet/hdwalletderive.go

add function DeriveKey  for new account calling

[ioctl/newcmd] add hdwallet for new account calling

---

ioctl/client.go
ioctl/client_test.go
ioctl/newcmd/account/accountdelete.go
ioctl/newcmd/account/accountdelete_test.go
test/mock/mock_ioctlclient/mock_ioctlclient.go

modify as ioctl/cmd/accountDelete

[ioctl/newcmd]  use AskToConfirm in AccountDelete

---

.codecov.yml
api/serverV2_test.go
api/web3server_test.go

add test for server_V2
ignore api.go for nouse

[test] add test for api

---

ioctl/newcmd/account/account.go
ioctl/newcmd/account/accountlist.go
ioctl/newcmd/account/accountlist_test.go

* Added accountlist to newcmd
* Added unit-test
* fix #2937

[ioctl] feat: Added Accountlist to newcmd

---

blocksync/uniqueue.go

Updated bool to struct in uniqueue.go

---

action/protocol/context.go
action/protocol/execution/evm/evmstatedbadapter_test.go
api/coreservice.go
api/grpcserver_test.go
blockchain/genesis/genesis.go
blockchain/genesis/heightupgrade_test.go
blockchain/integrity/integrity_test.go
config/config.go
config/config_test.go
e2etest/local_test.go
e2etest/local_transfer_test.go
ioctl/newcmd/account/accountlist_test.go

1. allow correct and default ChainID
2. fix GetHashFunc in EVM
3. correct tx/log index for transaction receipt and EVM log
4. revert logs upon tx reversion in EVM

[config] enable 4 features at midway height

---

api/web3server.go
api/web3server_test.go

[api] fix issue#3030

---

ioctl/newcmd/account/account.go
ioctl/newcmd/account/accountupdate.go
ioctl/newcmd/account/accountupdate_test.go

close #3002
build account update command line into new ioctl.

[ioctl/newcmd] build account update command line into new ioctl

---

ioctl/client.go
ioctl/client_test.go
ioctl/newcmd/account/account.go
ioctl/newcmd/account/account_test.go
ioctl/newcmd/account/accountcreate.go
ioctl/newcmd/account/accountcreate_test.go
ioctl/newcmd/account/accountdelete.go
ioctl/newcmd/account/accountdelete_test.go
ioctl/newcmd/account/accountlist.go
ioctl/newcmd/account/accountlist_test.go
ioctl/newcmd/account/accountsign_test.go
test/mock/mock_ioctlclient/mock_ioctlclient.go

delete SetCryptoSm2
modify HasCryptoSm2 to IsCryptoSm2

[ioctl/newcmd] modify HasCryptoSm2 to IsCryptoSm2 

---

server/itx/heartbeat.go

fix #3052 
Performance Benchmark:
```         
BenchmarkMemMetrics-12    	   58128	     22806 ns/op	     122 B/op	       3 allocs/op
```

[log] fix issue 3052

---

ioctl/newcmd/account/account.go
ioctl/newcmd/account/accountupdate.go
ioctl/newcmd/account/accountupdate_test.go

[ioctl/newcmd] use client.IsCryptoSm2 

---

blockchain/integrity/integrity_test.go
e2etest/native_staking_test.go

[test] simplify test code

---

e2etest/native_staking_test.go

fix #3065, #3087 
fix withdraw with correct timestamp

[test] simplify test code following fix

---

ioctl/newcmd/account/account.go
ioctl/newcmd/account/account_test.go
ioctl/newcmd/account/accountdelete_test.go
ioctl/newcmd/account/accountlist.go
ioctl/newcmd/account/accountlist_test.go
ioctl/newcmd/account/accountupdate.go
ioctl/newcmd/account/accountupdate_test.go

replace global var by client member

[ioctl/newcmd] replace config.ReadConfig with client.Config() in account

---

api/web3server.go

https://github.com/iotexproject/iotex-core/blob/2b4488ae6a617c7945dcb8d8f2c3e984d007a145/api/coreservice.go#L1056-L1058

delete duplicate range check

---

api/grpcserver.go
api/web3server.go

the redeclared error was not handled

Fix error handling in get actions

---

ioctl/client.go
ioctl/newcmd/account/accountcreate.go
ioctl/newcmd/account/accountcreate_test.go
ioctl/newcmd/account/accountdelete.go
ioctl/newcmd/account/accountdelete_test.go
test/mock/mock_ioctlclient/mock_ioctlclient.go

useless function. return err and print by cobra output

[ioctl/newcmd] delete PrintError in ioctl.client

---

ioctl/newcmd/account/account.go
ioctl/newcmd/account/account_test.go
ioctl/newcmd/account/accountnonce.go
ioctl/newcmd/account/accountnonce_test.go
ioctl/newcmd/account/accountsign_test.go

1. use client.PrintInfo
2. delete useless argument walletDir

[ioctl/newcmd] add client.PrintInfo in account

---

pkg/util/addrutil/addrutil_test.go

[test] add test for addrutil

---

api/coreservice.go
api/grpcserver.go
api/grpcserver_test.go
api/serverV2_test.go
api/web3server.go
api/web3server_test.go
api/web3server_utils.go
test/mock/mock_apicoreservice/mock_apicoreservice.go

Delete Blockchain, BlockDao, and Indexer

Delete some interface of CoreService

---

api/coreservice.go
api/grpcserver_test.go
api/serverV2.go
api/serverV2_test.go
api/web3server.go
api/web3server_test.go
api/web3server_utils.go
test/mock/mock_apicoreservice/mock_apicoreservice.go

Delete `Registry`, `Config`, and `ActPool`

Clean up core service

---

ioctl/newcmd/account/account.go
ioctl/newcmd/account/accountethaddr.go
ioctl/newcmd/account/accountethaddr_test.go

[ioctl] Dev account ethaddr

---

ioctl/newcmd/account/account.go
ioctl/newcmd/account/accountverify.go
ioctl/newcmd/account/accountverify_test.go

[ioctl] Dev account verify

---

ioctl/newcmd/account/accountcreate.go
ioctl/newcmd/account/accountcreate_test.go
ioctl/newcmd/account/accountdelete.go
ioctl/newcmd/account/accountdelete_test.go
ioctl/newcmd/account/accountnonce_test.go

no need print info in unit test

[ioctl/newcmd] delete print in unit test

---

ioctl/client.go
ioctl/newcmd/account/account.go
ioctl/newcmd/account/account_test.go
ioctl/newcmd/account/accountlist.go
ioctl/newcmd/account/accountlist_test.go
ioctl/newcmd/account/accountsign.go
ioctl/newcmd/account/accountsign_test.go
ioctl/newcmd/account/accountupdate.go
ioctl/newcmd/account/accountupdate_test.go

replace output.NewError with errors.Wrap

[ioctl/newcmd] delete output package

---

ioctl/newcmd/account/accountethaddr.go
ioctl/newcmd/account/accountethaddr_test.go
ioctl/newcmd/account/accountinfo.go
ioctl/newcmd/account/accountinfo_test.go
ioctl/newcmd/account/accountverify.go
ioctl/newcmd/account/accountverify_test.go
pkg/util/addrutil/addrutil_test.go

1. make sure run `make fmt` and `make lint` before submitting PR
2. pls also tell external contributor when they submit PR

fix make fmt

---

.codecov.yml

[codecov] codecov ignore

---

pkg/util/byteutil/byteutil.go
pkg/util/byteutil/byteutil_test.go

[test] add test for byteutil

---

server/itx/server.go
server/itx/server_test.go

[test] add server unit test

---

ioctl/client.go
ioctl/client_test.go

fix https://github.com/iotexproject/iotex-core/issues/3171

[ioctl/newcmd] modify client.SetAlias

---

action/protocol/execution/evm/evmstatedbadapter_test.go
db/batch/batch.go
db/batch/batch_impl.go
db/batch/batch_impl_test.go
db/batch/kv_cache.go
db/kvstorewithbuffer.go
db/kvstorewithbuffer_test.go
state/factory/factory.go
state/factory/factory_test.go
state/factory/statedb.go
state/factory/util.go
state/factory/workingset.go
state/factory/workingset_test.go
state/factory/workingsetstore.go
state/factory/workingsetstore_test.go
test/mock/mock_batch/mock_batch.go

Introduce workingsetstore

---

ioctl/newcmd/account/account.go
ioctl/newcmd/account/accountexport.go
ioctl/newcmd/account/accountexport_test.go

[ioctl] build account export command line into new ioctl

---

action/protocol/poll/blockmeta.go
action/protocol/staking/vote_bucket.go
api/coreservice.go
api/grpcserver_test.go
blockchain/block/block_test.go
blockchain/block/footer.go
blockchain/block/header.go
consensus/scheme/rolldpos/rolldpos_test.go
consensus/scheme/rolldpos/subchain_test.go
endorsement/endorsement.go
ioctl/cmd/action/actionhash.go
ioctl/cmd/bc/bcbucket.go
p2p/agent.go
tools/actioninjector.v2/internal/client/client_test.go

Replace ptypes.TimestampProto with timestamppb.New

---

chainservice/chainservice.go
state/factory/factory.go

Patch for factory

---

blockindex/bloomfilterindexer.go

This works on issue #3122 
delete function is removed and directly used in DeleteTipBlock function

Remove delete function and use directly in DeleteTipBlock function

---

blockchain/blockdao/blockdao.go
blockchain/blockdao/blockindexer.go

Create BlockIndexerChecker to check the block indexer status
- Hardware:
- Toolchain:
- SDK:

create block indexer checker

---

ioctl/newcmd/account/accountbalance.go
ioctl/newcmd/account/accountbalance_test.go

Build account balance command into ioctl/newcmd, since unit test couldn't add for old cmd, so needs for a new one.
Fixes #3166 
- Hardware:
- Toolchain:
- SDK:

dev account balance

---

action/protocol/staking/protocol.go
chainservice/builder.go
chainservice/chainservice.go
db/kvstore_impl.go
server/itx/server.go

1. Add chainservice builder to improve the readability of the related code.
2. Create kv stores in memory for test
3. Add lifecycle.Lifecycle to simplify the Start/Stop logic of chainservice
make test & make minicluster
- Hardware:
- Toolchain:
- SDK:

introduce chainservice builder

---

blockchain/blockdao/blockdao.go
blockchain/blockdao/blockindexer.go
blockindex/bloomfilterindexer.go
blockindex/indexbuilder.go
blockindex/indexbuilder_test.go
blockindex/indexer.go
blockindex/indexer_test.go
state/factory/factory.go
state/factory/statedb.go
test/mock/mock_blockindex/mock_blockindex.go
test/mock/mock_factory/mock_factory.go

[blockindex] add context to BlockIndexer

---

action/consignment_transfer.go
action/consignment_transfer_test.go
action/execution.go
action/execution_test.go
action/protocol/account/transfer.go
action/protocol/account/transfer_test.go
action/protocol/context.go
action/protocol/execution/evm/evm.go
action/protocol/execution/protocol.go
action/protocol/execution/protocol_test.go
action/protocol/staking/handlers.go
action/protocol/staking/protocol_test.go
action/rlp_tx_test.go
action/transfer.go
action/transfer_test.go
blockchain/integrity/integrity_test.go
blockindex/indexbuilder.go
blockindex/indexbuilder_test.go
blockindex/indexer.go
blockindex/indexer_test.go
chainservice/builder.go
config/config.go
e2etest/local_transfer_test.go
go.mod
go.sum
pkg/util/addrutil/addrutil_test.go

[protocol] check address format

---

ioctl/client.go
ioctl/newcmd/account/accountactions.go
ioctl/newcmd/account/accountactions_test.go
test/mock/mock_ioctlclient/mock_ioctlclient.go

Build account actions command into ioctl/newcmd, since unit test couldn't add for old cmd, so needs for a new one.
Fixes #3165 
- Hardware:
- Toolchain:
- SDK:

Dev account actions

---

chainservice/builder.go

1. cand/bucket indexer should be a gateway component
2. make the logic same as before refactor: https://github.com/iotexproject/iotex-core/commit/1065ea8d7a4bc5119e86456fc5742d5372781ac9#diff-6ae88fef41b61972a03af3642ac7d1da3d3eaa753f5a31e080cef9d8376054ebL178-L209

[chainservice] staking cand/bucket indexer should be a gateway component

---

api/coreservice.go
api/coreservice_test.go
blockindex/bloomfilterindexer.go
blockindex/bloomfilterindexer_test.go
test/mock/mock_blockindex/mock_blockindex.go

fix #3124 
- Hardware:
- Toolchain:
- SDK:

[blockindex] Add timeout and pagination to FilterBlocksInRange

---

action/protocol/account/transfer_test.go
action/protocol/context.go
action/protocol/execution/protocol_test.go
api/coreservice.go
blockchain/genesis/genesis.go
blockchain/genesis/heightupgrade_test.go
chainservice/chainservice.go
config/config.go
config/config_test.go
consensus/scheme/rolldpos/rolldpos.go
state/factory/statedb.go

[config] enable 3 features at newfoundland height

---

action/protocol/context.go
action/protocol/rewarding/protocol.go
action/protocol/rewarding/protocol_test.go

- [] Test A
- [] Test B
- Hardware:
- Toolchain:
- SDK:
- …

only producer can grant reward

---

api/coreservice.go
api/coreservice_test.go
api/serverV2.go
api/serverV2_integrity_test.go
api/web3server_integrity_test.go
chainservice/chainservice.go

The `hasActionIndex` config in `WithActionIndex` is redundant, which can replace by `core.indexer!=nil` check.
Fixes #3373 
- Hardware:
- Toolchain:
- SDK:

[api] Remove redudant function WithActionIndex

---

action/protocol/staking/bucket_index.go
action/protocol/staking/bucket_pool.go
action/protocol/staking/bucket_pool_test.go
action/protocol/staking/candidate_statemanager.go
action/protocol/staking/candidate_statereader.go
e2etest/native_staking_test.go

[staking] remove duplicate code

---

blockchain/genesis/genesis.go
blockchain/genesis/heightupgrade_test.go

[genesis] set Newfoundland to activate at 05-30-2022 11pm UTC

---

state/factory/workingset.go
tools/executiontester/blockchain/contract.go

- [] Test A
- [] Test B
- Hardware:
- …

fix err overwriten

---

action/action.go
action/action_test.go
gasstation/gasstattion.go
gasstation/gasstattion_test.go

- [] Test A
- [] Test B
- Hardware:
- …

move IsSystemAction into action package as a static function

---

ioctl/newcmd/account/accountactions_test.go

replace server request with fake request
Fixes https://github.com/iotexproject/iotex-core/issues/3393
- [] Test A
- [] Test B
- Hardware:
- Toolchain:
- SDK:
- [] I have …

[ioctl] remove server request

---

api/coreservice.go
test/mock/mock_apicoreservice/mock_apicoreservice.go

remove unused func
Fixes #3415 
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have performed a self-review of my …

clean-up coreservice API 

---

api/http.go
api/websocket.go

fix #3391 
- [] Test A
- [] Test B
- Hardware:
- Toolchain:
- SDK: …

fix issue #3391

---

action/action.go
action/action_test.go
blockchain/integrity/integrity_test.go
blockindex/indexbuilder_test.go
blockindex/indexer_test.go

move ClassifyActions() to test
Fixes #3069 
- [] make test
- Hardware:
- Toolchain:
- SDK:
- [] New and existing unit tests pass locally with my …

[test] move ClassifyActions() to test

---

api/grpcserver.go

Fixes #(issue)
- [] make test
- [] fullsync …

[api] Fix todo in GetLogs

---

api/grpcserver.go
api/grpcserver_test.go
go.sum

need to call `SetEvmNetworkID()` when converting protobuf to action
Fixes #(issue)
- [] fullsync

[api] update chain metrics

---

Makefile
go.mod
go.sum

as title
- [] fullsync
- [] Any dependent changes have been merged and published in downstream modules

[makefile] add go mod tidy

---

api/http.go

Fixes #3538 
- [] make test
- [] fullsync
- …

[api] Add ReadHeaderTimeout

---

action/consignment_transfer.go
action/protocol/staking/handlers_test.go

fix code  scanning#11 https://github.com/iotexproject/iotex-core/security/code-scanning/11
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] My code follows the …

[action] fix Incorrect conversion between integer types

---

consensus/consensus.go
consensus/scheme/rolldpos/rolldposctx.go

Fixes #(issue)
- [] make test
- [] fullsync …

[consensus] Add log in rolldposctx

---

action/protocol/account/transfer.go

as title
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

[action] Refactor handleTransfer()

---

blockchain/blockdao/blockdao.go
blockchain/filedao/filedao_legacy.go
blockchain/filedao/filedao_v2.go
blockchain/integrity/benchmark_test.go
db/kvstore_impl.go
db/kvstorewithcache.go
go.mod
go.sum
state/factory/factory.go
state/factory/statedb.go

Fixes #(issue)
- [] make test
- [] fullsync …

[test] Disable workingset cache in the benchmark test

---

ioctl/cmd/contract/contractshare.go

fix gosec errors [Expect directory permissions to be 0750 or less](https://github.com/iotexproject/iotex-core/security/code-scanning/125)
[Potential file inclusion via variable](https://github.com/iotexproject/iotex-core/security/code-scanning/124)
Fixes #(issue)
- [] make …

[ioctl] fix dir permission and potential file inclusion

---

api/web3server.go

fix  [Implicit memory aliasing in for loop.](https://github.com/iotexproject/iotex-core/security/code-scanning/60)
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] …

[api] fix Implicit memory aliasing in for loop.

---

.github/workflows/ci.yaml

PR #3515 seems to have weird go mod dependency issue, this is an attempted fix 
Fixes #(issue)
- [] fullsync

fix ci issue

---

api/grpcserver_test.go

Use t.Run to split test cases and enhance the code coverage.
Fixes #3587 
- Hardware:
- Toolchain:
- SDK:

[api] Use t.Run on TestGrpcServer_GetAccount

---

action/protocol/execution/protocol_test.go
api/serverV2_integrity_test.go
blockchain/integrity/benchmark_test.go
blockchain/integrity/integrity_test.go
blocksync/blocksync_test.go
blocksync/buffer_test.go
chainservice/builder.go
config/config.go
consensus/scheme/rolldpos/rolldpos_test.go
consensus/scheme/rolldpos/roundcalculator_test.go
db/builder.go
db/db_test.go
db/kvstore.go
e2etest/bigint_test.go
e2etest/local_test.go
e2etest/local_transfer_test.go
gasstation/gasstattion_test.go
state/factory/factory.go
state/factory/factory_test.go
state/factory/statedb.go
state/factory/workingset_test.go

As #3504 #3506 pre-fix
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] My changes generate no new …

delete config.Config in factory

---

ioctl/cmd/contract/contract.go
ioctl/cmd/contract/contractprepare.go
ioctl/util/compiler_contract.go
ioctl/util/compiler_contract_test.go

move solc compiler from go-ethereum
Fixes https://github.com/iotexproject/iotex-core/issues/3594
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

add solc compiler support

---

state/account_test.go

add test for account balance
Fixes https://github.com/iotexproject/iotex-core/issues/3410
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

check account balance add(-1)/sub(-1) 

---

CODEOWNERS

Introduced codeowners for repository

Define OWNER for each package #3609

---

api/grpcserver_test.go

add unit test for GetBlockMetas,StreamLogs
Fixes #3527
Fixes #3523
- [] make test
- Firmware version: macOS arm64
- Hardware:
- Toolchain:
- SDK:

add unit test for GetBlockMetas,StreamLogs

---

install-cli.sh

fix error 
`Architecture arm64 is not supported by this installation script`
Fixes #2690 
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

fix install-cli.sh

---

blockchain/config_privatekey.go
blockchain/config_privatekey_test.go

hange vault read data structure. adaptation vault web ui 
- Firmware version: macos arm64
- Hardware:
- Toolchain:
- SDK:

change vault read data structure

---

state/factory/workingset.go

add details to error, ErrDeltaStateMismatch and ErrReceiptRootMismatch
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

add error details

---

action/protocol/execution/protocol_test.go
action/protocol/execution/testdata-london/basefee.json
action/protocol/execution/testdata-london/basefee.sol

as title
Fixes https://github.com/iotexproject/iotex-core/issues/3647
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I …

[evm] add opBaseFee smart contract in London EVM

---

ioctl/newcmd/did/didregister.go
ioctl/newcmd/did/didregister_test.go
ioctl/newcmd/did/didupdate.go
ioctl/newcmd/did/didupdate_test.go

Refactor `didupdate` command in new `ioctl`, with the following note.
Fixes #3294 
- Hardware:
- Toolchain:
- SDK:

[ioctl] Build did update command line into new ioctl

---

action/protocol/execution/protocol_test.go
action/protocol/execution/testdata-london/datacopy.json

as title
Fixes #(issue)
- [] fullsync

[evm] set correct heights for Berlin/London tests

---

action/protocol/staking/protocol.go

as title
Fixes #(issue)
- [] fullsync

[staking] remove height from readCandCenterStateFromStateDB

---

action/protocol/rewarding/reward.go

Fixes #(issue)
- [] make test
- [] fullsync …

remove duplicate check err

---

ioctl/cmd/account/accountinfo.go
ioctl/cmd/account/accountnonce.go
ioctl/newcmd/account/account_test.go
ioctl/newcmd/account/accountbalance_test.go
ioctl/newcmd/account/accountinfo.go
ioctl/newcmd/account/accountinfo_test.go
ioctl/newcmd/account/accountnonce.go
ioctl/newcmd/account/accountnonce_test.go
ioctl/newcmd/action/action_test.go

Fixes  https://github.com/iotexproject/iotex-core/issues/3711
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have …

[ioctl] Remove nonce field in account info

---

action/protocol/execution/evm/evm_test.go
blockchain/genesis/genesis.go
blockchain/genesis/heightupgrade_test.go

as title
Fixes #(issue)
- [] fullsync

[genesis] set Okhotsk to activate at 01-11-2023 12am UTC

---

chainservice/builder.go
config/config.go
consensus/config.go
consensus/consensus.go
consensus/consensusfsm/consensus_ttl.go
consensus/consensusfsm/context.go
consensus/consensusfsm/mock_context_test.go
consensus/scheme/rolldpos/rolldpos.go
consensus/scheme/rolldpos/rolldpos_test.go
consensus/scheme/rolldpos/rolldposctx.go
consensus/scheme/rolldpos/rolldposctx_test.go
consensus/scheme/rolldpos/roundcalculator_test.go

as title
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK:

[config] move config.Consensus to consensus package

---

Makefile

Fixes #(issue)
- [] make test
- [] fullsync …

version info can be passed by env variable

---

.github/CODEOWNERS

Fixes #(issue)
- [] make test
- [] fullsync …

[github] Update CODEOWNER

---

action/protocol/account/transfer.go

code clean
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] …

[action] Clean code in handleTransfer

---

api/web3server_test.go

Fixes 
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

[api] complete web3 uint test 

---

.github/CODEOWNERS

Fixes #(issue)
- [] make test
- [] fullsync …

fix CODEOWNERS errors

---

chainservice/builder.go
e2etest/nodeinfo_test.go
misc/scripts/mockgen.sh
nodeinfo/config.go
nodeinfo/manager.go
nodeinfo/manager_test.go
test/mock/mock_nodeinfo/mock_manager.go

- use broadcastList instead of delegates to avoid ambiguity
- remove height dependent feature. Because node in old version only output some warn level message for unknown msg type, it's unnecessary to add that.
Fixes #(issue)
- Hardware:
- Toolchain:
- SDK:

[nodeinfo] keep updating broadcast list

---

action/protocol/execution/evm/evm_test.go
blockchain/genesis/genesis.go
blockchain/genesis/heightupgrade_test.go

[genesis] set Palau to activate at 04-04-2023 11pm UTC

---

.github/workflows/chatgpt.yaml
.github/workflows/ci.yaml

Use ChatGPT to review iotex-core code

add chatgpt code review

---

api/coreservice.go

fix #3756 
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have …

[api] Enable message batching

---

action/protocol/staking/ethabi/stake_base.go
action/protocol/staking/ethabi/stake_composite_buckets.go
action/protocol/staking/ethabi/stake_composite_buckets_test.go
action/protocol/staking/ethabi/stake_composite_bucketsbycandidate.go
action/protocol/staking/ethabi/stake_composite_bucketsbycandidate_test.go
action/protocol/staking/ethabi/stake_composite_bucketsbyindices.go
action/protocol/staking/ethabi/stake_composite_bucketsbyindices_test.go
action/protocol/staking/ethabi/stake_composite_bucketsbyvoter.go
action/protocol/staking/ethabi/stake_composite_bucketsbyvoter_test.go
action/protocol/staking/ethabi/stake_composite_bucketscount.go
action/protocol/staking/ethabi/stake_composite_bucketscount_test.go
action/protocol/staking/ethabi/stake_composite_totalstakingamount.go
action/protocol/staking/ethabi/stake_composite_totalstakingamount_test.go

The current contract bucket API only supports GRPC. This pull request adds support for Web3.
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK:

[staking] contract staking buckets support web3 api

---

action/protocol/staking/ethabi/stake_base.go
action/protocol/staking/ethabi/stake_contract_buckettypes.go
action/protocol/staking/ethabi/stake_contract_buckettypes_test.go

Add support for the BucketTypes API in Web3
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK:

[staking] Add BucketTypes web3 api

---

action/protocol/execution/evm/evm_test.go
blockchain/genesis/genesis.go
blockchain/genesis/heightupgrade_test.go

as title
Fixes #(issue)
- [] fullsync

[genesis] set Quebec to activate at 07-12-2023 11pm UTC

---

blockindex/sgd_indexer_test.go
e2etest/sgd_registry_test.go

improve sgd indexer test coverage
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

[iip15] improve sgd indexer test coverage

---

api/web3server_test.go
api/web3server_utils.go

fix typo in (#3952)
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK:

[api] fix typo should use EVMNetworkID()

---

blockchain/genesis/genesis.go
blockchain/genesis/heightupgrade_test.go
config/config.go
config/config_test.go

Naming the next HF Height as `Sumatra`
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

[config] Add SumatraHeight

---

action/protocol/execution/protocol_test.go
action/protocol/execution/testdata-london/CVE-2021-39137-attack-replay.json

found these 2 tests are not using correct data
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK:

[evm] correct test

---

chainservice/chainservice.go

see #3988 
Fixes #3988
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

remove unused chainIDmetrics()

---

api/coreservice.go
api/grpcserver.go
api/web3server.go
api/web3server_utils.go
api/web3server_utils_test.go
go.mod
go.sum

Add the gasPrice parameter to the estimated gas API to allow passing custom gasPrice to evm
The gRPC part can only be updated after the PR is merged.
https://github.com/iotexproject/iotex-proto/pull/137
Fixes #3984 
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

support gasPrice param in  estimatedGas API

---

ioctl/cmd/root.go
ioctl/cmd/ws/ws.go
ioctl/cmd/ws/wsmessage.go
ioctl/cmd/ws/wsmessagequery.go
ioctl/cmd/ws/wsmessagesend.go

znode message commands
Fixes #3982 

feat(ioctl): support znode message committing and querying commands(based #3986)

---

ioctl/config/config.go
ioctl/config/configsetget.go
ioctl/newcmd/config/config.go
ioctl/newcmd/config/config_test.go

default w3bstream node endpoint

feat(ioctl): default w3bstream endpoint

---

action/protocol/execution/evm/evm.go
action/protocol/execution/evm/evm_test.go
go.mod
go.sum

small clean-up.
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

[evm] remove unnecessary field from evm.Params

---

action/protocol/staking/handlers.go

Because the original `fetchBucket()` function also included some validation logic, in order to make it clearer, rename it to `fetchBucketAndValidate()`. Additionally, the part responsible for get the bucket was extracted and created as a new  `fetchBucket()`.
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I …

[staking] Refactor fetchBucket function

---

ioctl/cmd/bc/bcblock.go

--verbose flag has been accidentally changed to _verbose
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

[ioctl] fix verbose flag

---

actpool/queueworker.go

Fixes #(issue)
- [] make test
- [] fullsync …

[actpool] skip adding accounts if pending acts is empty

---

ioctl/cmd/ws/ws.go
ioctl/config/config.go
ioctl/config/configsetget.go
ioctl/newcmd/config/config.go
ioctl/newcmd/config/config_test.go

add IPFS endpoint and gateway config
Fixes #(issue)

feat(ioctl): ipfs endpoint and ipfs gateway config

---

go.mod
go.sum
ioctl/cmd/ws/ws_test.go
ioctl/cmd/ws/wsproject.go
ioctl/cmd/ws/wsprojectcreate.go
ioctl/cmd/ws/wsprojectupdate.go

feat(ioctl): optimize w3bstream project subcommand

---

action/candidate_activate.go
action/candidate_endorsement.go
action/envelope.go
go.mod
go.sum

As part of IIP-22 implementaion, introduce the CandidateEndorsement action to represent endorse / unendorse operations
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have added tests that …

[action] Define CandidateEndorsement Action

---

action/protocol/staking/endorsement_statemanager.go
action/protocol/staking/endorsement_statemanager_test.go
action/protocol/staking/protocol.go

`EndorsementStatemanager` is used to manager Put and Get operations of endorsement
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have added tests that prove my fix is effective or that my …

[staking] Implement Endorsement Statemanager

---

server/itx/heartbeat.go
server/itx/server.go

as title.
Fixes #4049 
- [] fullsync
- [] My changes generate no …

[server] add operator address into node's metrics

---

action/protocol/context.go
action/protocol/execution/protocol_test.go
api/coreservice.go
api/web3server.go
blockchain/integrity/integrity_test.go

…tra height
Fixes #(issue)
- [] make test
- [] fullsync
**Test …

enable 48kB execution data limit and deterministic deployment at Sumatra height

---

action/rlp_tx.go
action/rlp_tx_test.go
action/sealedenvelope.go
action/sealedenvelope_test.go

after discussion we'll defer access list tx enabling.
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

[action] defer access list tx enabling

---

action/protocol/execution/evm/evm_test.go
action/protocol/execution/protocol_test.go
blockchain/genesis/genesis.go
blockchain/genesis/heightupgrade_test.go

set Sumatra height for mainnet
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

[genesis] set Sumatra to activate at 02-08-2024 00:45:45AM UTC

---

blockchain/genesis/genesis_test.go

Fixes #4122 
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] Any …

[test] Add unit test for genesis

---

blockchain/integrity/benchmark_test.go

Fixes #4067 
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] Any …

[benchmark] Fix integrity benchmark

---

api/web3server_test.go
api/web3server_utils_test.go

Fixes #4117 
- [] make test
- [] fullsync
- …

feat(test): add unit test web3server_utils

---

action/protocol/staking/vote_bucket_test.go

Fixes #4103 
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

[test] Add test for VoteBucket

---

e2etest/nodeinfo_test.go

Fixes #4162 
- Hardware:
- Toolchain:
- SDK:
- [] Any dependent changes have been merged and published in downstream …

[e2etest] Fix flaky test 

---

api/http.go
api/http_test.go

Fixes #4132 
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

feat(api): get method return msg

---

blockchain/block/runnable_test.go

Improve test coverage
Fixes #4119
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have performed a self-review of my …

[blockchain] add unit tests for runnable.go

---

blockchain/genesis/genesis.go
blockchain/genesis/heightupgrade_test.go
config/config.go
config/config_test.go

As title.
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] …

[genesis] add Tsunami block height

---

blockchain/integrity/integrity_test.go

as title.
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

add e2etest for refactor fresh account conversion

---

action/protocol/staking/handler_candidate_endorsement_test.go
action/protocol/staking/handler_candidate_selfstake_test.go
action/protocol/staking/handlers_test.go

as title.
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

[staking] testing endorsed bucket with existing staking actions

---

action/protocol/execution/evm/evm_test.go
blockchain/genesis/genesis.go
blockchain/genesis/heightupgrade_test.go

Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] My …

[genesis] set Tsunami to activate at 04-03-2024 00:52:05 AM +UTC

---

action/protocol/execution/evm/evmstatedbadapter.go

Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- …

[evm] clean-up

---

action/protocol/execution/evm/contract.go
action/protocol/staking/protocol.go
actpool/queueworker.go
api/websocket.go

fix function names
Fixes #(issue)
- [] docs
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] Any dependent changes …

chore: fix function names

---

ioctl/cmd/ws/contracts/Makefile
ioctl/cmd/ws/contracts/abis/FleetManagement.json
ioctl/cmd/ws/contracts/abis/ProjectDevice.json
ioctl/cmd/ws/contracts/abis/ProjectRegistrar.json
ioctl/cmd/ws/contracts/abis/W3bstreamProject.json
ioctl/cmd/ws/contracts/abis/W3bstreamProver.json
ioctl/cmd/ws/contracts/abis/W3bstreamRouter.json
ioctl/cmd/ws/contracts/fleetmanagement.go
ioctl/cmd/ws/contracts/gen.go
ioctl/cmd/ws/contracts/projectdevice.go
ioctl/cmd/ws/contracts/projectregistrar.go
ioctl/cmd/ws/contracts/w3bstreamproject.go
ioctl/cmd/ws/contracts/w3bstreamprover.go
ioctl/cmd/ws/contracts/w3bstreamrouter.go

sync the latest w3bstream contracts and generate go code
contracts:
1. FleetManagement
2. ProjectDevice
3. ProjectRegister
4. W3bstreamProject
5. W3bstreamProver
6. W3bstreamRouter
Fixes #(issue)
- Hardware:
- Toolchain:
- SDK:

[ioctl][ws][#1] sync latest w3bstream contract abis and generate go code

---

action/candidate_transfer_ownership.go
blockindex/actionindex.go
blockindex/blockindex.go

fix some function names
- [] Docs
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] New and existing unit tests pass locally with my …

chore: fix some function names

---

action/protocol/staking/vote_reviser.go

This bug has not been triggered, and it will not be triggered unless new a vote revise height is set. So it is safe to merge it without hardfork.
Fixes #(issue)
- [] make test
- [] fullsync
- …

fix a bug in vote reviser

---

ioctl/cmd/action/stake2.go
ioctl/cmd/action/stake2migrate.go

as title
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] Any …

[ioctl] add stakemigrate command

---

e2etest/native_staking_test.go

cover four failure cases
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have performed a self-review …

more e2etest for native staking migration

---

blockchain/genesis/genesis.go

as title
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] Any …

[genesis] set default staking contract v2 address & start height for mainnet

---

state/factory/factory.go
state/factory/factory_test.go
state/factory/util.go
state/factory/workingsetstore.go

Read states from two layer trie for factory and its working set store.
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

fix read states

---

ioctl/cmd/ws/wsprojectconfig.go

Fixes #(issue)
- [] make test
- [] fullsync …

[ioctl] add data-source-pubKey param in ws project config cmd

---

ioctl/cmd/ws/contracts/Makefile
ioctl/cmd/ws/contracts/abis/W3bstreamVMType.json
ioctl/cmd/ws/contracts/gen.go
ioctl/cmd/ws/contracts/w3bstreamvmtype.go
ioctl/cmd/ws/ws.go
ioctl/cmd/ws/wsvmtype.go
ioctl/cmd/ws/wsvmtypequery.go
ioctl/cmd/ws/wsvmtyperegister.go
ioctl/cmd/ws/wsvmtypestate.go
ioctl/config/config.go
ioctl/config/configsetget.go
ioctl/newcmd/config/config.go
ioctl/newcmd/config/config_test.go

1. add `register` cmd
2. add `pause` and `resume` cmd
3. add `query` cmd
- [] make test
- [] …

[ioctl] add ws prover vmtype cmd

---

ioctl/cmd/bc/bcdelegate.go

as title
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

[ioctl] add ID into candidate display

---

ioctl/cmd/ws/wsprojectconfig.go

Fixes #(issue)
- [] make test
- [] fullsync …

[ioctl] change vmType from string to uint64

---

blockindex/indexer.go

fix some comments
Fixes #(issue)
- Docs Update
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] Any dependent …

chore: fix function name

---

ioctl/cmd/action/action.go

as title
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] Any …

[ioctl] print act hash when execute act

---

blockchain/config.go
chainservice/builder.go
db/builder.go
db/config.go
db/db_pebble.go
db/db_pebble_test.go
go.mod

as title
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- …

[db] implement kvstore on pebbledb

---

blockchain/genesis/genesis.go
blockchain/genesis/heightupgrade_test.go
config/config.go
config/config_test.go

add next hard-fork height
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have performed a self-review …

[genesis] add Vanuatu block height

---

ioctl/cmd/ioid/applyioid.go
ioctl/cmd/ioid/contracts/abis/ProjectRegistry.json
ioctl/cmd/ioid/contracts/projectregistry.go
ioctl/cmd/ioid/name.go
ioctl/cmd/ioid/project.go
ioctl/cmd/ioid/projectdevice.go
ioctl/cmd/ioid/projectregister.go
ioctl/config/configsetget.go
ioctl/newcmd/config/config.go

1. update ioid project register func
2. update default contract address 
- [] make test
- [] …

[ioctl] update ioid project register func

---

action/const.go
action/evm_transaction.go
action/protocol/account/protocol.go
action/protocol/account/transfer.go
action/protocol/account/transfer_test.go
action/protocol/execution/evm/context.go
action/protocol/execution/evm/evm.go
action/protocol/execution/evm/evm_test.go
action/protocol/execution/protocol.go
action/protocol/poll/consortium.go
action/protocol/poll/staking_committee.go
action/protocol/protocol.go
action/protocol/rewarding/fund.go
action/protocol/rewarding/fund_test.go
action/protocol/rewarding/protocol.go
action/protocol/rewarding/protocol_test.go
action/protocol/staking/handler_candidate_endorsement_test.go
action/protocol/staking/handler_candidate_selfstake_test.go
action/protocol/staking/handler_stake_migrate_test.go
action/protocol/staking/handlers_test.go
action/protocol/staking/protocol.go

1. spilt gas and burn base for transfer protocol
2. TODO: add other protocols
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] My code follows the style guidelines …

[protocol] split gas fee and burn base fee

---

action/actctx.go
action/builder.go
action/execution.go
action/protocol/execution/protocol_test.go
e2etest/contract_staking_test.go
go.mod
go.sum

As discussed, make this change to be fully compatible with Ethereum.
Fixes #(issue)
- Hardware:
- Toolchain:
- SDK:
- [] I …

[action] move AccessList to AbstractAction

---

action/blob_data.go
action/blob_data_test.go
action/envelope.go
test/mock/mock_envelope/mock_envelope.go

Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] My …

[action] add blob data definition and related API

---

action/actctx.go
action/builder.go
action/const.go
action/envelope.go
action/protocol/generic_validator.go
action/tx_dynamic_fee.go
action/tx_dynamic_fee_test.go

based on #4391
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] Any …

[action] add dynamicFee tx

---

action/actctx.go
action/blob_data.go
action/blob_data_test.go
action/builder.go
action/envelope.go
action/tx_blob.go
action/tx_blob_test.go

1. add blob tx data type and definition
2. TODO: convert into native action and native action convert back
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] My code …

[action] add EIP-4844 blob tx

---

blockchain/block/block.go
blockchain/blockdao/blob_store.go
blockchain/blockdao/blockdao.go
blockchain/blockdao/blockdao_test.go
blockchain/integrity/integrity_test.go
blockindex/indexbuilder.go
blockindex/indexbuilder_test.go
chainservice/builder.go
go.mod
go.sum
test/mock/mock_blockdao/mock_blockdao.go
test/mock/mock_envelope/mock_envelope.go

store blobs separately
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have performed a self-review of …

[blockdao] store blobs

---

action/envelope.go
action/tx_access_list.go
action/tx_blob.go
action/tx_dynamic_fee.go
action/tx_legacy.go
test/mock/mock_envelope/mock_envelope.go

a quick change to return effective gas price for a tx
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I …

[action] add EffectiveGasPrice()

---

action/protocol/context.go
action/protocol/generic_validator.go
actpool/actpool_test.go
blockchain/genesis/genesis.go
state/factory/workingset.go

Same as ethereum, we limit each block to contain a maximum of 2 blob transactions.
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] …

[eip4844] blob Tx limitation per block

---

go.mod
go.sum

Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

[evm] introduce Scrypt precompile contract

---

api/web3server.go
api/web3server_integrity_test.go

as title
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] Any …

[api] correct eth_maxPriorityFeePerGas method name

---

action/action.go
action/envelope.go
action/envelope_test.go
action/sealedenvelope.go
action/tx_blob.go
test/mock/mock_envelope/mock_envelope.go

as title
based on #4409 
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

[action] blob hash keep the same with or w/o sidecar

---

dispatcher/dispatcher.go

as title
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] Any …

[dispatcher] dispatch action sync msg

---

action/blob_data.go
action/blob_data_test.go
action/protocol/eip4844_test.go
blockchain/genesis/genesis.go
state/factory/workingset.go

as title
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] Any …

[action] SanityCheck validate blobTx must have blob

---

action/blob_data.go
action/builder.go
action/envelope.go
action/envelope_test.go
action/protocol/context.go
action/rlp_tx.go
action/rlp_tx_test.go
action/sealedenvelope.go
action/tx_container.go
api/web3server.go
api/web3server_utils.go
blockchain/integrity/integrity_test.go
state/factory/workingset.go

Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] My …

[action] enable tx container

---

go.mod
go.sum

Fixes #(issue)
- [] make test
- [] fullsync …

update go mod for cancun release tag

---

api/coreservice.go

as title
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] Any …

[api] Fix blob tx not broadcasted as hash

---

action/blob_data_test.go
action/rlp_tx_test.go
action/tx_access_list.go
action/tx_access_list_test.go
action/tx_blob.go
action/tx_blob_test.go
action/tx_dynamic_fee_test.go
action/tx_legacy_test.go

during testing it is found the return result from web3js API is missing sidecar
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

[action] fix missing sidecar in ToEthTx()

---

actpool/actpool.go

ignore load action error to not block the start up
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] New and existing unit tests …

[actpool] ignore load action error

---

action/protocol/generic_validator.go

Fixes #(issue)
- [] make test
- [] fullsync …

[action] tx fee cap can cover last block's base fee

---

api/coreservice.go
api/grpcserver.go
api/web3server.go

as title
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] Any …

[metric] Latency metrics for web3&grpc api

---

action/tx_container.go

as title, it is called by actionstore module to serialize/de-serialize blob tx
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] My code follows the style guidelines …

[action] txContainer.Proto() called by actionstore

---

actpool/actionstore.go
actpool/actionstore_test.go

as title
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] Any dependent changes have …

[actpool] Fix actionStore stored size

---

action/protocol/context.go
action/protocol/generic_validator.go
action/rlp_tx_test.go
action/tx_container.go
actpool/actpool.go
actpool/actpool_test.go
e2etest/blobtx_test.go
e2etest/dynamicfee_tx_test.go
state/factory/workingset.go

…legacy tx
Fixes #(issue)
- [] make test
- [] fullsync
**Test …

[workingset] verify correct tx after unfolding

---

actpool/actionstore.go
actsync/actionsync.go
blockchain/blockchain.go

as title
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] Any …

[metrics] improve metrics

---

action/action.go
actpool/actpool.go
actpool/actpool_test.go

block transfer with invalid address from entering into actpool.
This is more lightweight as compared to (#4410), avoid adding change to `generic_validator`, which will be run when committing every block
Fixes #(issue)
- [] make test
- [] fullsync
- [] Other test (please …

[actpool] reject invalid transfer address

---

blockchain/blockdao/blockdao.go

as title
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] Any …

[api] Cache for BlockByHeight and TransactionLogs

---

action/protocol/rewarding/protocol.go
action/protocol/staking/protocol.go
action/protocol/staking/staking_statereader.go

as title
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] Any …

Fix standalone mode

---

gasstation/gasstattion.go

- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] Any dependent …

[api] correct gas price

---

blockchain/config.go

this field is no longer needed
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

[config] remove BlobPurgeInterval

---

actpool/config.go
e2etest/e2etest.go
server/itx/server_test.go

enable action store by default, simplify node upgrade process
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] New and existing …

[config] Configure action store as default

---

action/protocol/context.go
action/protocol/staking/handlers_test.go
action/protocol/staking/validations.go

check staking duration in Validate().
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

[staking] check duration upper limit

---

actpool/config.go
actpool/options.go
e2etest/e2etest.go
server/itx/server_test.go

as title
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] Any …

[actpool] refactor actionstore config

---

Makefile

as title
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] …

Fix binary NoBuildInfo

---

api/web3server.go
api/web3server_integrity_test.go

as title.
Fixes #4481
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

[api] fix eth_estimateGas

---

action/protocol/execution/evm/evm_test.go
blockchain/genesis/genesis.go
blockchain/genesis/heightupgrade_test.go

as title
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

[genesis] set Vanuatu to activate at Nov-25-2024 01:05:15AM +UTC

---

action/protocol/context.go
action/protocol/execution/evm/evm.go
action/protocol/protocol.go

as title
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] …

Fix feecap less than basefee when estimateGas and call

---

blockchain/config.go
chainservice/builder.go
config/config.go
e2etest/local_test.go
e2etest/staking_test.go
state/factory/minter.go
state/factory/workingset.go

Fixes #4484
Add a deadline mechanism to Mint block, mint will end upon reaching it, even if there are remaining unprocessed actions. 
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

[mint] deadline for mint block

---

blockchain/blockchain.go
state/factory/workingset.go

as title
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

[metric] Update mint metric

---

action/protocol/execution/evm/evm_test.go
blockchain/genesis/genesis.go
blockchain/genesis/heightupgrade_test.go

Fixes #(issue)
- [] make test
- [] fullsync …

[genesis] set Vanuatu to activate at Dec-17-2024 02:20:40AM +UTC

---

blocksync/blocksync.go
blocksync/buffer.go

as title.
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

[blocksync] remove redundant clean-up

---

state/factory/workingsetstore.go
state/factory/workingsetstore_factory.go
state/factory/workingsetstore_statedb.go

1. add a common struct `workingSetStoreCommon`, and extract common funcs to simplify workingsetstore.
2. based on this, will implement workingset for archive statedb in PRs to come
Fixes #(issue)
- [] fullsync
- Hardware:
- …

[factory] refactore workingsetstore

---

state/factory/daoretrofitter.go
state/factory/statedb.go

add this interface the encapsulate DAO-related methods to accommodate archive-mode.
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have performed a self-review of my …

[factory] add daoRetrofitter interface

---

action/protocol/execution/evm/evmstatedbadapter.go
api/http.go
api/web3server.go
api/websocket.go

as title
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] …

[api] Recovery api panic

---

api/coreservice_test.go
api/web3server.go
api/web3server_integrity_test.go
api/web3server_test.go
api/web3server_utils.go
api/web3server_utils_test.go

as title.
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

[api] parse block number from request

---

blockchain/blockdao/grpcblockdao.go

Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- …

grpcdao connect securely

---

README.md

Fixes #(issue)
- [] make test
- [] fullsync …

add star history to README

---

state/factory/factory.go
state/factory/statedb.go
test/mock/mock_factory/mock_factory.go

Needed by `eth_traceTransaction` to get to a particular state at particular block height.
Fixes #(issue)
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] …

[factory] WorkingSetAtHeight() to take pre-actions

---

action/protocol/context.go
state/factory/workingset.go

HF passed, switch to use the post-HF behavior.
Fixes #(issue)
- Hardware:
- Toolchain:
- SDK: …

[workingset] use processWithCorrectOrder() always

---

action/protocol/context.go
action/protocol/generic_validator.go
e2etest/blobtx_test.go
e2etest/dynamicfee_tx_test.go

as title, remove the check after HF activation.
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have …

[protocol] remove tx type check in generic validator

---

action/protocol/context.go
action/protocol/generic_validator.go
state/factory/workingset.go

as title, switch to validate tx with state after HF. based on #4540 
please see 2nd commit
Fixes #(issue)
- Hardware:
- Toolchain:
- SDK: …

[protocol] validate tx with state always

---

chainservice/builder.go
chainservice/chainservice.go
e2etest/local_actpool_test.go
p2p/agent.go
server/itx/server.go

Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- …

[p2p] introduce account rate limit 

---

tools/minicluster/minicluster.go

no permission to write to /var/data
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

fix minicluster permission issue

---

action/evm_transaction.go
actpool/actioniterator/actioniterator.go
api/coreservice.go

fix some function names in comment
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] Any dependent changes have been merged and published in downstream modules

chore: fix some function names in comment

---

blockchain/block/blockstore.go

fix comment
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] Any dependent changes have been merged and published …

chore: fix comment

---

p2p/agent.go

as title, based on #4553.
Simulatioin on testnet shows it can filter out attack traffic using duplicate ACTIONS
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have performed a self-review of my …

[p2p] de-duplicate RPC ACTION/ACTIONS message

---

state/factory/factory.go
state/factory/readonlykv.go
state/factory/statedb.go

Fixes #(issue)
- [] make test
- [] fullsync …

read only working set

---

action/protocol/staking/viewdata.go

snapshots could be deleted in `Commit`
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

clean up snapshots

---

blockchain/genesis/genesis.go
blockchain/genesis/genesis_test.go

reduce to 30m
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- …

set gas limit to wake hardfork

---

gasstation/gasstattion.go

as title
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] …

[api] Fix feeHistory panic

---

action/protocol/context.go
action/protocol/rewarding/protocol.go
action/protocol/rewarding/reward_test.go
action/protocol/staking/vote_reviser_test.go
chainservice/builder.go
chainservice/builder_test.go
consensus/consensusfsm/consensus_ttl.go
e2etest/contract_staking_v2_test.go
testutil/genesis.go

as title
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

Enable Wake Height

---

action/protocol/staking/ethabi/common/types.go

Fixes #(issue)
- [] make test
- [] fullsync …

Fix timestamped bucket api format

---

consensus/consensusfsm/fsm.go
consensus/scheme/rolldpos/chainmanager.go

as title
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] …

Fix blockchain metric conflicts

---

blockchain/blockchain.go
blockchain/filedao/filedao.go
consensus/scheme/rolldpos/chainmanager.go
consensus/scheme/rolldpos/rolldpos.go
consensus/scheme/rolldpos/rolldpos_test.go
state/factory/statedb.go
test/mock/mock_blockchain/mock_blockchain.go

as title
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

Ignore vote error if already committed

---

action/protocol/rewarding/reward.go

as title.
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

[rewarding] fix reward logs type

---

chainservice/chainservice.go

if no new block were received, and the block chain height stays the same, restart the service
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] My code follows the …

restart the service if the height stays the same for one minute

---

state/factory/statedb.go

Currently, there is an issue where child workingset may not be written to the database due to the timing of commits in the parent working set. Specifically, this problem arises when there are multiple parent workingsets. The details are as follows:
1 - Driven by the consensus process, after validating `block N`, the working set `ws(N0)` is written to the working set pool.
2 - In a separate thread, under the block synchronization mechanism, validating `block N` will also write `ws(N1)` to the working set pool, which then overrides `ws(N0)`.
3 - If we assume that while preparing `block N+1`, a child working set `ws(N0).(N+1)` is created based on `ws(N0)`.
4 - However, during the commit of `block N`, the working set being used is `ws(N1)`.
5 - As a result, when attempting to commit …

Fix child workingset may not be commit

---

chainservice/builder.go
e2etest/contract_staking_v2_test.go

as title
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

[staking] unmute staking contract v2

---

api/web3server_utils.go

Fixes #4640 
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have …

[api] treat pending block request as latest

---

chainservice/builder.go
p2p/agent.go
server/itx/server.go

as title
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

[p2p] separate p2p topic for consensus and action msg

---

action/protocol/execution/evm/evm_test.go
blockchain/genesis/genesis.go
blockchain/genesis/heightupgrade_test.go

Fixes #(issue)
- [] make test
- [] fullsync …

[genesis] set Wake to activate at Jun-19-2025 01:28:25 AM +UTC

---

blockchain/blockchain.go
consensus/scheme/rolldpos/proposalpool.go
state/factory/minter.go

Fixes #(issue)
- [] make test
- [] fullsync …

Add more metrics

---

blockchain/blockchain.go
blocksync/blocksync.go
chainservice/chainservice.go
consensus/scheme/rolldpos/rolldposctx.go
consensus/scheme/standalone.go
server/itx/pauseable.go
server/itx/server.go
test/mock/mock_blockchain/mock_blockchain.go

as title
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have …

[admin] pause/unpause blockchain

---

go.mod
go.sum

Fixes #(issue)
- [] make test
- [] fullsync …

Update dependencies to stable tag versions

---

api/coreservice.go
api/coreservice_test.go
api/mock_apicoreservice.go
api/web3server.go
api/web3server_test.go

as title
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

support historical block height in eth_estimateGas

---

action/Makefile
action/candidate_activate.go
action/candidate_endorsement.go
action/candidate_register.go
action/candidate_transfer_ownership.go
action/candidate_update.go
action/native_staking_contract_abi.go
action/native_staking_contract_abi.json
action/native_staking_contract_interface.sol
action/stake_adddeposit.go
action/stake_changecandidate.go
action/stake_create.go
action/stake_migrate.go
action/stake_reclaim.go
action/stake_restake.go
action/stake_transferownership.go

as title
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

[refactor] unify the native staking contract interface

---

action/protocol/context.go
action/protocol/staking/protocol.go
blockchain/genesis/genesis.go

Set the min self stake to keep a delegate active. Default to 1M IOTX
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK: …

min self stake to be active

---

api/blocklistener_test.go

Fixes #4111 
- [] make test
- [] fullsync
- …

[4111] Add tests for blocklistener error handling

---

go.mod
go.sum

v2.13.0 fixes compatible issues with M2
Fixes #(issue)
- [] make test
- [] fullsync
- Hardware:
- Toolchain:
- SDK:
- [] I have performed …

upgrade gomonkey

---

action/protocol/staking/viewdata.go

Fixes #(issue)
- [] make test
- [] fullsync …

Fix viewdata snapshot
